"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from .basesdk import BaseSDK
from pipeshub_sdk import errors, models, utils
from pipeshub_sdk._hooks import HookContext
from pipeshub_sdk.types import OptionalNullable, UNSET
from pipeshub_sdk.utils import get_security_from_env
from pipeshub_sdk.utils.unmarshal_json_response import unmarshal_json_response
from typing import Any, Mapping, Optional


class AIModelsProviders(BaseSDK):
    def get_available_models_by_type(
        self,
        *,
        model_type: models.ModelType,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.GetAvailableModelsByTypeResponse:
        r"""Get available models by type

        Returns a **flattened list** of individual AI models of the requested type,
        suitable for use in selection dropdowns and model-picker UIs.

        Each provider configuration entry may specify multiple comma-separated model
        names; this endpoint expands those into one object per model name so callers
        receive a flat, enumerable collection.

        **Flattening rules:**
        - Only the **first** model in a multi-model provider entry is marked
        `isDefault: true`; all subsequent models from the same entry get `false`.
        - `modelFriendlyName` is included **only** when the provider entry contains
        exactly one model name (not a comma-separated list).
        - When no providers of the requested type are configured the endpoint still
        returns HTTP **200** with an empty `models` array — this is **not** an error.

        **Access control:** requires a valid bearer token. For OAuth tokens the
        `config:read` scope must be present; regular JWT bearer tokens pass through
        without scope enforcement.


        :param model_type: Category of AI model to retrieve.

            Must be one of: `llm`, `embedding`, `ocr`, `slm`, `reasoning`, `multiModal`, `imageGeneration`, `tts`, `stt`.

        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.GetAvailableModelsByTypeRequest(
            model_type=model_type,
        )

        req = self._build_request(
            method="GET",
            path="/configurationManager/ai-models/available/{modelType}",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=False,
            request_has_path_params=True,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = self.do_request(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="getAvailableModelsByType",
                oauth2_scopes=["config:read"],
                security_source=get_security_from_env(
                    self.sdk_configuration.security, models.Security
                ),
            ),
            request=req,
            error_status_codes=["400", "401", "403", "4XX", "500", "5XX"],
            retry_config=retry_config,
        )

        response_data: Any = None
        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(
                models.GetAvailableModelsByTypeResponse, http_res
            )
        if utils.match_response(http_res, "400", "application/json"):
            response_data = unmarshal_json_response(
                errors.GetAvailableModelsByTypeBadRequestErrorData, http_res
            )
            raise errors.GetAvailableModelsByTypeBadRequestError(
                response_data, http_res
            )
        if utils.match_response(http_res, "401", "application/json"):
            response_data = unmarshal_json_response(
                errors.GetAvailableModelsByTypeUnauthorizedErrorData, http_res
            )
            raise errors.GetAvailableModelsByTypeUnauthorizedError(
                response_data, http_res
            )
        if utils.match_response(http_res, "403", "application/json"):
            response_data = unmarshal_json_response(
                errors.GetAvailableModelsByTypeForbiddenErrorData, http_res
            )
            raise errors.GetAvailableModelsByTypeForbiddenError(response_data, http_res)
        if utils.match_response(http_res, "500", "application/json"):
            response_data = unmarshal_json_response(
                errors.GetAvailableModelsByTypeInternalServerErrorData, http_res
            )
            raise errors.GetAvailableModelsByTypeInternalServerError(
                response_data, http_res
            )
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.PipeshubDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.PipeshubDefaultError(
                "API error occurred", http_res, http_res_text
            )

        raise errors.PipeshubDefaultError("Unexpected response received", http_res)

    async def get_available_models_by_type_async(
        self,
        *,
        model_type: models.ModelType,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.GetAvailableModelsByTypeResponse:
        r"""Get available models by type

        Returns a **flattened list** of individual AI models of the requested type,
        suitable for use in selection dropdowns and model-picker UIs.

        Each provider configuration entry may specify multiple comma-separated model
        names; this endpoint expands those into one object per model name so callers
        receive a flat, enumerable collection.

        **Flattening rules:**
        - Only the **first** model in a multi-model provider entry is marked
        `isDefault: true`; all subsequent models from the same entry get `false`.
        - `modelFriendlyName` is included **only** when the provider entry contains
        exactly one model name (not a comma-separated list).
        - When no providers of the requested type are configured the endpoint still
        returns HTTP **200** with an empty `models` array — this is **not** an error.

        **Access control:** requires a valid bearer token. For OAuth tokens the
        `config:read` scope must be present; regular JWT bearer tokens pass through
        without scope enforcement.


        :param model_type: Category of AI model to retrieve.

            Must be one of: `llm`, `embedding`, `ocr`, `slm`, `reasoning`, `multiModal`, `imageGeneration`, `tts`, `stt`.

        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.GetAvailableModelsByTypeRequest(
            model_type=model_type,
        )

        req = self._build_request_async(
            method="GET",
            path="/configurationManager/ai-models/available/{modelType}",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=False,
            request_has_path_params=True,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = await self.do_request_async(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="getAvailableModelsByType",
                oauth2_scopes=["config:read"],
                security_source=get_security_from_env(
                    self.sdk_configuration.security, models.Security
                ),
            ),
            request=req,
            error_status_codes=["400", "401", "403", "4XX", "500", "5XX"],
            retry_config=retry_config,
        )

        response_data: Any = None
        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(
                models.GetAvailableModelsByTypeResponse, http_res
            )
        if utils.match_response(http_res, "400", "application/json"):
            response_data = unmarshal_json_response(
                errors.GetAvailableModelsByTypeBadRequestErrorData, http_res
            )
            raise errors.GetAvailableModelsByTypeBadRequestError(
                response_data, http_res
            )
        if utils.match_response(http_res, "401", "application/json"):
            response_data = unmarshal_json_response(
                errors.GetAvailableModelsByTypeUnauthorizedErrorData, http_res
            )
            raise errors.GetAvailableModelsByTypeUnauthorizedError(
                response_data, http_res
            )
        if utils.match_response(http_res, "403", "application/json"):
            response_data = unmarshal_json_response(
                errors.GetAvailableModelsByTypeForbiddenErrorData, http_res
            )
            raise errors.GetAvailableModelsByTypeForbiddenError(response_data, http_res)
        if utils.match_response(http_res, "500", "application/json"):
            response_data = unmarshal_json_response(
                errors.GetAvailableModelsByTypeInternalServerErrorData, http_res
            )
            raise errors.GetAvailableModelsByTypeInternalServerError(
                response_data, http_res
            )
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.PipeshubDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.PipeshubDefaultError(
                "API error occurred", http_res, http_res_text
            )

        raise errors.PipeshubDefaultError("Unexpected response received", http_res)
