"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: 9430f0363adf

from .basesdk import BaseSDK
from .httpclient import AsyncHttpClient, ClientOwner, HttpClient, close_clients
from .sdkconfiguration import SDKConfiguration
from .utils.logger import Logger, get_default_logger
from .utils.retries import RetryConfig
import httpx
import importlib
from pipeshub_sdk import models, utils
from pipeshub_sdk._hooks import SDKHooks
from pipeshub_sdk.types import OptionalNullable, UNSET
import sys
from typing import Callable, Dict, List, Optional, TYPE_CHECKING, Union, cast
import weakref

if TYPE_CHECKING:
    from pipeshub_sdk.agentconversations import AgentConversations
    from pipeshub_sdk.agents import Agents
    from pipeshub_sdk.agenttemplates import AgentTemplates
    from pipeshub_sdk.aimodelsconfiguration import AiModelsConfiguration
    from pipeshub_sdk.aimodelsproviders import AiModelsProviders
    from pipeshub_sdk.authconfig_sdk import AuthConfigSDK
    from pipeshub_sdk.authenticationconfiguration import AuthenticationConfiguration
    from pipeshub_sdk.authenticationconfigurations import AuthenticationConfigurations
    from pipeshub_sdk.configuration_manager import ConfigurationManager
    from pipeshub_sdk.connector_sdk import ConnectorSDK
    from pipeshub_sdk.connectorconfiguration import ConnectorConfiguration
    from pipeshub_sdk.connectorconfigurations import ConnectorConfigurations
    from pipeshub_sdk.connectorcontrols import ConnectorControls
    from pipeshub_sdk.connectorfilters import ConnectorFilters
    from pipeshub_sdk.connectorinstances import ConnectorInstances
    from pipeshub_sdk.connectoroauth import ConnectorOAuth
    from pipeshub_sdk.connectorregistry import ConnectorRegistry
    from pipeshub_sdk.connectors import Connectors
    from pipeshub_sdk.conversations import Conversations
    from pipeshub_sdk.crawlingjobs import CrawlingJobs
    from pipeshub_sdk.documentmanagement import DocumentManagement
    from pipeshub_sdk.folders import Folders
    from pipeshub_sdk.knowledgebases import KnowledgeBases
    from pipeshub_sdk.mcp import Mcp
    from pipeshub_sdk.metricscollection import MetricsCollection
    from pipeshub_sdk.oauth_configuration_1 import OAuthConfiguration1
    from pipeshub_sdk.oauth_provider import OAuthProvider
    from pipeshub_sdk.oauth_sdk import OauthSDK
    from pipeshub_sdk.oauthapps import OauthApps
    from pipeshub_sdk.oauthconfiguration_2 import OauthConfiguration2
    from pipeshub_sdk.openid_connect import OpenIDConnect
    from pipeshub_sdk.organizationauthconfig import OrganizationAuthConfig
    from pipeshub_sdk.organizationauthconfigs import OrganizationAuthConfigs
    from pipeshub_sdk.organizations import Organizations
    from pipeshub_sdk.permissions_sdk import PermissionsSDK
    from pipeshub_sdk.platformsettings_sdk import PlatformSettingsSDK
    from pipeshub_sdk.publicurls import PublicUrls
    from pipeshub_sdk.queuemanagement import QueueManagement
    from pipeshub_sdk.records import Records
    from pipeshub_sdk.saml import Saml
    from pipeshub_sdk.semanticsearch import SemanticSearch
    from pipeshub_sdk.smtpconfiguration import SMTPConfiguration
    from pipeshub_sdk.smtpconfigurations import SMTPConfigurations
    from pipeshub_sdk.storageconfiguration import StorageConfiguration
    from pipeshub_sdk.teams import Teams
    from pipeshub_sdk.toolset_configuration import ToolsetConfiguration
    from pipeshub_sdk.toolset_instances import ToolsetInstances
    from pipeshub_sdk.toolset_oauth import ToolsetOAuth
    from pipeshub_sdk.toolset_registry import ToolsetRegistry
    from pipeshub_sdk.upload import Upload
    from pipeshub_sdk.uploads import Uploads
    from pipeshub_sdk.user_groups import UserGroups
    from pipeshub_sdk.useraccount import UserAccount
    from pipeshub_sdk.users import Users


class Pipeshub(BaseSDK):
    r"""PipesHub API: Unified API documentation for PipesHub services.

    PipesHub is an enterprise-grade platform providing:
    - User authentication and management
    - Document storage and version control
    - Knowledge base management
    - Enterprise search and conversational AI
    - Third-party integrations via connectors
    - System configuration management
    - Crawling job scheduling
    - Email services

    ## Authentication
    Most endpoints require JWT Bearer token authentication. Some internal endpoints use scoped tokens for service-to-service communication.

    ## Base URLs
    All endpoints use the `/api/v1` prefix unless otherwise noted.

    """

    user_account: "UserAccount"
    oauth: "OauthSDK"
    o_auth_provider: "OAuthProvider"
    r"""PipesHub OAuth 2.0 Authorization Server implementing RFC 6749, RFC 7636 (PKCE), and OpenID Connect.

    **Supported Grant Types:**
    - `authorization_code` - Standard OAuth flow with PKCE support
    - `client_credentials` - Machine-to-machine authentication
    - `refresh_token` - Token refresh for long-lived access

    **Security Features:**
    - PKCE (Proof Key for Code Exchange) for public clients
    - State parameter for CSRF protection
    - Configurable token lifetimes
    - Token revocation and introspection

    **OpenID Connect:**
    - ID tokens with standard claims
    - UserInfo endpoint for profile data
    - Discovery endpoint for automatic configuration

    """
    open_id_connect: "OpenIDConnect"
    r"""OpenID Connect 1.0 endpoints for identity federation and discovery.

    **Discovery:**
    - `/.well-known/openid-configuration` - Authorization server metadata
    - `/.well-known/oauth-authorization-server` - Authorization server metadata (RFC 8414)
    - `/.well-known/oauth-protected-resource/mcp` - Protected resource metadata (RFC 9728)
    - `/.well-known/jwks.json` - Public keys for token verification

    **UserInfo:**
    - `/oauth2/userinfo` - Get authenticated user's profile information

    **Supported Claims:**
    - `user_id` - User identifier
    - `email`, `email_verified` - Email information
    - `name`, `given_name`, `family_name` - Name information

    """
    oauth_apps: "OauthApps"
    organization_auth_configs: "OrganizationAuthConfigs"
    organization_auth_config: "OrganizationAuthConfig"
    saml: "Saml"
    users: "Users"
    r"""User management operations"""
    teams: "Teams"
    r"""Team management operations"""
    organizations: "Organizations"
    r"""Organization management operations"""
    user_groups: "UserGroups"
    r"""User group management operations"""
    document_management: "DocumentManagement"
    knowledge_bases: "KnowledgeBases"
    r"""Knowledge base management operations"""
    records: "Records"
    r"""Record management and operations"""
    folders: "Folders"
    r"""Folder organization and management"""
    upload: "Upload"
    r"""File upload operations"""
    uploads: "Uploads"
    connector: "ConnectorSDK"
    r"""Connector-related operations"""
    connectors: "Connectors"
    permissions: "PermissionsSDK"
    r"""Permission management for knowledge bases"""
    conversations: "Conversations"
    r"""AI-powered conversational chat management with citations and follow-up questions"""
    semantic_search: "SemanticSearch"
    agent_templates: "AgentTemplates"
    agents: "Agents"
    r"""Custom AI agents with specialized capabilities and tool integrations"""
    agent_conversations: "AgentConversations"
    connector_registry: "ConnectorRegistry"
    connector_instances: "ConnectorInstances"
    connector_configurations: "ConnectorConfigurations"
    connector_configuration: "ConnectorConfiguration"
    connector_controls: "ConnectorControls"
    connector_o_auth: "ConnectorOAuth"
    connector_filters: "ConnectorFilters"
    toolset_registry: "ToolsetRegistry"
    r"""Browse available toolsets and their configuration schemas for agent integrations"""
    toolset_instances: "ToolsetInstances"
    r"""Create, manage, and configure toolset instances for your organization"""
    toolset_configuration: "ToolsetConfiguration"
    r"""Configure authentication and settings for toolset instances"""
    toolset_o_auth: "ToolsetOAuth"
    r"""OAuth 2.0 authorization flow for toolsets requiring user consent"""
    o_auth_configuration: "OAuthConfiguration1"
    r"""Admin management of OAuth credentials for connector types"""
    oauth_configuration: "OauthConfiguration2"
    storage_configuration: "StorageConfiguration"
    smtp_configurations: "SMTPConfigurations"
    smtp_configuration: "SMTPConfiguration"
    auth_config: "AuthConfigSDK"
    authentication_configurations: "AuthenticationConfigurations"
    authentication_configuration: "AuthenticationConfiguration"
    ai_models_providers: "AiModelsProviders"
    public_urls: "PublicUrls"
    platform_settings: "PlatformSettingsSDK"
    metrics_collection: "MetricsCollection"
    configuration_manager: "ConfigurationManager"
    ai_models_configuration: "AiModelsConfiguration"
    crawling_jobs: "CrawlingJobs"
    queue_management: "QueueManagement"
    mcp: "Mcp"
    r"""Model Context Protocol (MCP) endpoints for AI tool integration.

    PipesHub exposes a Streamable HTTP MCP server that allows MCP-compatible clients
    (such as Claude Desktop, Cursor, or custom agents) to interact with PipesHub tools
    including search, conversations, knowledge base management, and connector operations.

    **Transport:** Streamable HTTP (JSON-RPC over HTTP)
    **Base Path:** `/mcp` (not under `/api/v1`)

    **Authentication:**
    All MCP requests require a valid Bearer token or OAuth 2.0 access token.

    **Stateless Mode:**
    The server operates in stateless mode — each request creates an independent MCP session.

    """
    _sub_sdk_map = {
        "user_account": ("pipeshub_sdk.useraccount", "UserAccount"),
        "oauth": ("pipeshub_sdk.oauth_sdk", "OauthSDK"),
        "o_auth_provider": ("pipeshub_sdk.oauth_provider", "OAuthProvider"),
        "open_id_connect": ("pipeshub_sdk.openid_connect", "OpenIDConnect"),
        "oauth_apps": ("pipeshub_sdk.oauthapps", "OauthApps"),
        "organization_auth_configs": (
            "pipeshub_sdk.organizationauthconfigs",
            "OrganizationAuthConfigs",
        ),
        "organization_auth_config": (
            "pipeshub_sdk.organizationauthconfig",
            "OrganizationAuthConfig",
        ),
        "saml": ("pipeshub_sdk.saml", "Saml"),
        "users": ("pipeshub_sdk.users", "Users"),
        "teams": ("pipeshub_sdk.teams", "Teams"),
        "organizations": ("pipeshub_sdk.organizations", "Organizations"),
        "user_groups": ("pipeshub_sdk.user_groups", "UserGroups"),
        "document_management": (
            "pipeshub_sdk.documentmanagement",
            "DocumentManagement",
        ),
        "knowledge_bases": ("pipeshub_sdk.knowledgebases", "KnowledgeBases"),
        "records": ("pipeshub_sdk.records", "Records"),
        "folders": ("pipeshub_sdk.folders", "Folders"),
        "upload": ("pipeshub_sdk.upload", "Upload"),
        "uploads": ("pipeshub_sdk.uploads", "Uploads"),
        "connector": ("pipeshub_sdk.connector_sdk", "ConnectorSDK"),
        "connectors": ("pipeshub_sdk.connectors", "Connectors"),
        "permissions": ("pipeshub_sdk.permissions_sdk", "PermissionsSDK"),
        "conversations": ("pipeshub_sdk.conversations", "Conversations"),
        "semantic_search": ("pipeshub_sdk.semanticsearch", "SemanticSearch"),
        "agent_templates": ("pipeshub_sdk.agenttemplates", "AgentTemplates"),
        "agents": ("pipeshub_sdk.agents", "Agents"),
        "agent_conversations": (
            "pipeshub_sdk.agentconversations",
            "AgentConversations",
        ),
        "connector_registry": ("pipeshub_sdk.connectorregistry", "ConnectorRegistry"),
        "connector_instances": (
            "pipeshub_sdk.connectorinstances",
            "ConnectorInstances",
        ),
        "connector_configurations": (
            "pipeshub_sdk.connectorconfigurations",
            "ConnectorConfigurations",
        ),
        "connector_configuration": (
            "pipeshub_sdk.connectorconfiguration",
            "ConnectorConfiguration",
        ),
        "connector_controls": ("pipeshub_sdk.connectorcontrols", "ConnectorControls"),
        "connector_o_auth": ("pipeshub_sdk.connectoroauth", "ConnectorOAuth"),
        "connector_filters": ("pipeshub_sdk.connectorfilters", "ConnectorFilters"),
        "toolset_registry": ("pipeshub_sdk.toolset_registry", "ToolsetRegistry"),
        "toolset_instances": ("pipeshub_sdk.toolset_instances", "ToolsetInstances"),
        "toolset_configuration": (
            "pipeshub_sdk.toolset_configuration",
            "ToolsetConfiguration",
        ),
        "toolset_o_auth": ("pipeshub_sdk.toolset_oauth", "ToolsetOAuth"),
        "o_auth_configuration": (
            "pipeshub_sdk.oauth_configuration_1",
            "OAuthConfiguration1",
        ),
        "oauth_configuration": (
            "pipeshub_sdk.oauthconfiguration_2",
            "OauthConfiguration2",
        ),
        "storage_configuration": (
            "pipeshub_sdk.storageconfiguration",
            "StorageConfiguration",
        ),
        "smtp_configurations": (
            "pipeshub_sdk.smtpconfigurations",
            "SMTPConfigurations",
        ),
        "smtp_configuration": ("pipeshub_sdk.smtpconfiguration", "SMTPConfiguration"),
        "auth_config": ("pipeshub_sdk.authconfig_sdk", "AuthConfigSDK"),
        "authentication_configurations": (
            "pipeshub_sdk.authenticationconfigurations",
            "AuthenticationConfigurations",
        ),
        "authentication_configuration": (
            "pipeshub_sdk.authenticationconfiguration",
            "AuthenticationConfiguration",
        ),
        "ai_models_providers": ("pipeshub_sdk.aimodelsproviders", "AiModelsProviders"),
        "public_urls": ("pipeshub_sdk.publicurls", "PublicUrls"),
        "platform_settings": (
            "pipeshub_sdk.platformsettings_sdk",
            "PlatformSettingsSDK",
        ),
        "metrics_collection": ("pipeshub_sdk.metricscollection", "MetricsCollection"),
        "configuration_manager": (
            "pipeshub_sdk.configuration_manager",
            "ConfigurationManager",
        ),
        "ai_models_configuration": (
            "pipeshub_sdk.aimodelsconfiguration",
            "AiModelsConfiguration",
        ),
        "crawling_jobs": ("pipeshub_sdk.crawlingjobs", "CrawlingJobs"),
        "queue_management": ("pipeshub_sdk.queuemanagement", "QueueManagement"),
        "mcp": ("pipeshub_sdk.mcp", "Mcp"),
    }

    def __init__(
        self,
        security: Optional[
            Union[models.Security, Callable[[], models.Security]]
        ] = None,
        instance_url: Optional[str] = None,
        server_idx: Optional[int] = None,
        url_params: Optional[Dict[str, str]] = None,
        server_url: Optional[str] = None,
        client: Optional[HttpClient] = None,
        async_client: Optional[AsyncHttpClient] = None,
        retry_config: OptionalNullable[RetryConfig] = UNSET,
        timeout_ms: Optional[int] = None,
        debug_logger: Optional[Logger] = None,
    ) -> None:
        r"""Instantiates the SDK configuring it with the provided parameters.

        :param security: The security details required for authentication
        :param instance_url: Allows setting the instance_url variable for url substitution
        :param server_idx: The index of the server to use for all methods
        :param server_url: The server URL to use for all methods
        :param url_params: Parameters to optionally template the server URL with
        :param client: The HTTP client to use for all synchronous methods
        :param async_client: The Async HTTP client to use for all asynchronous methods
        :param retry_config: The retry configuration to use for all supported methods
        :param timeout_ms: Optional request timeout applied to each operation in milliseconds
        """
        client_supplied = True
        if client is None:
            client = httpx.Client(follow_redirects=True)
            client_supplied = False

        assert issubclass(
            type(client), HttpClient
        ), "The provided client must implement the HttpClient protocol."

        async_client_supplied = True
        if async_client is None:
            async_client = httpx.AsyncClient(follow_redirects=True)
            async_client_supplied = False

        if debug_logger is None:
            debug_logger = get_default_logger()

        assert issubclass(
            type(async_client), AsyncHttpClient
        ), "The provided async_client must implement the AsyncHttpClient protocol."

        if server_url is not None:
            if url_params is not None:
                server_url = utils.template_url(server_url, url_params)
        server_defaults: List[Dict[str, str]] = [
            {
                "instance_url": instance_url or "https://app.pipeshub.com",
            },
            {
                "instance_url": instance_url or "https://app.pipeshub.com",
            },
        ]

        BaseSDK.__init__(
            self,
            SDKConfiguration(
                client=client,
                client_supplied=client_supplied,
                async_client=async_client,
                async_client_supplied=async_client_supplied,
                security=security,
                server_url=server_url,
                server_idx=server_idx,
                server_defaults=server_defaults,
                retry_config=retry_config,
                timeout_ms=timeout_ms,
                debug_logger=debug_logger,
            ),
            parent_ref=self,
        )

        hooks = SDKHooks()

        # pylint: disable=protected-access
        self.sdk_configuration.__dict__["_hooks"] = hooks

        self.sdk_configuration = hooks.sdk_init(self.sdk_configuration)

        weakref.finalize(
            self,
            close_clients,
            cast(ClientOwner, self.sdk_configuration),
            self.sdk_configuration.client,
            self.sdk_configuration.client_supplied,
            self.sdk_configuration.async_client,
            self.sdk_configuration.async_client_supplied,
        )

    def dynamic_import(self, modname, retries=3):
        for attempt in range(retries):
            try:
                return importlib.import_module(modname)
            except KeyError:
                # Clear any half-initialized module and retry
                sys.modules.pop(modname, None)
                if attempt == retries - 1:
                    break
        raise KeyError(f"Failed to import module '{modname}' after {retries} attempts")

    def __getattr__(self, name: str):
        if name in self._sub_sdk_map:
            module_path, class_name = self._sub_sdk_map[name]
            try:
                module = self.dynamic_import(module_path)
                klass = getattr(module, class_name)
                instance = klass(self.sdk_configuration, parent_ref=self)
                setattr(self, name, instance)
                return instance
            except ImportError as e:
                raise AttributeError(
                    f"Failed to import module {module_path} for attribute {name}: {e}"
                ) from e
            except AttributeError as e:
                raise AttributeError(
                    f"Failed to find class {class_name} in module {module_path} for attribute {name}: {e}"
                ) from e

        raise AttributeError(
            f"'{type(self).__name__}' object has no attribute '{name}'"
        )

    def __dir__(self):
        default_attrs = list(super().__dir__())
        lazy_attrs = list(self._sub_sdk_map.keys())
        return sorted(list(set(default_attrs + lazy_attrs)))

    def __enter__(self):
        return self

    async def __aenter__(self):
        return self

    def __exit__(self, exc_type, exc_val, exc_tb):
        if (
            self.sdk_configuration.client is not None
            and not self.sdk_configuration.client_supplied
        ):
            self.sdk_configuration.client.close()
        self.sdk_configuration.client = None

    async def __aexit__(self, exc_type, exc_val, exc_tb):
        if (
            self.sdk_configuration.async_client is not None
            and not self.sdk_configuration.async_client_supplied
        ):
            await self.sdk_configuration.async_client.aclose()
        self.sdk_configuration.async_client = None
