"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from .basesdk import BaseSDK
from datetime import datetime
from pipeshub_sdk import errors, models, utils
from pipeshub_sdk._hooks import HookContext
from pipeshub_sdk.types import OptionalNullable, UNSET
from pipeshub_sdk.utils import get_security_from_env
from pipeshub_sdk.utils.unmarshal_json_response import unmarshal_json_response
from typing import Any, List, Mapping, Optional, Union


class SemanticSearch(BaseSDK):
    def search(
        self,
        *,
        query: str,
        filters: Optional[Union[models.Filters, models.FiltersTypedDict]] = None,
        limit: Optional[int] = 10,
        model_key: Optional[str] = None,
        model_name: Optional[str] = None,
        model_friendly_name: Optional[str] = None,
        chat_mode: Optional[str] = None,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.SemanticSearchExecuteResponse:
        r"""Perform semantic search

        Run a semantic search across your organization's knowledge base.
        Matching is meaning-based, so relevant results surface even when
        the wording differs from the query.

        Use optional `filters` to narrow the scope:

        - `filters.apps` — restrict to specific connector apps (for
        example Google Drive or Confluence).
        - `filters.kb` — restrict to specific knowledge bases.

        The response returns a `searchId` for the persisted search along
        with ranked matches, each carrying a relevance score and the
        source document's metadata. Past searches can be retrieved via
        `GET /search`.


        :param query: Natural language search query. The system understands
            semantic meaning, not just keywords.

        :param filters: App connector instance ids and knowledge-base / record-group ids that narrow retrieval
            for a turn. For **org assistant** chat streams, send explicit `apps` / `kb` lists.
            For **agent** chat streams, send explicit id lists, or **omit** `filters` (and `tools`)
            to let the service use the agent’s stored knowledge and tool configuration. Sending
            `{ \"apps\": [], \"kb\": [] }` on an agent stream means **no** knowledge sources for that
            turn (it is not “full org default”).

        :param limit: Maximum number of results to return
        :param model_key: AI model to use for embeddings
        :param model_name: Display name of the model
        :param model_friendly_name: Friendly display name of the model
        :param chat_mode: Processing mode configuration
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.SemanticSearchRequest(
            query=query,
            filters=utils.get_pydantic_model(filters, Optional[models.Filters]),
            limit=limit,
            model_key=model_key,
            model_name=model_name,
            model_friendly_name=model_friendly_name,
            chat_mode=chat_mode,
        )

        req = self._build_request(
            method="POST",
            path="/search",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=True,
            request_has_path_params=False,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            get_serialized_body=lambda: utils.serialize_request_body(
                request, False, False, "json", models.SemanticSearchRequest
            ),
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = self.do_request(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="search",
                oauth2_scopes=["semantic:write"],
                security_source=get_security_from_env(
                    self.sdk_configuration.security, models.Security
                ),
            ),
            request=req,
            error_status_codes=[
                "400",
                "401",
                "403",
                "404",
                "4XX",
                "500",
                "502",
                "503",
                "504",
                "5XX",
            ],
            retry_config=retry_config,
        )

        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(
                models.SemanticSearchExecuteResponse, http_res
            )
        if utils.match_response(http_res, ["400", "401", "403", "404", "4XX"], "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.PipeshubDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, ["500", "502", "503", "504", "5XX"], "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.PipeshubDefaultError(
                "API error occurred", http_res, http_res_text
            )

        raise errors.PipeshubDefaultError("Unexpected response received", http_res)

    async def search_async(
        self,
        *,
        query: str,
        filters: Optional[Union[models.Filters, models.FiltersTypedDict]] = None,
        limit: Optional[int] = 10,
        model_key: Optional[str] = None,
        model_name: Optional[str] = None,
        model_friendly_name: Optional[str] = None,
        chat_mode: Optional[str] = None,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.SemanticSearchExecuteResponse:
        r"""Perform semantic search

        Run a semantic search across your organization's knowledge base.
        Matching is meaning-based, so relevant results surface even when
        the wording differs from the query.

        Use optional `filters` to narrow the scope:

        - `filters.apps` — restrict to specific connector apps (for
        example Google Drive or Confluence).
        - `filters.kb` — restrict to specific knowledge bases.

        The response returns a `searchId` for the persisted search along
        with ranked matches, each carrying a relevance score and the
        source document's metadata. Past searches can be retrieved via
        `GET /search`.


        :param query: Natural language search query. The system understands
            semantic meaning, not just keywords.

        :param filters: App connector instance ids and knowledge-base / record-group ids that narrow retrieval
            for a turn. For **org assistant** chat streams, send explicit `apps` / `kb` lists.
            For **agent** chat streams, send explicit id lists, or **omit** `filters` (and `tools`)
            to let the service use the agent’s stored knowledge and tool configuration. Sending
            `{ \"apps\": [], \"kb\": [] }` on an agent stream means **no** knowledge sources for that
            turn (it is not “full org default”).

        :param limit: Maximum number of results to return
        :param model_key: AI model to use for embeddings
        :param model_name: Display name of the model
        :param model_friendly_name: Friendly display name of the model
        :param chat_mode: Processing mode configuration
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.SemanticSearchRequest(
            query=query,
            filters=utils.get_pydantic_model(filters, Optional[models.Filters]),
            limit=limit,
            model_key=model_key,
            model_name=model_name,
            model_friendly_name=model_friendly_name,
            chat_mode=chat_mode,
        )

        req = self._build_request_async(
            method="POST",
            path="/search",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=True,
            request_has_path_params=False,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            get_serialized_body=lambda: utils.serialize_request_body(
                request, False, False, "json", models.SemanticSearchRequest
            ),
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = await self.do_request_async(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="search",
                oauth2_scopes=["semantic:write"],
                security_source=get_security_from_env(
                    self.sdk_configuration.security, models.Security
                ),
            ),
            request=req,
            error_status_codes=[
                "400",
                "401",
                "403",
                "404",
                "4XX",
                "500",
                "502",
                "503",
                "504",
                "5XX",
            ],
            retry_config=retry_config,
        )

        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(
                models.SemanticSearchExecuteResponse, http_res
            )
        if utils.match_response(http_res, ["400", "401", "403", "404", "4XX"], "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.PipeshubDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, ["500", "502", "503", "504", "5XX"], "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.PipeshubDefaultError(
                "API error occurred", http_res, http_res_text
            )

        raise errors.PipeshubDefaultError("Unexpected response received", http_res)

    def search_history(
        self,
        *,
        page: Optional[int] = 1,
        limit: Optional[int] = 20,
        sort_by: Optional[models.SearchHistorySortBy] = "lastActivityAt",
        sort_order: Optional[models.SearchHistorySortOrder] = "desc",
        search: Optional[str] = None,
        shared: Optional[models.SearchHistoryShared] = None,
        start_date: Optional[datetime] = None,
        end_date: Optional[datetime] = None,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.SemanticSearchHistoryResponse:
        r"""Get search history

        Retrieve the authenticated user's persisted search history.

        Returns searches the user owns along with searches shared with them,
        scoped to the caller's organization. Archived and deleted entries are
        excluded. Citation references on this endpoint are returned as raw
        identifier strings; use `GET /search/{searchId}` to fetch a single
        search with its citations fully expanded.

        Pagination defaults to `page=1, limit=20` (maximum `limit` is 100).
        Results are sorted by most recent activity by default.


        :param page: Page number to return. Must be within `[1, 1000]`.
        :param limit: Number of items per page. Values are clamped to the range `[1, 100]`.
        :param sort_by: Field used to sort results. Any value other than `createdAt`,
            `lastActivityAt`, or `title` is treated as `lastActivityAt`.

        :param sort_order: Sort direction applied to `sortBy`.
        :param search: Case-insensitive substring to match against a search's title and
            message content. Regex metacharacters are escaped automatically.
            Values longer than 1000 characters are rejected with `400`.

        :param shared: Filter results by their shared status. Accepted values are
            `'true'` / `'1'` (return only shared searches) and
            `'false'` / `'0'` (exclude shared searches). Matching is
            case-insensitive and surrounding whitespace is trimmed.

        :param start_date: ISO 8601 timestamp used as the lower bound for a search's creation date.
        :param end_date: ISO 8601 timestamp used as the upper bound for a search's creation date.
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.SearchHistoryRequest(
            page=page,
            limit=limit,
            sort_by=sort_by,
            sort_order=sort_order,
            search=search,
            shared=shared,
            start_date=start_date,
            end_date=end_date,
        )

        req = self._build_request(
            method="GET",
            path="/search",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=False,
            request_has_path_params=False,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = self.do_request(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="searchHistory",
                oauth2_scopes=["semantic:read"],
                security_source=get_security_from_env(
                    self.sdk_configuration.security, models.Security
                ),
            ),
            request=req,
            error_status_codes=["400", "401", "403", "4XX", "500", "5XX"],
            retry_config=retry_config,
        )

        response_data: Any = None
        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(
                models.SemanticSearchHistoryResponse, http_res
            )
        if utils.match_response(http_res, "400", "application/json"):
            response_data = unmarshal_json_response(
                errors.SearchHistoryBadRequestErrorData, http_res
            )
            raise errors.SearchHistoryBadRequestError(response_data, http_res)
        if utils.match_response(http_res, "401", "application/json"):
            response_data = unmarshal_json_response(
                errors.SearchHistoryUnauthorizedErrorData, http_res
            )
            raise errors.SearchHistoryUnauthorizedError(response_data, http_res)
        if utils.match_response(http_res, "403", "application/json"):
            response_data = unmarshal_json_response(
                errors.SearchHistoryForbiddenErrorData, http_res
            )
            raise errors.SearchHistoryForbiddenError(response_data, http_res)
        if utils.match_response(http_res, "500", "application/json"):
            response_data = unmarshal_json_response(
                errors.SearchHistoryInternalServerErrorData, http_res
            )
            raise errors.SearchHistoryInternalServerError(response_data, http_res)
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.PipeshubDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.PipeshubDefaultError(
                "API error occurred", http_res, http_res_text
            )

        raise errors.PipeshubDefaultError("Unexpected response received", http_res)

    async def search_history_async(
        self,
        *,
        page: Optional[int] = 1,
        limit: Optional[int] = 20,
        sort_by: Optional[models.SearchHistorySortBy] = "lastActivityAt",
        sort_order: Optional[models.SearchHistorySortOrder] = "desc",
        search: Optional[str] = None,
        shared: Optional[models.SearchHistoryShared] = None,
        start_date: Optional[datetime] = None,
        end_date: Optional[datetime] = None,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.SemanticSearchHistoryResponse:
        r"""Get search history

        Retrieve the authenticated user's persisted search history.

        Returns searches the user owns along with searches shared with them,
        scoped to the caller's organization. Archived and deleted entries are
        excluded. Citation references on this endpoint are returned as raw
        identifier strings; use `GET /search/{searchId}` to fetch a single
        search with its citations fully expanded.

        Pagination defaults to `page=1, limit=20` (maximum `limit` is 100).
        Results are sorted by most recent activity by default.


        :param page: Page number to return. Must be within `[1, 1000]`.
        :param limit: Number of items per page. Values are clamped to the range `[1, 100]`.
        :param sort_by: Field used to sort results. Any value other than `createdAt`,
            `lastActivityAt`, or `title` is treated as `lastActivityAt`.

        :param sort_order: Sort direction applied to `sortBy`.
        :param search: Case-insensitive substring to match against a search's title and
            message content. Regex metacharacters are escaped automatically.
            Values longer than 1000 characters are rejected with `400`.

        :param shared: Filter results by their shared status. Accepted values are
            `'true'` / `'1'` (return only shared searches) and
            `'false'` / `'0'` (exclude shared searches). Matching is
            case-insensitive and surrounding whitespace is trimmed.

        :param start_date: ISO 8601 timestamp used as the lower bound for a search's creation date.
        :param end_date: ISO 8601 timestamp used as the upper bound for a search's creation date.
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.SearchHistoryRequest(
            page=page,
            limit=limit,
            sort_by=sort_by,
            sort_order=sort_order,
            search=search,
            shared=shared,
            start_date=start_date,
            end_date=end_date,
        )

        req = self._build_request_async(
            method="GET",
            path="/search",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=False,
            request_has_path_params=False,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = await self.do_request_async(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="searchHistory",
                oauth2_scopes=["semantic:read"],
                security_source=get_security_from_env(
                    self.sdk_configuration.security, models.Security
                ),
            ),
            request=req,
            error_status_codes=["400", "401", "403", "4XX", "500", "5XX"],
            retry_config=retry_config,
        )

        response_data: Any = None
        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(
                models.SemanticSearchHistoryResponse, http_res
            )
        if utils.match_response(http_res, "400", "application/json"):
            response_data = unmarshal_json_response(
                errors.SearchHistoryBadRequestErrorData, http_res
            )
            raise errors.SearchHistoryBadRequestError(response_data, http_res)
        if utils.match_response(http_res, "401", "application/json"):
            response_data = unmarshal_json_response(
                errors.SearchHistoryUnauthorizedErrorData, http_res
            )
            raise errors.SearchHistoryUnauthorizedError(response_data, http_res)
        if utils.match_response(http_res, "403", "application/json"):
            response_data = unmarshal_json_response(
                errors.SearchHistoryForbiddenErrorData, http_res
            )
            raise errors.SearchHistoryForbiddenError(response_data, http_res)
        if utils.match_response(http_res, "500", "application/json"):
            response_data = unmarshal_json_response(
                errors.SearchHistoryInternalServerErrorData, http_res
            )
            raise errors.SearchHistoryInternalServerError(response_data, http_res)
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.PipeshubDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.PipeshubDefaultError(
                "API error occurred", http_res, http_res_text
            )

        raise errors.PipeshubDefaultError("Unexpected response received", http_res)

    def delete_search_history(
        self,
        *,
        search: Optional[str] = None,
        shared: Optional[models.DeleteSearchHistoryShared] = None,
        start_date: Optional[datetime] = None,
        end_date: Optional[datetime] = None,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.DeleteSearchHistoryResponse:
        r"""Clear all search history

        Permanently delete every persisted search row owned by, or shared
        with, the authenticated user, along with the citation rows those
        searches reference. The action cannot be undone.

        Scoped to the caller's org and limited to rows where
        `isDeleted: false` and `isArchived: false`. If nothing matches
        (including the case where every row is already archived), the
        endpoint returns `404` rather than a successful no-op.


        :param search: Restrict the deletion to rows whose `title` or `messages.content`
            matches this case-insensitive substring. Special regex characters
            are escaped before the lookup; values over 1000 chars are
            rejected with `400`.

        :param shared: Restrict the deletion to rows with this `isShared` value
            (`'true'` / `'false'`).

        :param start_date: ISO 8601 lower bound for `createdAt`. Combined with `endDate`
            to scope which rows are deleted.

        :param end_date: ISO 8601 upper bound for `createdAt`.
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.DeleteSearchHistoryRequest(
            search=search,
            shared=shared,
            start_date=start_date,
            end_date=end_date,
        )

        req = self._build_request(
            method="DELETE",
            path="/search",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=False,
            request_has_path_params=False,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = self.do_request(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="deleteSearchHistory",
                oauth2_scopes=["semantic:delete"],
                security_source=get_security_from_env(
                    self.sdk_configuration.security, models.Security
                ),
            ),
            request=req,
            error_status_codes=["400", "401", "403", "404", "4XX", "500", "5XX"],
            retry_config=retry_config,
        )

        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(models.DeleteSearchHistoryResponse, http_res)
        if utils.match_response(http_res, ["400", "401", "403", "404", "4XX"], "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.PipeshubDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, ["500", "5XX"], "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.PipeshubDefaultError(
                "API error occurred", http_res, http_res_text
            )

        raise errors.PipeshubDefaultError("Unexpected response received", http_res)

    async def delete_search_history_async(
        self,
        *,
        search: Optional[str] = None,
        shared: Optional[models.DeleteSearchHistoryShared] = None,
        start_date: Optional[datetime] = None,
        end_date: Optional[datetime] = None,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.DeleteSearchHistoryResponse:
        r"""Clear all search history

        Permanently delete every persisted search row owned by, or shared
        with, the authenticated user, along with the citation rows those
        searches reference. The action cannot be undone.

        Scoped to the caller's org and limited to rows where
        `isDeleted: false` and `isArchived: false`. If nothing matches
        (including the case where every row is already archived), the
        endpoint returns `404` rather than a successful no-op.


        :param search: Restrict the deletion to rows whose `title` or `messages.content`
            matches this case-insensitive substring. Special regex characters
            are escaped before the lookup; values over 1000 chars are
            rejected with `400`.

        :param shared: Restrict the deletion to rows with this `isShared` value
            (`'true'` / `'false'`).

        :param start_date: ISO 8601 lower bound for `createdAt`. Combined with `endDate`
            to scope which rows are deleted.

        :param end_date: ISO 8601 upper bound for `createdAt`.
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.DeleteSearchHistoryRequest(
            search=search,
            shared=shared,
            start_date=start_date,
            end_date=end_date,
        )

        req = self._build_request_async(
            method="DELETE",
            path="/search",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=False,
            request_has_path_params=False,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = await self.do_request_async(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="deleteSearchHistory",
                oauth2_scopes=["semantic:delete"],
                security_source=get_security_from_env(
                    self.sdk_configuration.security, models.Security
                ),
            ),
            request=req,
            error_status_codes=["400", "401", "403", "404", "4XX", "500", "5XX"],
            retry_config=retry_config,
        )

        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(models.DeleteSearchHistoryResponse, http_res)
        if utils.match_response(http_res, ["400", "401", "403", "404", "4XX"], "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.PipeshubDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, ["500", "5XX"], "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.PipeshubDefaultError(
                "API error occurred", http_res, http_res_text
            )

        raise errors.PipeshubDefaultError("Unexpected response received", http_res)

    def get_search_by_id(
        self,
        *,
        search_id: str,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> List[models.PersistedSemanticSearch]:
        r"""Get search by ID

        Retrieve a previously persisted search by its id, scoped to the
        caller's org.

        The response body is always an **array** containing zero or one
        persisted search document. An unknown id returns an empty array
        with a `200` status — callers should check array length rather
        than relying on a `404`.


        :param search_id: Unique search identifier
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.GetSearchByIDRequest(
            search_id=search_id,
        )

        req = self._build_request(
            method="GET",
            path="/search/{searchId}",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=False,
            request_has_path_params=True,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = self.do_request(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="getSearchById",
                oauth2_scopes=["semantic:read"],
                security_source=get_security_from_env(
                    self.sdk_configuration.security, models.Security
                ),
            ),
            request=req,
            error_status_codes=["400", "401", "403", "404", "4XX", "500", "5XX"],
            retry_config=retry_config,
        )

        response_data: Any = None
        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(
                List[models.PersistedSemanticSearch], http_res
            )
        if utils.match_response(http_res, "400", "application/json"):
            response_data = unmarshal_json_response(
                errors.GetSearchByIDBadRequestErrorData, http_res
            )
            raise errors.GetSearchByIDBadRequestError(response_data, http_res)
        if utils.match_response(http_res, "401", "application/json"):
            response_data = unmarshal_json_response(
                errors.GetSearchByIDUnauthorizedErrorData, http_res
            )
            raise errors.GetSearchByIDUnauthorizedError(response_data, http_res)
        if utils.match_response(http_res, "403", "application/json"):
            response_data = unmarshal_json_response(
                errors.GetSearchByIDForbiddenErrorData, http_res
            )
            raise errors.GetSearchByIDForbiddenError(response_data, http_res)
        if utils.match_response(http_res, "404", "application/json"):
            response_data = unmarshal_json_response(
                errors.GetSearchByIDNotFoundErrorData, http_res
            )
            raise errors.GetSearchByIDNotFoundError(response_data, http_res)
        if utils.match_response(http_res, "500", "application/json"):
            response_data = unmarshal_json_response(
                errors.GetSearchByIDInternalServerErrorData, http_res
            )
            raise errors.GetSearchByIDInternalServerError(response_data, http_res)
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.PipeshubDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.PipeshubDefaultError(
                "API error occurred", http_res, http_res_text
            )

        raise errors.PipeshubDefaultError("Unexpected response received", http_res)

    async def get_search_by_id_async(
        self,
        *,
        search_id: str,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> List[models.PersistedSemanticSearch]:
        r"""Get search by ID

        Retrieve a previously persisted search by its id, scoped to the
        caller's org.

        The response body is always an **array** containing zero or one
        persisted search document. An unknown id returns an empty array
        with a `200` status — callers should check array length rather
        than relying on a `404`.


        :param search_id: Unique search identifier
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.GetSearchByIDRequest(
            search_id=search_id,
        )

        req = self._build_request_async(
            method="GET",
            path="/search/{searchId}",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=False,
            request_has_path_params=True,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = await self.do_request_async(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="getSearchById",
                oauth2_scopes=["semantic:read"],
                security_source=get_security_from_env(
                    self.sdk_configuration.security, models.Security
                ),
            ),
            request=req,
            error_status_codes=["400", "401", "403", "404", "4XX", "500", "5XX"],
            retry_config=retry_config,
        )

        response_data: Any = None
        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(
                List[models.PersistedSemanticSearch], http_res
            )
        if utils.match_response(http_res, "400", "application/json"):
            response_data = unmarshal_json_response(
                errors.GetSearchByIDBadRequestErrorData, http_res
            )
            raise errors.GetSearchByIDBadRequestError(response_data, http_res)
        if utils.match_response(http_res, "401", "application/json"):
            response_data = unmarshal_json_response(
                errors.GetSearchByIDUnauthorizedErrorData, http_res
            )
            raise errors.GetSearchByIDUnauthorizedError(response_data, http_res)
        if utils.match_response(http_res, "403", "application/json"):
            response_data = unmarshal_json_response(
                errors.GetSearchByIDForbiddenErrorData, http_res
            )
            raise errors.GetSearchByIDForbiddenError(response_data, http_res)
        if utils.match_response(http_res, "404", "application/json"):
            response_data = unmarshal_json_response(
                errors.GetSearchByIDNotFoundErrorData, http_res
            )
            raise errors.GetSearchByIDNotFoundError(response_data, http_res)
        if utils.match_response(http_res, "500", "application/json"):
            response_data = unmarshal_json_response(
                errors.GetSearchByIDInternalServerErrorData, http_res
            )
            raise errors.GetSearchByIDInternalServerError(response_data, http_res)
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.PipeshubDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.PipeshubDefaultError(
                "API error occurred", http_res, http_res_text
            )

        raise errors.PipeshubDefaultError("Unexpected response received", http_res)

    def delete_search_by_id(
        self,
        *,
        search_id: str,
        search: Optional[str] = None,
        shared: Optional[models.DeleteSearchByIDShared] = None,
        start_date: Optional[datetime] = None,
        end_date: Optional[datetime] = None,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.DeleteSearchByIDResponse:
        r"""Delete search by ID

        Permanently delete a single persisted search row, plus every
        citation row referenced by its `citationIds`. The caller must
        either own the row or have it shared with them.

        Scoped to the caller's org and limited to rows where
        `isDeleted: false` and `isArchived: false`; archived or
        already-deleted rows surface as `404`.


        :param search_id: ObjectId of the persisted search row to delete.
        :param search: Additional substring filter against `title` / `messages.content`.
            The row is only deleted if the `searchId` row also matches this
            filter; otherwise `404`. Special regex characters are escaped;
            values over 1000 chars or tripping the XSS guard yield `400`.

        :param shared: Additional `isShared` filter (`'true'` / `'false'`). The row is
            only deleted if it also matches this value.

        :param start_date: ISO 8601 lower bound for `createdAt`. The row is only deleted
            if its `createdAt` is on or after this value.

        :param end_date: ISO 8601 upper bound for `createdAt`. The row is only deleted
            if its `createdAt` is on or before this value.

        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.DeleteSearchByIDRequest(
            search_id=search_id,
            search=search,
            shared=shared,
            start_date=start_date,
            end_date=end_date,
        )

        req = self._build_request(
            method="DELETE",
            path="/search/{searchId}",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=False,
            request_has_path_params=True,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = self.do_request(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="deleteSearchById",
                oauth2_scopes=["semantic:delete"],
                security_source=get_security_from_env(
                    self.sdk_configuration.security, models.Security
                ),
            ),
            request=req,
            error_status_codes=["400", "401", "403", "404", "4XX", "500", "5XX"],
            retry_config=retry_config,
        )

        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(models.DeleteSearchByIDResponse, http_res)
        if utils.match_response(http_res, ["400", "401", "403", "404", "4XX"], "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.PipeshubDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, ["500", "5XX"], "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.PipeshubDefaultError(
                "API error occurred", http_res, http_res_text
            )

        raise errors.PipeshubDefaultError("Unexpected response received", http_res)

    async def delete_search_by_id_async(
        self,
        *,
        search_id: str,
        search: Optional[str] = None,
        shared: Optional[models.DeleteSearchByIDShared] = None,
        start_date: Optional[datetime] = None,
        end_date: Optional[datetime] = None,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.DeleteSearchByIDResponse:
        r"""Delete search by ID

        Permanently delete a single persisted search row, plus every
        citation row referenced by its `citationIds`. The caller must
        either own the row or have it shared with them.

        Scoped to the caller's org and limited to rows where
        `isDeleted: false` and `isArchived: false`; archived or
        already-deleted rows surface as `404`.


        :param search_id: ObjectId of the persisted search row to delete.
        :param search: Additional substring filter against `title` / `messages.content`.
            The row is only deleted if the `searchId` row also matches this
            filter; otherwise `404`. Special regex characters are escaped;
            values over 1000 chars or tripping the XSS guard yield `400`.

        :param shared: Additional `isShared` filter (`'true'` / `'false'`). The row is
            only deleted if it also matches this value.

        :param start_date: ISO 8601 lower bound for `createdAt`. The row is only deleted
            if its `createdAt` is on or after this value.

        :param end_date: ISO 8601 upper bound for `createdAt`. The row is only deleted
            if its `createdAt` is on or before this value.

        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.DeleteSearchByIDRequest(
            search_id=search_id,
            search=search,
            shared=shared,
            start_date=start_date,
            end_date=end_date,
        )

        req = self._build_request_async(
            method="DELETE",
            path="/search/{searchId}",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=False,
            request_has_path_params=True,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = await self.do_request_async(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="deleteSearchById",
                oauth2_scopes=["semantic:delete"],
                security_source=get_security_from_env(
                    self.sdk_configuration.security, models.Security
                ),
            ),
            request=req,
            error_status_codes=["400", "401", "403", "404", "4XX", "500", "5XX"],
            retry_config=retry_config,
        )

        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(models.DeleteSearchByIDResponse, http_res)
        if utils.match_response(http_res, ["400", "401", "403", "404", "4XX"], "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.PipeshubDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, ["500", "5XX"], "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.PipeshubDefaultError(
                "API error occurred", http_res, http_res_text
            )

        raise errors.PipeshubDefaultError("Unexpected response received", http_res)

    def archive_search(
        self,
        *,
        search_id: str,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.ArchiveSearchResponse:
        r"""Archive a search

        Archive a specific search result. Archived searches are hidden
        from the default search history view but remain retrievable via
        the archive-aware listing endpoints.


        :param search_id: Unique search identifier
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.ArchiveSearchRequest(
            search_id=search_id,
        )

        req = self._build_request(
            method="PATCH",
            path="/search/{searchId}/archive",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=False,
            request_has_path_params=True,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = self.do_request(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="archiveSearch",
                oauth2_scopes=["semantic:write"],
                security_source=get_security_from_env(
                    self.sdk_configuration.security, models.Security
                ),
            ),
            request=req,
            error_status_codes=["400", "401", "403", "404", "4XX", "500", "5XX"],
            retry_config=retry_config,
        )

        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(models.ArchiveSearchResponse, http_res)
        if utils.match_response(http_res, ["400", "401", "403", "404", "4XX"], "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.PipeshubDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, ["500", "5XX"], "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.PipeshubDefaultError(
                "API error occurred", http_res, http_res_text
            )

        raise errors.PipeshubDefaultError("Unexpected response received", http_res)

    async def archive_search_async(
        self,
        *,
        search_id: str,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.ArchiveSearchResponse:
        r"""Archive a search

        Archive a specific search result. Archived searches are hidden
        from the default search history view but remain retrievable via
        the archive-aware listing endpoints.


        :param search_id: Unique search identifier
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.ArchiveSearchRequest(
            search_id=search_id,
        )

        req = self._build_request_async(
            method="PATCH",
            path="/search/{searchId}/archive",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=False,
            request_has_path_params=True,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = await self.do_request_async(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="archiveSearch",
                oauth2_scopes=["semantic:write"],
                security_source=get_security_from_env(
                    self.sdk_configuration.security, models.Security
                ),
            ),
            request=req,
            error_status_codes=["400", "401", "403", "404", "4XX", "500", "5XX"],
            retry_config=retry_config,
        )

        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(models.ArchiveSearchResponse, http_res)
        if utils.match_response(http_res, ["400", "401", "403", "404", "4XX"], "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.PipeshubDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, ["500", "5XX"], "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.PipeshubDefaultError(
                "API error occurred", http_res, http_res_text
            )

        raise errors.PipeshubDefaultError("Unexpected response received", http_res)

    def unarchive_search(
        self,
        *,
        search_id: str,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.UnarchiveSearchResponse:
        r"""Unarchive a search

        Restore a previously archived search result back to the active search history.


        :param search_id: Unique search identifier
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.UnarchiveSearchRequest(
            search_id=search_id,
        )

        req = self._build_request(
            method="PATCH",
            path="/search/{searchId}/unarchive",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=False,
            request_has_path_params=True,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = self.do_request(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="unarchiveSearch",
                oauth2_scopes=["semantic:write"],
                security_source=get_security_from_env(
                    self.sdk_configuration.security, models.Security
                ),
            ),
            request=req,
            error_status_codes=["400", "401", "403", "404", "4XX", "500", "5XX"],
            retry_config=retry_config,
        )

        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(models.UnarchiveSearchResponse, http_res)
        if utils.match_response(http_res, ["400", "401", "403", "404", "4XX"], "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.PipeshubDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, ["500", "5XX"], "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.PipeshubDefaultError(
                "API error occurred", http_res, http_res_text
            )

        raise errors.PipeshubDefaultError("Unexpected response received", http_res)

    async def unarchive_search_async(
        self,
        *,
        search_id: str,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.UnarchiveSearchResponse:
        r"""Unarchive a search

        Restore a previously archived search result back to the active search history.


        :param search_id: Unique search identifier
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.UnarchiveSearchRequest(
            search_id=search_id,
        )

        req = self._build_request_async(
            method="PATCH",
            path="/search/{searchId}/unarchive",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=False,
            request_has_path_params=True,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            security=self.sdk_configuration.security,
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = await self.do_request_async(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="unarchiveSearch",
                oauth2_scopes=["semantic:write"],
                security_source=get_security_from_env(
                    self.sdk_configuration.security, models.Security
                ),
            ),
            request=req,
            error_status_codes=["400", "401", "403", "404", "4XX", "500", "5XX"],
            retry_config=retry_config,
        )

        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(models.UnarchiveSearchResponse, http_res)
        if utils.match_response(http_res, ["400", "401", "403", "404", "4XX"], "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.PipeshubDefaultError(
                "API error occurred", http_res, http_res_text
            )
        if utils.match_response(http_res, ["500", "5XX"], "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.PipeshubDefaultError(
                "API error occurred", http_res, http_res_text
            )

        raise errors.PipeshubDefaultError("Unexpected response received", http_res)
