"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from dataclasses import dataclass, field
import httpx
from pipeshub_sdk.errors import PipeshubError
from pipeshub_sdk.models import getsearchbyidop as models_getsearchbyidop
from pipeshub_sdk.types import BaseModel
from typing import Optional


class GetSearchByIDInternalServerErrorData(BaseModel):
    error: models_getsearchbyidop.GetSearchByIDInternalServerErrorError


@dataclass(unsafe_hash=True)
class GetSearchByIDInternalServerError(PipeshubError):
    r"""Server error. Possible causes:

    - Explicit `InternalServerError`
    or any other 500 `BaseError` thrown by the handler.
    - Non-`BaseError` exception caught by the
    global error middleware.
    - Response serializer fallback.

    """

    data: GetSearchByIDInternalServerErrorData = field(hash=False)

    def __init__(
        self,
        data: GetSearchByIDInternalServerErrorData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        fallback = body or raw_response.text
        message = str(data.error.message) or fallback
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)


class GetSearchByIDNotFoundErrorData(BaseModel):
    error: models_getsearchbyidop.GetSearchByIDNotFoundError


@dataclass(unsafe_hash=True)
class GetSearchByIDNotFoundError(PipeshubError):
    r"""Reserved for parity with sibling routes; this endpoint
    currently returns `200` with an empty array for an unknown
    id rather than emitting `404`.

    """

    data: GetSearchByIDNotFoundErrorData = field(hash=False)

    def __init__(
        self,
        data: GetSearchByIDNotFoundErrorData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        fallback = body or raw_response.text
        message = str(data.error.message) or fallback
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)


class GetSearchByIDForbiddenErrorData(BaseModel):
    error: models_getsearchbyidop.GetSearchByIDErrorHTTPForbidden


@dataclass(unsafe_hash=True)
class GetSearchByIDForbiddenError(PipeshubError):
    r"""Bearer token lacks the `semantic:read` scope."""

    data: GetSearchByIDForbiddenErrorData = field(hash=False)

    def __init__(
        self,
        data: GetSearchByIDForbiddenErrorData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        fallback = body or raw_response.text
        message = str(data.error.message) or fallback
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)


class GetSearchByIDUnauthorizedErrorData(BaseModel):
    error: models_getsearchbyidop.GetSearchByIDErrorHTTPUnauthorized


@dataclass(unsafe_hash=True)
class GetSearchByIDUnauthorizedError(PipeshubError):
    r"""Missing or invalid bearer token."""

    data: GetSearchByIDUnauthorizedErrorData = field(hash=False)

    def __init__(
        self,
        data: GetSearchByIDUnauthorizedErrorData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        fallback = body or raw_response.text
        message = str(data.error.message) or fallback
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)


class GetSearchByIDBadRequestErrorData(BaseModel):
    error: models_getsearchbyidop.GetSearchByIDErrorValidationError


@dataclass(unsafe_hash=True)
class GetSearchByIDBadRequestError(PipeshubError):
    r"""Invalid request — `searchId`
    failed Zod validation (not a valid ObjectId).

    """

    data: GetSearchByIDBadRequestErrorData = field(hash=False)

    def __init__(
        self,
        data: GetSearchByIDBadRequestErrorData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        fallback = body or raw_response.text
        message = str(data.error.message) or fallback
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)
