"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

import os
from pipeshub_sdk import Pipeshub, models
from tests.test_client import create_test_http_client


def test_connectorconfiguration_update_connector_config():
    test_http_client = create_test_http_client("updateConnectorConfig")

    with Pipeshub(
        client=test_http_client,
        security=models.Security(
            bearer_auth=os.getenv("PIPESHUB_BEARER_AUTH", "value"),
        ),
    ) as pipeshub:
        assert pipeshub is not None

        res = pipeshub.connector_configuration.update_config(
            connector_id="<id>",
            auth={
                "values": {
                    "apiKey": "sk-xxxxx",
                    "baseUrl": "https://api.example.com",
                },
                "oauth_config_id": "oauth_config_123",
            },
            sync={
                "scheduled_config": {
                    "cron_expression": "0 */6 * * *",
                    "timezone": "America/New_York",
                },
                "webhook_config": {
                    "events": [
                        "file.created",
                        "file.modified",
                        "file.deleted",
                    ],
                },
            },
            filters={
                "sync": {
                    "values": {
                        "fileTypes": [
                            "pdf",
                            "docx",
                            "xlsx",
                        ],
                        "folders": [
                            "folder_id_1",
                            "folder_id_2",
                        ],
                        "includeShared": True,
                    },
                },
            },
            base_url="https://confluence.mycompany.com",
        )
        assert res is not None
        assert res == models.UpdateConnectorConfigResponse(
            config=models.ConnectorConfig(
                scope="team",
            ),
        )


def test_connectorconfiguration_update_connector_auth_config():
    test_http_client = create_test_http_client("updateConnectorAuthConfig")

    with Pipeshub(
        client=test_http_client,
        security=models.Security(
            bearer_auth=os.getenv("PIPESHUB_BEARER_AUTH", "value"),
        ),
    ) as pipeshub:
        assert pipeshub is not None

        res = pipeshub.connector_configuration.update_auth_config(
            connector_id="<id>",
            auth={
                "values": {
                    "apiKey": "sk-xxxxx",
                    "baseUrl": "https://api.example.com",
                },
                "oauth_config_id": "oauth_config_123",
            },
        )
        assert res is not None
        assert res == models.UpdateConnectorAuthConfigResponse(
            config=models.ConnectorConfig(
                scope="team",
            ),
        )
