"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

import os
from pipeshub_sdk import Pipeshub, models
from tests.test_client import create_test_http_client


def test_uploads_get_upload_limits():
    test_http_client = create_test_http_client("getUploadLimits")

    with Pipeshub(
        client=test_http_client,
        security=models.Security(
            bearer_auth=os.getenv("PIPESHUB_BEARER_AUTH", "value"),
        ),
    ) as pipeshub:
        assert pipeshub is not None

        res = pipeshub.uploads.get_limits()
        assert res is not None
        assert res == models.GetUploadLimitsResponse(
            max_files_per_request=1000,
            max_file_size_bytes=31457280,
        )
