"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

import os
from pipeshub_sdk import Pipeshub, models
from tests.test_client import create_test_http_client


def test_smtpconfiguration_get_smtp_config():
    test_http_client = create_test_http_client("getSMTPConfig")

    with Pipeshub(
        client=test_http_client,
        security=models.Security(
            bearer_auth=os.getenv("PIPESHUB_BEARER_AUTH", "value"),
        ),
    ) as pipeshub:
        assert pipeshub is not None

        res = pipeshub.smtp_configuration.get_config()
        assert res is not None
        assert res == models.SMTPConfig(
            host="smtp.gmail.com",
            port=587,
            username="notifications@yourcompany.com",
            password="your-app-password",
            from_email="noreply@yourcompany.com",
        )
