"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: 1a325a24360b

from pipeshub_sdk import Pipeshub, models
from tests.test_client import create_test_http_client


def test_authenticationconfigurations_get_azure_ad_auth_config():
    test_http_client = create_test_http_client("getAzureAdAuthConfig")

    with Pipeshub(
        server_url="http://localhost:3000/api/v1",
        security=models.Security(),
        client=test_http_client,
    ) as pipeshub:
        assert pipeshub is not None

        res = pipeshub.authentication_configurations.get_azure_ad()
        assert res is not None
        assert res == models.AzureAdAuthConfig(
            client_id="12345678-1234-1234-1234-123456789abc",
        )


def test_authenticationconfigurations_get_generic_o_auth_config():
    test_http_client = create_test_http_client("getGenericOAuthConfig")

    with Pipeshub(
        server_url="http://localhost:3000/api/v1",
        security=models.Security(),
        client=test_http_client,
    ) as pipeshub:
        assert pipeshub is not None

        res = pipeshub.authentication_configurations.get_generic_o_auth_config()
        assert res is not None
        assert res == models.GenericOAuthConfig(
            provider_name="Custom OAuth Provider",
            scope="openid profile email",
        )
