"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

import os
from pipeshub_sdk import Pipeshub, models
from tests.test_client import create_test_http_client


def test_oauthconfiguration_2_get_o_auth_registry():
    test_http_client = create_test_http_client("getOAuthRegistry")

    with Pipeshub(
        client=test_http_client,
        security=models.Security(
            bearer_auth=os.getenv("PIPESHUB_BEARER_AUTH", "value"),
        ),
    ) as pipeshub:
        assert pipeshub is not None

        res = pipeshub.oauth_configuration.list_registry(page=1, limit=20)
        assert res is not None
        assert res == models.GetOAuthRegistryResponse(
            connectors=[
                models.ConnectorType(
                    connector_type="google-drive",
                    display_name="Google Drive",
                    supported_scopes=[
                        "team",
                    ],
                ),
            ],
        )


def test_oauthconfiguration_2_get_o_auth_connector_type():
    test_http_client = create_test_http_client("getOAuthConnectorType")

    with Pipeshub(
        client=test_http_client,
        security=models.Security(
            bearer_auth=os.getenv("PIPESHUB_BEARER_AUTH", "value"),
        ),
    ) as pipeshub:
        assert pipeshub is not None

        res = pipeshub.oauth_configuration.get_connector_type(connector_type="<value>")
        assert res is not None
        assert res == models.GetOAuthConnectorTypeResponse(
            connector=models.ConnectorType(
                connector_type="google-drive",
                display_name="Google Drive",
                supported_scopes=[
                    "team",
                ],
            ),
        )


def test_oauthconfiguration_2_list_o_auth_configs():
    test_http_client = create_test_http_client("listOAuthConfigs")

    with Pipeshub(
        client=test_http_client,
        security=models.Security(
            bearer_auth=os.getenv("PIPESHUB_BEARER_AUTH", "value"),
        ),
    ) as pipeshub:
        assert pipeshub is not None

        res = pipeshub.oauth_configuration.list(page=1, limit=20)
        assert res is not None
        assert res == models.ListOAuthConfigsResponse(
            oauth_configs=[
                models.OAuthConfig(
                    oauth_instance_name="Production Google OAuth",
                ),
            ],
        )


def test_oauthconfiguration_2_list_o_auth_configs_by_type():
    test_http_client = create_test_http_client("listOAuthConfigsByType")

    with Pipeshub(
        client=test_http_client,
        security=models.Security(
            bearer_auth=os.getenv("PIPESHUB_BEARER_AUTH", "value"),
        ),
    ) as pipeshub:
        assert pipeshub is not None

        res = pipeshub.oauth_configuration.list_by_type(
            connector_type="<value>", page=1, limit=20
        )
        assert res is not None
        assert res == models.ListOAuthConfigsByTypeResponse(
            oauth_configs=[
                models.OAuthConfig(
                    oauth_instance_name="Production Google OAuth",
                ),
            ],
        )


def test_oauthconfiguration_2_create_o_auth_config():
    test_http_client = create_test_http_client("createOAuthConfig")

    with Pipeshub(
        client=test_http_client,
        security=models.Security(
            bearer_auth=os.getenv("PIPESHUB_BEARER_AUTH", "value"),
        ),
    ) as pipeshub:
        assert pipeshub is not None

        res = pipeshub.oauth_configuration.create(
            connector_type="<value>",
            oauth_instance_name="Production Google OAuth Credentials",
            config={
                "client_id": "123456789-abc.apps.googleusercontent.com",
                "client_secret": "GOCSPX-xxxxxxxxxxxxx",
                "tenant_id": "12345678-1234-1234-1234-123456789abc",
            },
            base_url="https://gitlab.mycompany.com",
        )
        assert res is not None
        assert res == models.CreateOAuthConfigResponse(
            oauth_config=models.OAuthConfig(
                oauth_instance_name="Production Google OAuth",
            ),
        )


def test_oauthconfiguration_2_get_o_auth_config():
    test_http_client = create_test_http_client("getOAuthConfig")

    with Pipeshub(
        client=test_http_client,
        security=models.Security(
            bearer_auth=os.getenv("PIPESHUB_BEARER_AUTH", "value"),
        ),
    ) as pipeshub:
        assert pipeshub is not None

        res = pipeshub.oauth_configuration.get(
            connector_type="<value>", config_id="<id>"
        )
        assert res is not None
        assert res == models.GetOAuthConfigResponse(
            oauth_config=models.OAuthConfig(
                oauth_instance_name="Production Google OAuth",
            ),
        )


def test_oauthconfiguration_2_update_o_auth_config():
    test_http_client = create_test_http_client("updateOAuthConfig")

    with Pipeshub(
        client=test_http_client,
        security=models.Security(
            bearer_auth=os.getenv("PIPESHUB_BEARER_AUTH", "value"),
        ),
    ) as pipeshub:
        assert pipeshub is not None

        res = pipeshub.oauth_configuration.update(
            connector_type="<value>", config_id="<id>"
        )
        assert res is not None
        assert res == models.UpdateOAuthConfigResponse(
            oauth_config=models.OAuthConfig(
                oauth_instance_name="Production Google OAuth",
            ),
        )


def test_oauthconfiguration_2_delete_o_auth_config():
    test_http_client = create_test_http_client("deleteOAuthConfig")

    with Pipeshub(
        client=test_http_client,
        security=models.Security(
            bearer_auth=os.getenv("PIPESHUB_BEARER_AUTH", "value"),
        ),
    ) as pipeshub:
        assert pipeshub is not None

        res = pipeshub.oauth_configuration.delete(
            connector_type="<value>", config_id="<id>"
        )
        assert res is not None
        assert res == models.DeleteOAuthConfigResponse()
