"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: 56cce0c5e280

from pipeshub_sdk import Pipeshub, models
from tests.test_client import create_test_http_client


def test_aimodelsconfiguration_get_ai_models_config():
    test_http_client = create_test_http_client("getAIModelsConfig")

    with Pipeshub(
        server_url="http://localhost:3000/api/v1",
        security=models.Security(),
        client=test_http_client,
    ) as pipeshub:
        assert pipeshub is not None

        res = pipeshub.ai_models_configuration.get()
        assert res is not None
        assert res == models.GetAIModelsConfigResponse()


def test_aimodelsconfiguration_create_ai_models_config():
    test_http_client = create_test_http_client("createAIModelsConfig")

    with Pipeshub(
        server_url="http://localhost:3000/api/v1",
        security=models.Security(),
        client=test_http_client,
    ) as pipeshub:
        assert pipeshub is not None

        res = pipeshub.ai_models_configuration.create(request={})
        assert res is not None
        assert res == models.CreateAIModelsConfigResponse()
