"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: 8f516fa36cd6

import os
from pipeshub_sdk import Pipeshub, models
from tests.test_client import create_test_http_client


def test_useraccount_init_auth():
    test_http_client = create_test_http_client("initAuth")

    with Pipeshub(
        server_url="http://localhost:3000/api/v1",
        security=models.Security(),
        client=test_http_client,
    ) as pipeshub:
        assert pipeshub is not None

        res = pipeshub.user_account.init_auth(email="user@example.com")
        assert res is not None
        assert res.result is not None
        assert res.result == models.InitAuthResponse(
            current_step=0,
            allowed_methods=[
                "password",
                "google",
                "otp",
            ],
            message="Authentication initialized",
        )


def test_useraccount_authenticate():
    test_http_client = create_test_http_client("authenticate")

    with Pipeshub(
        server_url="http://localhost:3000/api/v1",
        security=models.Security(),
        client=test_http_client,
    ) as pipeshub:
        assert pipeshub is not None

        res = pipeshub.user_account.authenticate(
            x_session_token="<value>",
            method="oauth",
            credentials={
                "password": "o_5N_tt72qMx3WV",
            },
        )
        assert res is not None
        assert res == models.AuthenticateResponse(
            message="Fully authenticated",
        )


def test_useraccount_generate_login_otp():
    test_http_client = create_test_http_client("generateLoginOtp")

    with Pipeshub(
        server_url="http://localhost:3000/api/v1",
        security=models.Security(),
        client=test_http_client,
    ) as pipeshub:
        assert pipeshub is not None

        res = pipeshub.user_account.generate_otp(email="Garland.Sipes42@hotmail.com")
        assert res is not None
        assert res == models.GenerateLoginOtpResponse(
            message="OTP sent to your email",
        )


def test_useraccount_forgot_password():
    test_http_client = create_test_http_client("forgotPassword")

    with Pipeshub(
        server_url="http://localhost:3000/api/v1",
        security=models.Security(),
        client=test_http_client,
    ) as pipeshub:
        assert pipeshub is not None

        res = pipeshub.user_account.forgot_password(
            email="Barton.Gutkowski68@yahoo.com"
        )
        assert res is not None
        assert res == models.ForgotPasswordResponse(
            message="Password reset email sent",
        )


def test_useraccount_reset_password_with_token():
    test_http_client = create_test_http_client("resetPasswordWithToken")

    with Pipeshub(
        server_url="http://localhost:3000/api/v1",
        client=test_http_client,
    ) as pipeshub:
        assert pipeshub is not None

        res = pipeshub.user_account.reset_password_token(
            security=models.ResetPasswordWithTokenSecurity(
                scoped_token=os.getenv("PIPESHUB_SCOPED_TOKEN", "value"),
            ),
            password="H9GEHoL829GXj06",
        )
        assert res is not None
        assert res == models.PasswordResetResponse(
            data="password reset",
        )


def test_useraccount_refresh_token():
    test_http_client = create_test_http_client("refreshToken")

    with Pipeshub(
        server_url="http://localhost:3000/api/v1",
        client=test_http_client,
    ) as pipeshub:
        assert pipeshub is not None

        res = pipeshub.user_account.refresh(
            security=models.RefreshTokenSecurity(
                scoped_token=os.getenv("PIPESHUB_SCOPED_TOKEN", "value"),
            )
        )
        assert res is not None
        assert res == models.RefreshTokenResponse()


def test_useraccount_logout():
    test_http_client = create_test_http_client("logout")

    with Pipeshub(
        server_url="http://localhost:3000/api/v1",
        security=models.Security(),
        client=test_http_client,
    ) as pipeshub:
        assert pipeshub is not None

        res = pipeshub.user_account.logout()
        assert res is not None
        assert res == models.LogoutResponse(
            message="Logged out successfully",
        )


def test_useraccount_reset_password():
    test_http_client = create_test_http_client("resetPassword")

    with Pipeshub(
        server_url="http://localhost:3000/api/v1",
        security=models.Security(),
        client=test_http_client,
    ) as pipeshub:
        assert pipeshub is not None

        res = pipeshub.user_account.reset_password(
            current_password="fR5Alu28cPCa984", new_password="vcFGz9GLaOB88kV"
        )
        assert res is not None
        assert res == models.ResetPasswordResponse(
            message="Password reset successfully",
        )


def test_useraccount_validate_email_change_token():
    test_http_client = create_test_http_client("validateEmailChangeToken")

    with Pipeshub(
        server_url="http://localhost:3000/api/v1",
        client=test_http_client,
    ) as pipeshub:
        assert pipeshub is not None

        res = pipeshub.user_account.validate_email_change_token(
            security=models.ValidateEmailChangeTokenSecurity(
                scoped_token=os.getenv("PIPESHUB_SCOPED_TOKEN", "value"),
            )
        )
        assert res is not None
        assert res == models.ValidateEmailChangeTokenResponse(
            message="Email updated successfully",
        )
