"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: ef559b6d88ce

from pipeshub_sdk import Pipeshub, models
import pytest
from tests.test_client import create_test_http_client


def test_authentication_configuration_get_sso_auth_config():
    test_http_client = create_test_http_client("getSsoAuthConfig")

    with Pipeshub(
        server_url="http://localhost:3000/api/v1",
        security=models.Security(),
        client=test_http_client,
    ) as pipeshub:
        assert pipeshub is not None

        res = pipeshub.authentication_configuration.get_sso_auth_config()
        assert res is not None
        assert res == models.SSOAuthConfig(
            certificate="<value>",
            entry_point="https://left-swanling.net/",
            email_key="<value>",
        )


@pytest.mark.skip(
    reason="incomplete test found please make sure to address the following errors: [`workflow step getAzureAdAuthConfig.test referencing operation getAzureAdAuthConfig not found in document`]"
)
def test_authentication_configuration_get_azure_ad_auth_config():
    pass


def test_authentication_configuration_get_generic_o_auth_config():
    test_http_client = create_test_http_client("getGenericOAuthConfig")

    with Pipeshub(
        server_url="http://localhost:3000/api/v1",
        security=models.Security(),
        client=test_http_client,
    ) as pipeshub:
        assert pipeshub is not None

        res = pipeshub.authentication_configuration.get_generic_o_auth_config()
        assert res is not None
        assert res == models.GenericOAuthConfig(
            provider_name="<value>",
            client_id="<id>",
            client_secret="<value>",
            authorization_url="https://pertinent-icebreaker.org",
            token_endpoint="https://apt-bid.org/",
            user_info_endpoint="https://uniform-reporter.info/",
            scope="openid email profile",
            redirect_uri="https://misguided-stitcher.com/",
        )


def test_authentication_configuration_get_microsoft_auth_config():
    test_http_client = create_test_http_client("getMicrosoftAuthConfig")

    with Pipeshub(
        server_url="http://localhost:3000/api/v1",
        security=models.Security(),
        client=test_http_client,
    ) as pipeshub:
        assert pipeshub is not None

        res = pipeshub.authentication_configuration.get_microsoft_auth_config()
        assert res is not None
        assert res == models.MicrosoftAuthConfig(
            client_id="<id>",
            authority="https://login.microsoftonline.com/{tenantId}",
        )


def test_authentication_configuration_get_google_auth_config():
    test_http_client = create_test_http_client("getGoogleAuthConfig")

    with Pipeshub(
        server_url="http://localhost:3000/api/v1",
        security=models.Security(),
        client=test_http_client,
    ) as pipeshub:
        assert pipeshub is not None

        res = pipeshub.authentication_configuration.get_google_auth_config()
        assert res is not None
        assert res == models.GoogleAuthConfig(
            client_id="<id>",
        )


def test_authentication_configuration_set_microsoft_auth_config():
    test_http_client = create_test_http_client("setMicrosoftAuthConfig")

    with Pipeshub(
        server_url="http://localhost:3000/api/v1",
        security=models.Security(),
        client=test_http_client,
    ) as pipeshub:
        assert pipeshub is not None

        res = pipeshub.authentication_configuration.set_microsoft_auth_config(
            client_id="<id>", tenant_id="common", enable_jit=False
        )
        assert res is not None
        assert res == models.SetMicrosoftAuthConfigResponse(
            message="Microsoft Auth config created successfully",
        )


def test_authentication_configuration_set_google_auth_config():
    test_http_client = create_test_http_client("setGoogleAuthConfig")

    with Pipeshub(
        server_url="http://localhost:3000/api/v1",
        security=models.Security(),
        client=test_http_client,
    ) as pipeshub:
        assert pipeshub is not None

        res = pipeshub.authentication_configuration.set_google_auth_config(
            client_id="<id>", enable_jit=True
        )
        assert res is not None
        assert res == models.SetGoogleAuthConfigResponse(
            message="Google Auth config created successfully",
        )


def test_authentication_configuration_set_sso_auth_config():
    test_http_client = create_test_http_client("setSsoAuthConfig")

    with Pipeshub(
        server_url="http://localhost:3000/api/v1",
        security=models.Security(),
        client=test_http_client,
    ) as pipeshub:
        assert pipeshub is not None

        res = pipeshub.authentication_configuration.set_sso_auth_config(
            certificate="<value>",
            entry_point="https://unwieldy-sprinkles.name",
            email_key="<value>",
            enable_jit=True,
        )
        assert res is not None
        assert res == models.SetSsoAuthConfigResponse(
            message="SSO Auth config created successfully",
        )


def test_authentication_configuration_set_o_auth_config():
    test_http_client = create_test_http_client("setOAuthConfig")

    with Pipeshub(
        server_url="http://localhost:3000/api/v1",
        security=models.Security(),
        client=test_http_client,
    ) as pipeshub:
        assert pipeshub is not None

        res = pipeshub.authentication_configuration.set_o_auth_config(
            provider_name="<value>",
            client_id="<id>",
            client_secret="<value>",
            authorization_url="https://squeaky-ad.org",
            token_endpoint="https://rapid-cruelty.name/",
            user_info_endpoint="https://far-flung-habit.net",
            scope="openid email profile",
            redirect_uri="https://questionable-straw.biz",
            enable_jit=True,
        )
        assert res is not None
        assert res == models.SetOAuthConfigResponse(
            message="OAuth config created successfully",
        )
