"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: ef559b6d88ce

from pipeshub_sdk import Pipeshub, models
from tests.test_client import create_test_http_client


def test_authentication_configuration_get_sso_auth_config():
    test_http_client = create_test_http_client("getSsoAuthConfig")

    with Pipeshub(
        server_url="http://localhost:3000/api/v1",
        security=models.Security(),
        client=test_http_client,
    ) as pipeshub:
        assert pipeshub is not None

        res = pipeshub.authentication_configuration.get_sso_auth_config()
        assert res is not None
        assert res == models.SSOAuthConfig(
            entry_point="https://idp.example.com/sso/saml",
            email_key="email",
        )


def test_authentication_configuration_get_azure_ad_auth_config():
    test_http_client = create_test_http_client("getAzureAdAuthConfig")

    with Pipeshub(
        server_url="http://localhost:3000/api/v1",
        security=models.Security(),
        client=test_http_client,
    ) as pipeshub:
        assert pipeshub is not None

        res = pipeshub.authentication_configuration.get_azure_ad_auth_config()
        assert res is not None
        assert res == models.AzureAdAuthConfig(
            client_id="12345678-1234-1234-1234-123456789abc",
        )


def test_authentication_configuration_get_generic_o_auth_config():
    test_http_client = create_test_http_client("getGenericOAuthConfig")

    with Pipeshub(
        server_url="http://localhost:3000/api/v1",
        security=models.Security(),
        client=test_http_client,
    ) as pipeshub:
        assert pipeshub is not None

        res = pipeshub.authentication_configuration.get_generic_o_auth_config()
        assert res is not None
        assert res == models.GenericOAuthConfig(
            provider_name="Custom OAuth Provider",
            scope="openid profile email",
        )


def test_authentication_configuration_get_microsoft_auth_config():
    test_http_client = create_test_http_client("getMicrosoftAuthConfig")

    with Pipeshub(
        server_url="http://localhost:3000/api/v1",
        security=models.Security(),
        client=test_http_client,
    ) as pipeshub:
        assert pipeshub is not None

        res = pipeshub.authentication_configuration.get_microsoft_auth_config()
        assert res is not None
        assert res == models.MicrosoftAuthConfig(
            client_id="12345678-1234-1234-1234-123456789abc",
            authority="https://login.microsoftonline.com/common",
        )


def test_authentication_configuration_get_google_auth_config():
    test_http_client = create_test_http_client("getGoogleAuthConfig")

    with Pipeshub(
        server_url="http://localhost:3000/api/v1",
        security=models.Security(),
        client=test_http_client,
    ) as pipeshub:
        assert pipeshub is not None

        res = pipeshub.authentication_configuration.get_google_auth_config()
        assert res is not None
        assert res == models.GoogleAuthConfig(
            client_id="123456789-abc.apps.googleusercontent.com",
        )
