"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

import os
from pipeshub_sdk import Pipeshub, models
from tests.test_client import create_test_http_client


def test_toolset_registry_list_toolset_registry():
    test_http_client = create_test_http_client("listToolsetRegistry")

    with Pipeshub(
        client=test_http_client,
        security=models.Security(
            bearer_auth=os.getenv("PIPESHUB_BEARER_AUTH", "value"),
        ),
    ) as pipeshub:
        assert pipeshub is not None

        res = pipeshub.toolset_registry.list_toolset_registry(page=1, limit=50)
        assert res is not None
        assert res == models.ListToolsetRegistryResponse()
