"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: a50b4c6e3fc8

from pipeshub_sdk import Pipeshub, models
import pytest
from tests.test_client import create_test_http_client


def test_agentconversations_list_agent_conversations():
    test_http_client = create_test_http_client("listAgentConversations")

    with Pipeshub(
        server_url="http://localhost:3000/api/v1",
        security=models.Security(),
        client=test_http_client,
    ) as pipeshub:
        assert pipeshub is not None

        res = pipeshub.agent_conversations.list(agent_key="<value>")
        assert res is not None
        assert res == models.ListAgentConversationsResponse(
            conversations=[
                models.Conversation(
                    title="Q4 Financial Report Discussion",
                ),
            ],
            shared_with_me_conversations=[
                models.Conversation(
                    title="Q4 Financial Report Discussion",
                ),
            ],
        )


def test_agentconversations_create_agent_conversation():
    test_http_client = create_test_http_client("createAgentConversation")

    with Pipeshub(
        server_url="http://localhost:3000/api/v1",
        security=models.Security(),
        client=test_http_client,
    ) as pipeshub:
        assert pipeshub is not None

        res = pipeshub.agent_conversations.create(
            agent_key="<value>",
            query="What are the key findings from our Q4 financial report?",
            record_ids=[
                "507f1f77bcf86cd799439011",
                "507f1f77bcf86cd799439012",
            ],
            filters={
                "apps": [
                    "550e8400-e29b-41d4-a716-446655440000",
                ],
            },
            model_key="gpt-4-turbo",
            model_name="GPT-4 Turbo",
            chat_mode="balanced",
        )
        assert res is not None
        assert res == models.AgentConversation()


def test_agentconversations_get_agent_conversation():
    test_http_client = create_test_http_client("getAgentConversation")

    with Pipeshub(
        server_url="http://localhost:3000/api/v1",
        security=models.Security(),
        client=test_http_client,
    ) as pipeshub:
        assert pipeshub is not None

        res = pipeshub.agent_conversations.get(
            agent_key="<value>", conversation_id="<value>"
        )
        assert res is not None
        assert res == models.AgentConversation()


def test_agentconversations_add_agent_message():
    test_http_client = create_test_http_client("addAgentMessage")

    with Pipeshub(
        server_url="http://localhost:3000/api/v1",
        security=models.Security(),
        client=test_http_client,
    ) as pipeshub:
        assert pipeshub is not None

        res = pipeshub.agent_conversations.add_message(
            agent_key="<value>",
            conversation_id="<value>",
            query="Can you elaborate on the revenue trends?",
            filters={
                "apps": [
                    "550e8400-e29b-41d4-a716-446655440000",
                ],
            },
        )
        assert res is not None
        assert res == models.AgentConversation()


@pytest.mark.skip(
    reason="incomplete test found please make sure to address the following errors: [`workflow step regenerateAgentAnswer.test referencing operation regenerateAgentAnswer is not currently supported`]"
)
def test_agentconversations_regenerate_agent_answer():
    pass
