"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: 7a67698719e7

from pipeshub_sdk import Pipeshub, models
from tests.test_client import create_test_http_client


def test_connectorcontrols_toggle_connector():
    test_http_client = create_test_http_client("toggleConnector")

    with Pipeshub(
        server_url="http://localhost:3000/api/v1",
        security=models.Security(),
        client=test_http_client,
    ) as pipeshub:
        assert pipeshub is not None

        res = pipeshub.connector_controls.toggle(connector_id="<id>", type_="sync")
        assert res is not None
        assert res == models.ToggleConnectorResponse()
