"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

import os
from pipeshub_sdk import Pipeshub, models
from tests.test_client import create_test_http_client


def test_mcp_handle_mcp_request():
    test_http_client = create_test_http_client("handleMCPRequest")

    with Pipeshub(
        client=test_http_client,
        security=models.Security(
            bearer_auth=os.getenv("PIPESHUB_BEARER_AUTH", "value"),
        ),
    ) as pipeshub:
        assert pipeshub is not None

        res = pipeshub.mcp.handle_mcp_request(jsonrpc="2.0", method="<value>")
        assert res is not None
        assert res == models.HandleMCPRequestResponse()
