"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: 59800da582a4

from pipeshub_sdk import Pipeshub, models
from tests.test_client import create_test_http_client


def test_ai_models_providers_get_models_by_type():
    test_http_client = create_test_http_client("getModelsByType")

    with Pipeshub(
        server_url="http://localhost:3000/api/v1",
        security=models.Security(),
        client=test_http_client,
    ) as pipeshub:
        assert pipeshub is not None

        res = pipeshub.ai_models_providers.get_models_by_type(model_type="embedding")
        assert res is not None
        assert res == models.GetModelsByTypeResponse()


def test_ai_models_providers_get_available_models_by_type():
    test_http_client = create_test_http_client("getAvailableModelsByType")

    with Pipeshub(
        server_url="http://localhost:3000/api/v1",
        security=models.Security(),
        client=test_http_client,
    ) as pipeshub:
        assert pipeshub is not None

        res = pipeshub.ai_models_providers.get_available_models_by_type(
            model_type="llm"
        )
        assert res is not None
        assert res == models.GetAvailableModelsByTypeResponse()


def test_ai_models_providers_add_ai_model_provider():
    test_http_client = create_test_http_client("addAIModelProvider")

    with Pipeshub(
        server_url="http://localhost:3000/api/v1",
        security=models.Security(),
        client=test_http_client,
    ) as pipeshub:
        assert pipeshub is not None

        res = pipeshub.ai_models_providers.add_ai_model_provider(
            model_type="embedding",
            provider="cohere",
            configuration={
                "model": "gpt-4",
            },
            is_multimodal=False,
            is_reasoning=False,
            is_default=False,
        )
        assert res is not None
        assert res == models.AIModelProviderResponse()
