"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

import os
from pipeshub_sdk import Pipeshub, models
from tests.test_client import create_test_http_client


def test_upload_upload_records_to_kb():
    test_http_client = create_test_http_client("uploadRecordsToKB")

    with Pipeshub(
        client=test_http_client,
        security=models.Security(
            bearer_auth=os.getenv("PIPESHUB_BEARER_AUTH", "value"),
        ),
    ) as pipeshub:
        assert pipeshub is not None

        res = pipeshub.upload.to_knowledge_base(
            kb_id="<id>",
            files=[
                {
                    "file_name": "example.file",
                    "content": open(".speakeasy/testfiles/example.file", "rb"),
                },
            ],
            files_metadata='[{"file_path":"/docs/report.pdf","last_modified":"2024-01-15T10:30:00Z"}]',
            is_versioned=True,
            record_type="FILE",
        )
        assert res is not None
        assert res == models.UploadResult(
            message="Files uploaded successfully",
        )


def test_upload_upload_records_to_folder():
    test_http_client = create_test_http_client("uploadRecordsToFolder")

    with Pipeshub(
        client=test_http_client,
        security=models.Security(
            bearer_auth=os.getenv("PIPESHUB_BEARER_AUTH", "value"),
        ),
    ) as pipeshub:
        assert pipeshub is not None

        res = pipeshub.upload.records_to_folder(
            kb_id="<id>",
            folder_id="<id>",
            files=[
                {
                    "file_name": "example.file",
                    "content": open(".speakeasy/testfiles/example.file", "rb"),
                },
            ],
            is_versioned=True,
        )
        assert res is not None
        assert res == models.UploadResult(
            message="Files uploaded successfully",
        )
