"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: e60b0cd90e20

from pipeshub_sdk import Pipeshub, models
from tests.test_client import create_test_http_client


def test_upload_upload_records_to_kb():
    test_http_client = create_test_http_client("uploadRecordsToKB")

    with Pipeshub(
        server_url="http://localhost:3000/api/v1",
        security=models.Security(),
        client=test_http_client,
    ) as pipeshub:
        assert pipeshub is not None

        res = pipeshub.upload.upload_records_to_kb(
            kb_id="<id>",
            files=[
                {
                    "file_name": "example.file",
                    "content": open(".speakeasy/testfiles/example.file", "rb"),
                },
            ],
            files_metadata='[{"file_path":"/docs/report.pdf","last_modified":"2024-01-15T10:30:00Z"}]',
            is_versioned=True,
            record_type="FILE",
        )
        assert res is not None
        assert res == models.UploadResult(
            message="Files uploaded successfully",
        )


def test_upload_upload_records_to_folder():
    test_http_client = create_test_http_client("uploadRecordsToFolder")

    with Pipeshub(
        server_url="http://localhost:3000/api/v1",
        security=models.Security(),
        client=test_http_client,
    ) as pipeshub:
        assert pipeshub is not None

        res = pipeshub.upload.upload_records_to_folder(
            kb_id="<id>",
            folder_id="<id>",
            files=[
                {
                    "file_name": "example.file",
                    "content": open(".speakeasy/testfiles/example.file", "rb"),
                },
            ],
            is_versioned=True,
        )
        assert res is not None
        assert res == models.UploadResult(
            message="Files uploaded successfully",
        )


def test_upload_get_upload_limits():
    test_http_client = create_test_http_client("getUploadLimits")

    with Pipeshub(
        server_url="http://localhost:3000/api/v1",
        security=models.Security(),
        client=test_http_client,
    ) as pipeshub:
        assert pipeshub is not None

        res = pipeshub.upload.get_upload_limits()
        assert res is not None
        assert res == models.GetUploadLimitsResponse(
            max_files_per_request=1000,
            max_file_size_bytes=31457280,
        )
