"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

import os
from pipeshub_sdk import Pipeshub, models
from tests.test_client import create_test_http_client


def test_knowledgebases_create_knowledge_base():
    test_http_client = create_test_http_client("createKnowledgeBase")

    with Pipeshub(
        client=test_http_client,
        security=models.Security(
            bearer_auth=os.getenv("PIPESHUB_BEARER_AUTH", "value"),
        ),
    ) as pipeshub:
        assert pipeshub is not None

        res = pipeshub.knowledge_bases.create(kb_name="Product Documentation")
        assert res is not None
        assert res == models.KnowledgeBase(
            name="<value>",
        )


def test_knowledgebases_list_knowledge_bases():
    test_http_client = create_test_http_client("listKnowledgeBases")

    with Pipeshub(
        client=test_http_client,
        security=models.Security(
            bearer_auth=os.getenv("PIPESHUB_BEARER_AUTH", "value"),
        ),
    ) as pipeshub:
        assert pipeshub is not None

        res = pipeshub.knowledge_bases.list(
            page=1,
            limit=20,
            permissions="OWNER,ORGANIZER,WRITER",
            sort_by="name",
            sort_order="asc",
        )
        assert res is not None
        assert res == models.ListKnowledgeBasesResponse()


def test_knowledgebases_get_knowledge_base():
    test_http_client = create_test_http_client("getKnowledgeBase")

    with Pipeshub(
        client=test_http_client,
        security=models.Security(
            bearer_auth=os.getenv("PIPESHUB_BEARER_AUTH", "value"),
        ),
    ) as pipeshub:
        assert pipeshub is not None

        res = pipeshub.knowledge_bases.get(kb_id="kb_550e8400-e29b-41d4-a716")
        assert res is not None
        assert res == models.KnowledgeBase(
            name="<value>",
        )


def test_knowledgebases_update_knowledge_base():
    test_http_client = create_test_http_client("updateKnowledgeBase")

    with Pipeshub(
        client=test_http_client,
        security=models.Security(
            bearer_auth=os.getenv("PIPESHUB_BEARER_AUTH", "value"),
        ),
    ) as pipeshub:
        assert pipeshub is not None

        res = pipeshub.knowledge_bases.update(
            kb_id="<id>", kb_name="Updated Documentation Hub"
        )
        assert res is not None
        assert res == models.KnowledgeBase(
            name="<value>",
        )


def test_knowledgebases_delete_knowledge_base():
    test_http_client = create_test_http_client("deleteKnowledgeBase")

    with Pipeshub(
        client=test_http_client,
        security=models.Security(
            bearer_auth=os.getenv("PIPESHUB_BEARER_AUTH", "value"),
        ),
    ) as pipeshub:
        assert pipeshub is not None

        res = pipeshub.knowledge_bases.delete(kb_id="<id>")
        assert res is not None
        assert res == models.DeleteKnowledgeBaseResponse(
            success=True,
            message="Knowledge base deleted successfully",
        )


def test_knowledgebases_get_knowledge_hub_root_nodes():
    test_http_client = create_test_http_client("getKnowledgeHubRootNodes")

    with Pipeshub(
        client=test_http_client,
        security=models.Security(
            bearer_auth=os.getenv("PIPESHUB_BEARER_AUTH", "value"),
        ),
    ) as pipeshub:
        assert pipeshub is not None

        res = pipeshub.knowledge_bases.get_root_nodes()
        assert res is not None
        assert res == models.GetKnowledgeHubRootNodesResponse()


def test_knowledgebases_get_knowledge_hub_child_nodes():
    test_http_client = create_test_http_client("getKnowledgeHubChildNodes")

    with Pipeshub(
        client=test_http_client,
        security=models.Security(
            bearer_auth=os.getenv("PIPESHUB_BEARER_AUTH", "value"),
        ),
    ) as pipeshub:
        assert pipeshub is not None

        res = pipeshub.knowledge_bases.get_child_nodes(
            parent_type="<value>", parent_id="<id>"
        )
        assert res is not None
        assert res == models.GetKnowledgeHubChildNodesResponse()


def test_knowledgebases_reindex_failed_records():
    test_http_client = create_test_http_client("reindexFailedRecords")

    with Pipeshub(
        client=test_http_client,
        security=models.Security(
            bearer_auth=os.getenv("PIPESHUB_BEARER_AUTH", "value"),
        ),
    ) as pipeshub:
        assert pipeshub is not None

        res = pipeshub.knowledge_bases.reindex_failed_records()
        assert res is not None
        assert res == models.ReindexFailedRecordsResponse(
            message="Reindex of failed records triggered",
        )


def test_knowledgebases_move_record():
    test_http_client = create_test_http_client("moveRecord")

    with Pipeshub(
        client=test_http_client,
        security=models.Security(
            bearer_auth=os.getenv("PIPESHUB_BEARER_AUTH", "value"),
        ),
    ) as pipeshub:
        assert pipeshub is not None

        res = pipeshub.knowledge_bases.move(
            kb_id="03bbd815-933b-4f49-9822-7811537c4ddc", record_id="<id>", body={}
        )
        assert res is not None
        assert res == models.MoveRecordResponse()
