"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from .pipeshuberror import PipeshubError
from typing import Any, TYPE_CHECKING

from pipeshub.utils.dynamic_imports import lazy_getattr, lazy_dir

if TYPE_CHECKING:
    from .autherror import AuthError, AuthErrorData
    from .no_response_error import NoResponseError
    from .oautherrorresponse import OAuthErrorResponse, OAuthErrorResponseData
    from .pipeshubdefaulterror import PipeshubDefaultError
    from .responsevalidationerror import ResponseValidationError

__all__ = [
    "AuthError",
    "AuthErrorData",
    "NoResponseError",
    "OAuthErrorResponse",
    "OAuthErrorResponseData",
    "PipeshubDefaultError",
    "PipeshubError",
    "ResponseValidationError",
]

_dynamic_imports: dict[str, str] = {
    "AuthError": ".autherror",
    "AuthErrorData": ".autherror",
    "NoResponseError": ".no_response_error",
    "OAuthErrorResponse": ".oautherrorresponse",
    "OAuthErrorResponseData": ".oautherrorresponse",
    "PipeshubDefaultError": ".pipeshubdefaulterror",
    "ResponseValidationError": ".responsevalidationerror",
}


def __getattr__(attr_name: str) -> Any:
    return lazy_getattr(
        attr_name, package=__package__, dynamic_imports=_dynamic_imports
    )


def __dir__():
    return lazy_dir(dynamic_imports=_dynamic_imports)
