"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .schemeoauth2 import SchemeOauth2, SchemeOauth2TypedDict
from pipeshub.types import BaseModel, UNSET_SENTINEL
from pipeshub.utils import FieldMetadata, PathParamMetadata, SecurityMetadata
import pydantic
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class DeleteTeamSecurityTypedDict(TypedDict):
    bearer_auth: NotRequired[str]
    oauth2: NotRequired[SchemeOauth2TypedDict]


class DeleteTeamSecurity(BaseModel):
    bearer_auth: Annotated[
        Optional[str],
        FieldMetadata(
            security=SecurityMetadata(
                scheme=True,
                scheme_type="http",
                sub_type="bearer",
                field_name="Authorization",
            )
        ),
    ] = None

    oauth2: Annotated[
        Optional[SchemeOauth2],
        FieldMetadata(
            security=SecurityMetadata(
                scheme=True, scheme_type="oauth2", sub_type="client_credentials"
            )
        ),
    ] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["bearerAuth", "oauth2"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class DeleteTeamRequestTypedDict(TypedDict):
    team_id: str
    r"""Unique identifier of the team to delete"""


class DeleteTeamRequest(BaseModel):
    team_id: Annotated[
        str,
        pydantic.Field(alias="teamId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""Unique identifier of the team to delete"""


class DeleteTeamResponseTypedDict(TypedDict):
    r"""Team deleted successfully"""

    success: NotRequired[bool]
    message: NotRequired[str]


class DeleteTeamResponse(BaseModel):
    r"""Team deleted successfully"""

    success: Optional[bool] = None

    message: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["success", "message"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
