"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .jobstatus import JobStatus, JobStatusTypedDict
from .schemeoauth2 import SchemeOauth2, SchemeOauth2TypedDict
from pipeshub.types import BaseModel, UNSET_SENTINEL
from pipeshub.utils import FieldMetadata, PathParamMetadata, SecurityMetadata
import pydantic
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class GetCrawlingJobStatusSecurityTypedDict(TypedDict):
    bearer_auth: NotRequired[str]
    oauth2: NotRequired[SchemeOauth2TypedDict]


class GetCrawlingJobStatusSecurity(BaseModel):
    bearer_auth: Annotated[
        Optional[str],
        FieldMetadata(
            security=SecurityMetadata(
                scheme=True,
                scheme_type="http",
                sub_type="bearer",
                field_name="Authorization",
            )
        ),
    ] = None

    oauth2: Annotated[
        Optional[SchemeOauth2],
        FieldMetadata(
            security=SecurityMetadata(
                scheme=True, scheme_type="oauth2", sub_type="client_credentials"
            )
        ),
    ] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["bearerAuth", "oauth2"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class GetCrawlingJobStatusRequestTypedDict(TypedDict):
    connector: str
    r"""Connector type identifier"""
    connector_id: str
    r"""Unique identifier of the connector instance"""


class GetCrawlingJobStatusRequest(BaseModel):
    connector: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""Connector type identifier"""

    connector_id: Annotated[
        str,
        pydantic.Field(alias="connectorId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""Unique identifier of the connector instance"""


class GetCrawlingJobStatusResponseTypedDict(TypedDict):
    r"""Job status retrieved successfully"""

    success: NotRequired[bool]
    message: NotRequired[str]
    data: NotRequired[JobStatusTypedDict]
    r"""Complete status information for a crawling job"""


class GetCrawlingJobStatusResponse(BaseModel):
    r"""Job status retrieved successfully"""

    success: Optional[bool] = None

    message: Optional[str] = None

    data: Optional[JobStatus] = None
    r"""Complete status information for a crawling job"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["success", "message", "data"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
