"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .schemeoauth2 import SchemeOauth2, SchemeOauth2TypedDict
from pipeshub.types import BaseModel, UNSET_SENTINEL
from pipeshub.utils import FieldMetadata, SecurityMetadata
import pydantic
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class GetOrganizationLogoSecurityTypedDict(TypedDict):
    bearer_auth: NotRequired[str]
    oauth2: NotRequired[SchemeOauth2TypedDict]


class GetOrganizationLogoSecurity(BaseModel):
    bearer_auth: Annotated[
        Optional[str],
        FieldMetadata(
            security=SecurityMetadata(
                scheme=True,
                scheme_type="http",
                sub_type="bearer",
                field_name="Authorization",
            )
        ),
    ] = None

    oauth2: Annotated[
        Optional[SchemeOauth2],
        FieldMetadata(
            security=SecurityMetadata(
                scheme=True, scheme_type="oauth2", sub_type="client_credentials"
            )
        ),
    ] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["bearerAuth", "oauth2"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class GetOrganizationLogoResponseTypedDict(TypedDict):
    r"""Logo URL retrieved successfully"""

    success: NotRequired[bool]
    has_logo: NotRequired[bool]
    r"""Whether organization has a custom logo"""
    logo_url: NotRequired[str]
    r"""Signed URL to access the logo (null if no logo)"""


class GetOrganizationLogoResponse(BaseModel):
    r"""Logo URL retrieved successfully"""

    success: Optional[bool] = None

    has_logo: Annotated[Optional[bool], pydantic.Field(alias="hasLogo")] = None
    r"""Whether organization has a custom logo"""

    logo_url: Annotated[Optional[str], pydantic.Field(alias="logoUrl")] = None
    r"""Signed URL to access the logo (null if no logo)"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["success", "hasLogo", "logoUrl"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    GetOrganizationLogoResponse.model_rebuild()
except NameError:
    pass
