"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .schemeoauth2 import SchemeOauth2, SchemeOauth2TypedDict
from pipeshub.types import BaseModel, UNSET_SENTINEL, UnrecognizedStr
from pipeshub.utils import FieldMetadata, SecurityMetadata
import pydantic
from pydantic import model_serializer
from typing import Literal, Optional, Union
from typing_extensions import Annotated, NotRequired, TypedDict


class GetStorageConfigSecurityTypedDict(TypedDict):
    bearer_auth: NotRequired[str]
    oauth2: NotRequired[SchemeOauth2TypedDict]


class GetStorageConfigSecurity(BaseModel):
    bearer_auth: Annotated[
        Optional[str],
        FieldMetadata(
            security=SecurityMetadata(
                scheme=True,
                scheme_type="http",
                sub_type="bearer",
                field_name="Authorization",
            )
        ),
    ] = None

    oauth2: Annotated[
        Optional[SchemeOauth2],
        FieldMetadata(
            security=SecurityMetadata(
                scheme=True, scheme_type="oauth2", sub_type="client_credentials"
            )
        ),
    ] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["bearerAuth", "oauth2"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


StorageType = Union[
    Literal[
        "local",
        "s3",
        "azureBlob",
    ],
    UnrecognizedStr,
]
r"""Currently configured storage type"""


class GetStorageConfigResponseTypedDict(TypedDict):
    r"""Storage configuration retrieved"""

    storage_type: NotRequired[StorageType]
    r"""Currently configured storage type"""
    mount_name: NotRequired[str]
    r"""Mount point name (Local)"""
    base_url: NotRequired[str]
    r"""Base URL for files (Local)"""
    access_key_id: NotRequired[str]
    r"""AWS access key ID (S3)"""
    secret_access_key: NotRequired[str]
    r"""AWS secret access key (S3)"""
    region: NotRequired[str]
    r"""AWS region (S3)"""
    bucket_name: NotRequired[str]
    r"""S3 bucket name (S3)"""
    container_name: NotRequired[str]
    r"""Container name (Azure Blob)"""
    account_name: NotRequired[str]
    r"""Storage account name (Azure Blob)"""


class GetStorageConfigResponse(BaseModel):
    r"""Storage configuration retrieved"""

    storage_type: Annotated[
        Optional[StorageType], pydantic.Field(alias="storageType")
    ] = None
    r"""Currently configured storage type"""

    mount_name: Annotated[Optional[str], pydantic.Field(alias="mountName")] = None
    r"""Mount point name (Local)"""

    base_url: Annotated[Optional[str], pydantic.Field(alias="baseUrl")] = None
    r"""Base URL for files (Local)"""

    access_key_id: Annotated[Optional[str], pydantic.Field(alias="accessKeyId")] = None
    r"""AWS access key ID (S3)"""

    secret_access_key: Annotated[
        Optional[str], pydantic.Field(alias="secretAccessKey")
    ] = None
    r"""AWS secret access key (S3)"""

    region: Optional[str] = None
    r"""AWS region (S3)"""

    bucket_name: Annotated[Optional[str], pydantic.Field(alias="bucketName")] = None
    r"""S3 bucket name (S3)"""

    container_name: Annotated[Optional[str], pydantic.Field(alias="containerName")] = (
        None
    )
    r"""Container name (Azure Blob)"""

    account_name: Annotated[Optional[str], pydantic.Field(alias="accountName")] = None
    r"""Storage account name (Azure Blob)"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "storageType",
                "mountName",
                "baseUrl",
                "accessKeyId",
                "secretAccessKey",
                "region",
                "bucketName",
                "containerName",
                "accountName",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    GetStorageConfigResponse.model_rebuild()
except NameError:
    pass
