"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .connectorinstance import ConnectorInstance, ConnectorInstanceTypedDict
from .connectorpagination import ConnectorPagination, ConnectorPaginationTypedDict
from .connectorscope import ConnectorScope
from .schemeoauth2 import SchemeOauth2, SchemeOauth2TypedDict
from pipeshub.types import BaseModel, UNSET_SENTINEL
from pipeshub.utils import FieldMetadata, QueryParamMetadata, SecurityMetadata
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class ListConfiguredConnectorsSecurityTypedDict(TypedDict):
    bearer_auth: NotRequired[str]
    oauth2: NotRequired[SchemeOauth2TypedDict]


class ListConfiguredConnectorsSecurity(BaseModel):
    bearer_auth: Annotated[
        Optional[str],
        FieldMetadata(
            security=SecurityMetadata(
                scheme=True,
                scheme_type="http",
                sub_type="bearer",
                field_name="Authorization",
            )
        ),
    ] = None

    oauth2: Annotated[
        Optional[SchemeOauth2],
        FieldMetadata(
            security=SecurityMetadata(
                scheme=True, scheme_type="oauth2", sub_type="client_credentials"
            )
        ),
    ] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["bearerAuth", "oauth2"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class ListConfiguredConnectorsRequestTypedDict(TypedDict):
    scope: NotRequired[ConnectorScope]
    r"""Scope determines visibility and access control for connectors:<br>
    <ul>
    <li><code>team</code> - Available to all users in the organization (admin-only creation)</li>
    <li><code>personal</code> - Private to the creating user only</li>
    </ul>

    """
    page: NotRequired[int]
    limit: NotRequired[int]
    search: NotRequired[str]


class ListConfiguredConnectorsRequest(BaseModel):
    scope: Annotated[
        Optional[ConnectorScope],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Scope determines visibility and access control for connectors:<br>
    <ul>
    <li><code>team</code> - Available to all users in the organization (admin-only creation)</li>
    <li><code>personal</code> - Private to the creating user only</li>
    </ul>

    """

    page: Annotated[
        Optional[int],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = 1

    limit: Annotated[
        Optional[int],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = 20

    search: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["scope", "page", "limit", "search"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class ListConfiguredConnectorsResponseTypedDict(TypedDict):
    r"""Configured connectors retrieved"""

    success: NotRequired[bool]
    connectors: NotRequired[List[ConnectorInstanceTypedDict]]
    pagination: NotRequired[ConnectorPaginationTypedDict]
    r"""Pagination information for connector lists"""


class ListConfiguredConnectorsResponse(BaseModel):
    r"""Configured connectors retrieved"""

    success: Optional[bool] = None

    connectors: Optional[List[ConnectorInstance]] = None

    pagination: Optional[ConnectorPagination] = None
    r"""Pagination information for connector lists"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["success", "connectors", "pagination"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
