"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .addmessageresponse import AddMessageResponse, AddMessageResponseTypedDict
from .agentaddmessagerequest import (
    AgentAddMessageRequest,
    AgentAddMessageRequestTypedDict,
)
from pipeshub_sdk.types import BaseModel
from pipeshub_sdk.utils import FieldMetadata, PathParamMetadata, RequestMetadata
import pydantic
from typing import Dict, List
from typing_extensions import Annotated, TypedDict


class AddAgentConversationMessageRequestTypedDict(TypedDict):
    agent_key: str
    conversation_id: str
    body: AgentAddMessageRequestTypedDict
    r"""The follow-up question, with optional scope, model and tool overrides."""


class AddAgentConversationMessageRequest(BaseModel):
    agent_key: Annotated[
        str,
        pydantic.Field(alias="agentKey"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]

    conversation_id: Annotated[
        str,
        pydantic.Field(alias="conversationId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]

    body: Annotated[
        AgentAddMessageRequest,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
    r"""The follow-up question, with optional scope, model and tool overrides."""


class AddAgentConversationMessageResponseTypedDict(TypedDict):
    headers: Dict[str, List[str]]
    result: AddMessageResponseTypedDict


class AddAgentConversationMessageResponse(BaseModel):
    headers: Dict[str, List[str]]

    result: AddMessageResponse
