"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .addmessagerequest import AddMessageRequest, AddMessageRequestTypedDict
from .addmessageresponse import AddMessageResponse, AddMessageResponseTypedDict
from pipeshub_sdk.types import BaseModel
from pipeshub_sdk.utils import FieldMetadata, PathParamMetadata, RequestMetadata
import pydantic
from typing import Dict, List
from typing_extensions import Annotated, TypedDict


class AddMessageRequestRequestTypedDict(TypedDict):
    conversation_id: str
    body: AddMessageRequestTypedDict
    r"""The follow-up question, with optional scope and model overrides."""


class AddMessageRequestRequest(BaseModel):
    conversation_id: Annotated[
        str,
        pydantic.Field(alias="conversationId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]

    body: Annotated[
        AddMessageRequest,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
    r"""The follow-up question, with optional scope and model overrides."""


class AddMessageResponseResponseTypedDict(TypedDict):
    headers: Dict[str, List[str]]
    result: AddMessageResponseTypedDict


class AddMessageResponseResponse(BaseModel):
    headers: Dict[str, List[str]]

    result: AddMessageResponse
