"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: f42ed7fdaf37

from __future__ import annotations
from pipeshub_sdk.types import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class AgentKnowledgeFiltersParsedTypedDict(TypedDict):
    r"""Parsed filter criteria for knowledge source scoping"""

    record_groups: NotRequired[List[str]]
    r"""Record group filters"""
    records: NotRequired[List[str]]
    r"""Individual record filters"""


class AgentKnowledgeFiltersParsed(BaseModel):
    r"""Parsed filter criteria for knowledge source scoping"""

    record_groups: Annotated[
        Optional[List[str]], pydantic.Field(alias="recordGroups")
    ] = None
    r"""Record group filters"""

    records: Optional[List[str]] = None
    r"""Individual record filters"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["recordGroups", "records"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    AgentKnowledgeFiltersParsed.model_rebuild()
except NameError:
    pass
