"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: c91fa0cbc93e

from __future__ import annotations
from pipeshub_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
import pydantic
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class AgentCreateResponseToolsetTypedDict(TypedDict):
    pass


class AgentCreateResponseToolset(BaseModel):
    pass


class AgentCreateResponseKnowledgeTypedDict(TypedDict):
    pass


class AgentCreateResponseKnowledge(BaseModel):
    pass


class AgentCreateResponseTypedDict(TypedDict):
    r"""Agent object returned from create endpoint"""

    key: NotRequired[str]
    name: NotRequired[str]
    description: NotRequired[str]
    start_message: NotRequired[str]
    system_prompt: NotRequired[str]
    instructions: NotRequired[Nullable[str]]
    models: NotRequired[List[str]]
    tags: NotRequired[List[str]]
    is_active: NotRequired[bool]
    created_by: NotRequired[str]
    updated_by: NotRequired[Nullable[str]]
    created_at_timestamp: NotRequired[int]
    updated_at_timestamp: NotRequired[int]
    is_deleted: NotRequired[bool]
    toolsets: NotRequired[List[AgentCreateResponseToolsetTypedDict]]
    knowledge: NotRequired[List[AgentCreateResponseKnowledgeTypedDict]]


class AgentCreateResponse(BaseModel):
    r"""Agent object returned from create endpoint"""

    key: Annotated[Optional[str], pydantic.Field(alias="_key")] = None

    name: Optional[str] = None

    description: Optional[str] = None

    start_message: Annotated[Optional[str], pydantic.Field(alias="startMessage")] = None

    system_prompt: Annotated[Optional[str], pydantic.Field(alias="systemPrompt")] = None

    instructions: OptionalNullable[str] = UNSET

    models: Optional[List[str]] = None

    tags: Optional[List[str]] = None

    is_active: Annotated[Optional[bool], pydantic.Field(alias="isActive")] = None

    created_by: Annotated[Optional[str], pydantic.Field(alias="createdBy")] = None

    updated_by: Annotated[OptionalNullable[str], pydantic.Field(alias="updatedBy")] = (
        UNSET
    )

    created_at_timestamp: Annotated[
        Optional[int], pydantic.Field(alias="createdAtTimestamp")
    ] = None

    updated_at_timestamp: Annotated[
        Optional[int], pydantic.Field(alias="updatedAtTimestamp")
    ] = None

    is_deleted: Annotated[Optional[bool], pydantic.Field(alias="isDeleted")] = None

    toolsets: Optional[List[AgentCreateResponseToolset]] = None

    knowledge: Optional[List[AgentCreateResponseKnowledge]] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "_key",
                "name",
                "description",
                "startMessage",
                "systemPrompt",
                "instructions",
                "models",
                "tags",
                "isActive",
                "createdBy",
                "updatedBy",
                "createdAtTimestamp",
                "updatedAtTimestamp",
                "isDeleted",
                "toolsets",
                "knowledge",
            ]
        )
        nullable_fields = set(["instructions", "updatedBy"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


try:
    AgentCreateResponse.model_rebuild()
except NameError:
    pass
