"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .requestmeta import RequestMeta, RequestMetaTypedDict
from .storedagentconversation import (
    StoredAgentConversation,
    StoredAgentConversationTypedDict,
)
from pipeshub_sdk.types import BaseModel
from typing_extensions import TypedDict


class AgentConversationTitleUpdateResponseTypedDict(TypedDict):
    conversation: StoredAgentConversationTypedDict
    r"""Stored agent conversation document returned by non-list endpoints.

    """
    meta: RequestMetaTypedDict
    r"""Basic request metadata returned by the API."""


class AgentConversationTitleUpdateResponse(BaseModel):
    conversation: StoredAgentConversation
    r"""Stored agent conversation document returned by non-list endpoints.

    """

    meta: RequestMeta
    r"""Basic request metadata returned by the API."""
