"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: c747cae27494

from __future__ import annotations
from .agenttool import AgentTool, AgentToolTypedDict
from pipeshub_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
import pydantic
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class AgentToolsetTypedDict(TypedDict):
    r"""A toolset attached to an agent providing external tool capabilities"""

    key: NotRequired[str]
    r"""Unique key of the toolset"""
    name: NotRequired[str]
    r"""Toolset identifier name"""
    display_name: NotRequired[str]
    r"""Human-readable display name"""
    type: NotRequired[str]
    r"""Type of toolset"""
    instance_id: NotRequired[str]
    r"""Instance ID of the connected app"""
    selected_tools: NotRequired[Nullable[List[str]]]
    r"""Subset of tools selected by the user (null means all tools)"""
    tools: NotRequired[List[AgentToolTypedDict]]
    r"""List of tools available in this toolset"""


class AgentToolset(BaseModel):
    r"""A toolset attached to an agent providing external tool capabilities"""

    key: Annotated[Optional[str], pydantic.Field(alias="_key")] = None
    r"""Unique key of the toolset"""

    name: Optional[str] = None
    r"""Toolset identifier name"""

    display_name: Annotated[Optional[str], pydantic.Field(alias="displayName")] = None
    r"""Human-readable display name"""

    type: Optional[str] = None
    r"""Type of toolset"""

    instance_id: Annotated[Optional[str], pydantic.Field(alias="instanceId")] = None
    r"""Instance ID of the connected app"""

    selected_tools: Annotated[
        OptionalNullable[List[str]], pydantic.Field(alias="selectedTools")
    ] = UNSET
    r"""Subset of tools selected by the user (null means all tools)"""

    tools: Optional[List[AgentTool]] = None
    r"""List of tools available in this toolset"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "_key",
                "name",
                "displayName",
                "type",
                "instanceId",
                "selectedTools",
                "tools",
            ]
        )
        nullable_fields = set(["selectedTools"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


try:
    AgentToolset.model_rebuild()
except NameError:
    pass
