"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: c0b8b9766827

from __future__ import annotations
from pipeshub_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
import pydantic
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class AgentListItemTypedDict(TypedDict):
    r"""Agent summary returned in list endpoints (models as compact strings)"""

    id: NotRequired[str]
    key: NotRequired[str]
    rev: NotRequired[str]
    name: NotRequired[str]
    description: NotRequired[str]
    system_prompt: NotRequired[str]
    start_message: NotRequired[str]
    instructions: NotRequired[Nullable[str]]
    models: NotRequired[List[str]]
    r"""Model entries as compact strings (modelKey_modelName)"""
    tags: NotRequired[List[str]]
    is_active: NotRequired[bool]
    is_deleted: NotRequired[bool]
    share_with_org: NotRequired[bool]
    created_by: NotRequired[str]
    updated_by: NotRequired[Nullable[str]]
    created_at_timestamp: NotRequired[int]
    updated_at_timestamp: NotRequired[int]
    can_view: NotRequired[bool]
    can_share: NotRequired[bool]
    can_edit: NotRequired[bool]
    can_delete: NotRequired[bool]
    user_role: NotRequired[str]
    access_type: NotRequired[str]


class AgentListItem(BaseModel):
    r"""Agent summary returned in list endpoints (models as compact strings)"""

    id: Annotated[Optional[str], pydantic.Field(alias="_id")] = None

    key: Annotated[Optional[str], pydantic.Field(alias="_key")] = None

    rev: Annotated[Optional[str], pydantic.Field(alias="_rev")] = None

    name: Optional[str] = None

    description: Optional[str] = None

    system_prompt: Annotated[Optional[str], pydantic.Field(alias="systemPrompt")] = None

    start_message: Annotated[Optional[str], pydantic.Field(alias="startMessage")] = None

    instructions: OptionalNullable[str] = UNSET

    models: Optional[List[str]] = None
    r"""Model entries as compact strings (modelKey_modelName)"""

    tags: Optional[List[str]] = None

    is_active: Annotated[Optional[bool], pydantic.Field(alias="isActive")] = None

    is_deleted: Annotated[Optional[bool], pydantic.Field(alias="isDeleted")] = None

    share_with_org: Annotated[Optional[bool], pydantic.Field(alias="shareWithOrg")] = (
        None
    )

    created_by: Annotated[Optional[str], pydantic.Field(alias="createdBy")] = None

    updated_by: Annotated[OptionalNullable[str], pydantic.Field(alias="updatedBy")] = (
        UNSET
    )

    created_at_timestamp: Annotated[
        Optional[int], pydantic.Field(alias="createdAtTimestamp")
    ] = None

    updated_at_timestamp: Annotated[
        Optional[int], pydantic.Field(alias="updatedAtTimestamp")
    ] = None

    can_view: Optional[bool] = None

    can_share: Optional[bool] = None

    can_edit: Optional[bool] = None

    can_delete: Optional[bool] = None

    user_role: Optional[str] = None

    access_type: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "_id",
                "_key",
                "_rev",
                "name",
                "description",
                "systemPrompt",
                "startMessage",
                "instructions",
                "models",
                "tags",
                "isActive",
                "isDeleted",
                "shareWithOrg",
                "createdBy",
                "updatedBy",
                "createdAtTimestamp",
                "updatedAtTimestamp",
                "can_view",
                "can_share",
                "can_edit",
                "can_delete",
                "user_role",
                "access_type",
            ]
        )
        nullable_fields = set(["instructions", "updatedBy"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


try:
    AgentListItem.model_rebuild()
except NameError:
    pass
