"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pipeshub_sdk.types import BaseModel, UNSET_SENTINEL, UnrecognizedStr
from pydantic import model_serializer
from typing import Literal, Optional, Union
from typing_extensions import NotRequired, TypedDict


AgentStreamSSEEventEvent = Union[
    Literal[
        "connected",
        "status",
        "tool_calls",
        "tool_call",
        "tool_success",
        "tool_error",
        "tool_result",
        "tool_execution_complete",
        "answer_chunk",
        "restreaming",
        "metadata",
        "complete",
        "error",
    ],
    UnrecognizedStr,
]
r"""SSE event name.
See the enum for possible values.

"""


class AgentStreamSSEEventTypedDict(TypedDict):
    r"""SSE event envelope for `POST /agents/{agentKey}/conversations/stream`.
    Event names are listed in `event`; payload JSON is carried in `data`.

    """

    event: NotRequired[AgentStreamSSEEventEvent]
    r"""SSE event name.
    See the enum for possible values.

    """
    data: NotRequired[str]
    r"""JSON-encoded event payload.
    Shape depends on `event`.

    """


class AgentStreamSSEEvent(BaseModel):
    r"""SSE event envelope for `POST /agents/{agentKey}/conversations/stream`.
    Event names are listed in `event`; payload JSON is carried in `data`.

    """

    event: Optional[AgentStreamSSEEventEvent] = None
    r"""SSE event name.
    See the enum for possible values.

    """

    data: Optional[str] = None
    r"""JSON-encoded event payload.
    Shape depends on `event`.

    """

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["event", "data"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
