"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .storedagentconversation import (
    StoredAgentConversation,
    StoredAgentConversationTypedDict,
)
from pipeshub_sdk.types import BaseModel
from typing import Literal
from typing_extensions import TypedDict


MessageEnum = Literal["Conversation deleted successfully",]


class AgentConversationDeleteResponseTypedDict(TypedDict):
    r"""Envelope returned by `DELETE /agents/{agentKey}/conversations/{conversationId}`.
    When the conversation does not exist, belongs to a different agent, or
    was already deleted, the API still returns HTTP 200 with
    `conversation: null`.

    """

    message: MessageEnum
    conversation: StoredAgentConversationTypedDict
    r"""Stored agent conversation document returned by non-list endpoints.

    """


class AgentConversationDeleteResponse(BaseModel):
    r"""Envelope returned by `DELETE /agents/{agentKey}/conversations/{conversationId}`.
    When the conversation does not exist, belongs to a different agent, or
    was already deleted, the API still returns HTTP 200 with
    `conversation: null`.

    """

    message: MessageEnum

    conversation: StoredAgentConversation
    r"""Stored agent conversation document returned by non-list endpoints.

    """
