"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pipeshub_sdk.types import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class AgentCapabilitiesTypedDict(TypedDict):
    r"""Per-request agent capability toggles. Only meaningful when `chatMode`
    selects an agent mode; ignored otherwise. Each field falls back to its
    own `default` below when omitted — a missing flag is not uniformly
    `true`. Omitting the whole object applies every default.

    """

    internal_search: NotRequired[bool]
    r"""Whether the agent may search internal knowledge bases for this turn."""
    web_search: NotRequired[bool]
    r"""Whether the agent may perform web search for this turn."""
    deep_search: NotRequired[bool]
    r"""Whether the agent may use deeper, higher-latency retrieval for this turn."""


class AgentCapabilities(BaseModel):
    r"""Per-request agent capability toggles. Only meaningful when `chatMode`
    selects an agent mode; ignored otherwise. Each field falls back to its
    own `default` below when omitted — a missing flag is not uniformly
    `true`. Omitting the whole object applies every default.

    """

    internal_search: Annotated[
        Optional[bool], pydantic.Field(alias="internalSearch")
    ] = True
    r"""Whether the agent may search internal knowledge bases for this turn."""

    web_search: Annotated[Optional[bool], pydantic.Field(alias="webSearch")] = True
    r"""Whether the agent may perform web search for this turn."""

    deep_search: Annotated[Optional[bool], pydantic.Field(alias="deepSearch")] = False
    r"""Whether the agent may use deeper, higher-latency retrieval for this turn."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["internalSearch", "webSearch", "deepSearch"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    AgentCapabilities.model_rebuild()
except NameError:
    pass
