"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: 7db707718f47

from __future__ import annotations
from typing import Literal


AppType = Literal[
    "drive",
    "gmail",
    "onedrive",
    "sharepointOnline",
    "bookstack",
    "confluence",
    "jira",
    "slack",
    "dropbox",
    "outlook",
    "servicenow",
    "web",
    "local",
]
r"""Supported application/connector types"""
