"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import datetime
from pipeshub_sdk.types import BaseModel, UNSET_SENTINEL
from pipeshub_sdk.utils import FieldMetadata, PathParamMetadata
import pydantic
from pydantic import model_serializer
from typing import Literal, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class ArchiveConversationRequestTypedDict(TypedDict):
    conversation_id: str
    r"""Conversation identifier"""


class ArchiveConversationRequest(BaseModel):
    conversation_id: Annotated[
        str,
        pydantic.Field(alias="conversationId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""Conversation identifier"""


ArchiveConversationStatus = Literal["archived",]
r"""New archive status of the conversation"""


class ArchiveConversationMetaTypedDict(TypedDict):
    request_id: NotRequired[str]
    r"""Request correlation identifier"""
    timestamp: NotRequired[datetime]
    r"""Response generation timestamp"""
    duration: NotRequired[int]
    r"""Server processing time in milliseconds"""


class ArchiveConversationMeta(BaseModel):
    request_id: Annotated[Optional[str], pydantic.Field(alias="requestId")] = None
    r"""Request correlation identifier"""

    timestamp: Optional[datetime] = None
    r"""Response generation timestamp"""

    duration: Optional[int] = None
    r"""Server processing time in milliseconds"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["requestId", "timestamp", "duration"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class ArchiveConversationResponseTypedDict(TypedDict):
    r"""Conversation archived successfully"""

    id: NotRequired[str]
    r"""Conversation identifier"""
    status: NotRequired[ArchiveConversationStatus]
    r"""New archive status of the conversation"""
    archived_by: NotRequired[str]
    r"""User who archived the conversation"""
    archived_at: NotRequired[datetime]
    r"""Timestamp when the conversation was archived"""
    meta: NotRequired[ArchiveConversationMetaTypedDict]


class ArchiveConversationResponse(BaseModel):
    r"""Conversation archived successfully"""

    id: Optional[str] = None
    r"""Conversation identifier"""

    status: Optional[ArchiveConversationStatus] = None
    r"""New archive status of the conversation"""

    archived_by: Annotated[Optional[str], pydantic.Field(alias="archivedBy")] = None
    r"""User who archived the conversation"""

    archived_at: Annotated[Optional[datetime], pydantic.Field(alias="archivedAt")] = (
        None
    )
    r"""Timestamp when the conversation was archived"""

    meta: Optional[ArchiveConversationMeta] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["id", "status", "archivedBy", "archivedAt", "meta"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    ArchiveConversationMeta.model_rebuild()
except NameError:
    pass
try:
    ArchiveConversationResponse.model_rebuild()
except NameError:
    pass
