"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: dc1f8367d3c8

from __future__ import annotations
from pipeshub_sdk.types import BaseModel
from pipeshub_sdk.utils import FieldMetadata, PathParamMetadata, RequestMetadata
import pydantic
from typing import Any, Dict
from typing_extensions import Annotated, TypedDict


class AuthenticateAgentToolsetRequestTypedDict(TypedDict):
    agent_key: str
    instance_id: str
    body: Dict[str, Any]


class AuthenticateAgentToolsetRequest(BaseModel):
    agent_key: Annotated[
        str,
        pydantic.Field(alias="agentKey"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]

    instance_id: Annotated[
        str,
        pydantic.Field(alias="instanceId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]

    body: Annotated[
        Dict[str, Any],
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
