"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .chatattachmentuploadref import (
    ChatAttachmentUploadRef,
    ChatAttachmentUploadRefTypedDict,
)
from pipeshub_sdk.types import BaseModel, Nullable, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import List
from typing_extensions import Annotated, TypedDict


class ChatAttachmentUploadResponseTypedDict(TypedDict):
    r"""Success envelope returned by `POST /conversations/attachments/upload`
    and `POST /agents/{agentKey}/conversations/attachments/upload`.

    """

    conversation_id: Nullable[str]
    r"""Existing conversation id echoed from the request when the upload is tied to a thread; otherwise `null`.

    """
    attachments: List[ChatAttachmentUploadRefTypedDict]


class ChatAttachmentUploadResponse(BaseModel):
    r"""Success envelope returned by `POST /conversations/attachments/upload`
    and `POST /agents/{agentKey}/conversations/attachments/upload`.

    """

    conversation_id: Annotated[Nullable[str], pydantic.Field(alias="conversationId")]
    r"""Existing conversation id echoed from the request when the upload is tied to a thread; otherwise `null`.

    """

    attachments: List[ChatAttachmentUploadRef]

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                m[k] = val

        return m


try:
    ChatAttachmentUploadResponse.model_rebuild()
except NameError:
    pass
