"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pipeshub_sdk.types import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class ChatAttachmentUploadRefTypedDict(TypedDict):
    r"""Concrete attachment metadata returned by `POST /conversations/attachments/upload`
    (or the equivalent agent route).

    """

    record_id: str
    r"""Server-assigned attachment record id."""
    record_name: str
    r"""Original filename stored for the attachment."""
    mime_type: str
    r"""MIME type of the uploaded file."""
    extension: str
    r"""File extension derived by the backend."""
    virtual_record_id: str
    r"""Synthetic record id used by the graph layer."""
    ocr_mode: NotRequired[str]
    r"""Optional backend-reported processing mode for the attachment."""


class ChatAttachmentUploadRef(BaseModel):
    r"""Concrete attachment metadata returned by `POST /conversations/attachments/upload`
    (or the equivalent agent route).

    """

    record_id: Annotated[str, pydantic.Field(alias="recordId")]
    r"""Server-assigned attachment record id."""

    record_name: Annotated[str, pydantic.Field(alias="recordName")]
    r"""Original filename stored for the attachment."""

    mime_type: Annotated[str, pydantic.Field(alias="mimeType")]
    r"""MIME type of the uploaded file."""

    extension: str
    r"""File extension derived by the backend."""

    virtual_record_id: Annotated[str, pydantic.Field(alias="virtualRecordId")]
    r"""Synthetic record id used by the graph layer."""

    ocr_mode: Annotated[Optional[str], pydantic.Field(alias="ocrMode")] = None
    r"""Optional backend-reported processing mode for the attachment."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["ocrMode"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    ChatAttachmentUploadRef.model_rebuild()
except NameError:
    pass
