"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: c9b7114fa78d

from __future__ import annotations
from .connectorauthtype import ConnectorAuthType
from .connectorscope import ConnectorScope
from pipeshub_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
import pydantic
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class AuthTypedDict(TypedDict):
    r"""Authentication configuration"""


class Auth(BaseModel):
    r"""Authentication configuration"""


class ConnectorConfigSyncTypedDict(TypedDict):
    r"""Sync configuration"""


class ConnectorConfigSync(BaseModel):
    r"""Sync configuration"""


class ConnectorConfigFiltersTypedDict(TypedDict):
    r"""Filter configuration"""


class ConnectorConfigFilters(BaseModel):
    r"""Filter configuration"""


class ConnectorConfigCredentialsTypedDict(TypedDict):
    r"""Credential details"""


class ConnectorConfigCredentials(BaseModel):
    r"""Credential details"""


class ConnectorConfigOauthTypedDict(TypedDict):
    r"""OAuth configuration"""


class ConnectorConfigOauth(BaseModel):
    r"""OAuth configuration"""


class ConnectorConfigTypedDict(TypedDict):
    r"""Configuration for a connector instance including auth, sync, and filter settings"""

    connector_id: NotRequired[str]
    r"""Connector instance ID"""
    connector_type: NotRequired[str]
    r"""Connector type"""
    instance_name: NotRequired[str]
    r"""Instance name"""
    auth_type: NotRequired[ConnectorAuthType]
    r"""Authentication method required by the connector:<br>
    <ul>
    <li><code>OAUTH</code> - User OAuth consent flow</li>
    <li><code>OAUTH_ADMIN_CONSENT</code> - Admin OAuth with org-wide consent</li>
    <li><code>API_TOKEN</code> - API key or token authentication</li>
    <li><code>USERNAME_PASSWORD</code> - Username/password credentials</li>
    <li><code>BASIC_AUTH</code> - Basic authentication (username/password)</li>
    <li><code>NONE</code> - No authentication required</li>
    </ul>

    """
    scope: NotRequired[ConnectorScope]
    r"""Scope determines visibility and access control for connectors:<br>
    <ul>
    <li><code>team</code> - Available to all users in the organization (admin-only creation)</li>
    <li><code>personal</code> - Private to the creating user only</li>
    </ul>

    """
    auth: NotRequired[AuthTypedDict]
    r"""Authentication configuration"""
    sync: NotRequired[ConnectorConfigSyncTypedDict]
    r"""Sync configuration"""
    filters: NotRequired[ConnectorConfigFiltersTypedDict]
    r"""Filter configuration"""
    credentials: NotRequired[Nullable[ConnectorConfigCredentialsTypedDict]]
    r"""Credential details"""
    oauth: NotRequired[Nullable[ConnectorConfigOauthTypedDict]]
    r"""OAuth configuration"""
    base_url: NotRequired[str]
    r"""Base URL for self-hosted instances"""
    is_active: NotRequired[bool]
    is_configured: NotRequired[bool]
    is_authenticated: NotRequired[bool]


class ConnectorConfig(BaseModel):
    r"""Configuration for a connector instance including auth, sync, and filter settings"""

    connector_id: Annotated[Optional[str], pydantic.Field(alias="connectorId")] = None
    r"""Connector instance ID"""

    connector_type: Annotated[Optional[str], pydantic.Field(alias="connectorType")] = (
        None
    )
    r"""Connector type"""

    instance_name: Annotated[Optional[str], pydantic.Field(alias="instanceName")] = None
    r"""Instance name"""

    auth_type: Annotated[
        Optional[ConnectorAuthType], pydantic.Field(alias="authType")
    ] = None
    r"""Authentication method required by the connector:<br>
    <ul>
    <li><code>OAUTH</code> - User OAuth consent flow</li>
    <li><code>OAUTH_ADMIN_CONSENT</code> - Admin OAuth with org-wide consent</li>
    <li><code>API_TOKEN</code> - API key or token authentication</li>
    <li><code>USERNAME_PASSWORD</code> - Username/password credentials</li>
    <li><code>BASIC_AUTH</code> - Basic authentication (username/password)</li>
    <li><code>NONE</code> - No authentication required</li>
    </ul>

    """

    scope: Optional[ConnectorScope] = None
    r"""Scope determines visibility and access control for connectors:<br>
    <ul>
    <li><code>team</code> - Available to all users in the organization (admin-only creation)</li>
    <li><code>personal</code> - Private to the creating user only</li>
    </ul>

    """

    auth: Optional[Auth] = None
    r"""Authentication configuration"""

    sync: Optional[ConnectorConfigSync] = None
    r"""Sync configuration"""

    filters: Optional[ConnectorConfigFilters] = None
    r"""Filter configuration"""

    credentials: OptionalNullable[ConnectorConfigCredentials] = UNSET
    r"""Credential details"""

    oauth: OptionalNullable[ConnectorConfigOauth] = UNSET
    r"""OAuth configuration"""

    base_url: Annotated[Optional[str], pydantic.Field(alias="baseUrl")] = None
    r"""Base URL for self-hosted instances"""

    is_active: Annotated[Optional[bool], pydantic.Field(alias="isActive")] = None

    is_configured: Annotated[Optional[bool], pydantic.Field(alias="isConfigured")] = (
        None
    )

    is_authenticated: Annotated[
        Optional[bool], pydantic.Field(alias="isAuthenticated")
    ] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "connectorId",
                "connectorType",
                "instanceName",
                "authType",
                "scope",
                "auth",
                "sync",
                "filters",
                "credentials",
                "oauth",
                "baseUrl",
                "isActive",
                "isConfigured",
                "isAuthenticated",
            ]
        )
        nullable_fields = set(["credentials", "oauth"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


try:
    ConnectorConfig.model_rebuild()
except NameError:
    pass
