"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .project import Project, ProjectTypedDict
from pipeshub_sdk.types import BaseModel
from typing_extensions import TypedDict


class CreateProjectResponseTypedDict(TypedDict):
    r"""Project created"""

    project: ProjectTypedDict
    r"""A workspace that groups related assistant and agent conversations
    under a shared name, instructions, knowledge scope, tool
    selection, and its own hidden Collection of uploaded files. See
    the `Projects` tag description for the sharing model.

    """


class CreateProjectResponse(BaseModel):
    r"""Project created"""

    project: Project
    r"""A workspace that groups related assistant and agent conversations
    under a shared name, instructions, knowledge scope, tool
    selection, and its own hidden Collection of uploaded files. See
    the `Projects` tag description for the sharing model.

    """
