"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pipeshub_sdk.types import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import List, Literal, Optional, Union
from typing_extensions import Annotated, NotRequired, TypeAliasType, TypedDict


ExpiryDaysNever = Literal["never",]


ExpiryDaysEnum = Literal[
    30,
    90,
    365,
]


ExpiryDaysTypedDict = TypeAliasType(
    "ExpiryDaysTypedDict", Union[ExpiryDaysEnum, ExpiryDaysNever]
)
r"""Token lifetime. Defaults to `30` if omitted — a token minted
without an explicit choice shouldn't default to the longest
lifetime. `\"never\"` is stored as a ~100-year expiry (the
underlying schema field is required and TTL-indexed, so there's
no literal null option).

"""


ExpiryDays = TypeAliasType("ExpiryDays", Union[ExpiryDaysEnum, ExpiryDaysNever])
r"""Token lifetime. Defaults to `30` if omitted — a token minted
without an explicit choice shouldn't default to the longest
lifetime. `\"never\"` is stored as a ~100-year expiry (the
underlying schema field is required and TTL-indexed, so there's
no literal null option).

"""


class CreatePatRequestTypedDict(TypedDict):
    r"""Request to create a personal access token (`createPatTokenSchema` in `pat.validators.ts`)."""

    name: str
    r"""Label to help you recognize the token later"""
    scopes: NotRequired[List[str]]
    r"""Scopes to grant, validated against the org's configured `MCP_SCOPES`
    (not the full role-aware OAuth-app scope set). Defaults to every
    scope in `MCP_SCOPES` if omitted.

    """
    expiry_days: NotRequired[ExpiryDaysTypedDict]
    r"""Token lifetime. Defaults to `30` if omitted — a token minted
    without an explicit choice shouldn't default to the longest
    lifetime. `\"never\"` is stored as a ~100-year expiry (the
    underlying schema field is required and TTL-indexed, so there's
    no literal null option).

    """


class CreatePatRequest(BaseModel):
    r"""Request to create a personal access token (`createPatTokenSchema` in `pat.validators.ts`)."""

    name: str
    r"""Label to help you recognize the token later"""

    scopes: Optional[List[str]] = None
    r"""Scopes to grant, validated against the org's configured `MCP_SCOPES`
    (not the full role-aware OAuth-app scope set). Defaults to every
    scope in `MCP_SCOPES` if omitted.

    """

    expiry_days: Annotated[Optional[ExpiryDays], pydantic.Field(alias="expiryDays")] = (
        None
    )
    r"""Token lifetime. Defaults to `30` if omitted — a token minted
    without an explicit choice shouldn't default to the longest
    lifetime. `\"never\"` is stored as a ~100-year expiry (the
    underlying schema field is required and TTL-indexed, so there's
    no literal null option).

    """

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["scopes", "expiryDays"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    CreatePatRequest.model_rebuild()
except NameError:
    pass
