"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .appliedfilters import AppliedFilters, AppliedFiltersTypedDict
from .chatattachmentref import ChatAttachmentRef, ChatAttachmentRefTypedDict
from .filters import Filters, FiltersTypedDict
from datetime import datetime
from pipeshub_sdk.types import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import List, Literal, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


CreateConversationRequestChatMode = Literal[
    "web_search",
    "internal_search",
]
r"""Chat mode affecting response behavior.

"""


class CreateConversationRequestTypedDict(TypedDict):
    r"""Request body for creating a new AI conversation.

    **Query Processing:**

    The query is processed through PipesHub's AI pipeline which:

    - Performs semantic search across indexed knowledge bases
    - Retrieves relevant context from matching documents
    - Generates a response with citations to source materials
    - Suggests follow-up questions based on the conversation

    """

    query: str
    r"""The user's question or prompt to start the conversation.
    Supports natural language queries of any complexity.

    """
    record_ids: NotRequired[List[str]]
    r"""Limit the AI's knowledge scope to specific records/documents.
    When provided, only these records will be searched for context.

    """
    filters: NotRequired[FiltersTypedDict]
    r"""App connector instance ids and knowledge-base / record-group ids that narrow retrieval
    for a turn. For **org assistant** chat streams, send explicit `apps` / `kb` lists.
    For **agent** chat streams, send explicit id lists, or **omit** `filters` (and `tools`)
    to let the service use the agent’s stored knowledge and tool configuration. Sending
    `{ \"apps\": [], \"kb\": [] }` on an agent stream means **no** knowledge sources for that
    turn (it is not “full org default”).

    """
    applied_filters: NotRequired[AppliedFiltersTypedDict]
    r"""Rich filter state selected by the user, used for display and persistence only.
    This mirrors the active selection shown in the UI and is distinct from the
    machine-readable `filters` field used for retrieval scoping.

    """
    attachments: NotRequired[List[ChatAttachmentRefTypedDict]]
    r"""Uploaded chat attachments to associate with this conversation turn (see
    `POST /conversations/attachments/upload`).

    """
    model_key: NotRequired[str]
    r"""Identifier for the AI model configuration to use.
    Available models depend on organization settings.

    """
    model_name: NotRequired[str]
    r"""Display name of the AI model"""
    model_friendly_name: NotRequired[str]
    r"""Friendly display name of the selected model"""
    chat_mode: NotRequired[CreateConversationRequestChatMode]
    r"""Chat mode affecting response behavior.

    """
    timezone: NotRequired[str]
    r"""IANA timezone identifier from the client (top-level field).
    Used to provide time-aware context to the AI.

    """
    current_time: NotRequired[datetime]
    r"""ISO 8601 / RFC 3339 datetime from the client (top-level field; UTC `Z` or numeric offset).

    """
    tools: NotRequired[List[str]]
    r"""Optional list of tool identifiers (fully-qualified action names such as
    \"jira.create_issue\") that the AI agent is permitted to invoke for this
    request. When omitted the agent may use any configured tool. Applicable
    only when chatMode is an agent mode (e.g. \"agent:auto\").

    """


class CreateConversationRequest(BaseModel):
    r"""Request body for creating a new AI conversation.

    **Query Processing:**

    The query is processed through PipesHub's AI pipeline which:

    - Performs semantic search across indexed knowledge bases
    - Retrieves relevant context from matching documents
    - Generates a response with citations to source materials
    - Suggests follow-up questions based on the conversation

    """

    query: str
    r"""The user's question or prompt to start the conversation.
    Supports natural language queries of any complexity.

    """

    record_ids: Annotated[Optional[List[str]], pydantic.Field(alias="recordIds")] = None
    r"""Limit the AI's knowledge scope to specific records/documents.
    When provided, only these records will be searched for context.

    """

    filters: Optional[Filters] = None
    r"""App connector instance ids and knowledge-base / record-group ids that narrow retrieval
    for a turn. For **org assistant** chat streams, send explicit `apps` / `kb` lists.
    For **agent** chat streams, send explicit id lists, or **omit** `filters` (and `tools`)
    to let the service use the agent’s stored knowledge and tool configuration. Sending
    `{ \"apps\": [], \"kb\": [] }` on an agent stream means **no** knowledge sources for that
    turn (it is not “full org default”).

    """

    applied_filters: Annotated[
        Optional[AppliedFilters], pydantic.Field(alias="appliedFilters")
    ] = None
    r"""Rich filter state selected by the user, used for display and persistence only.
    This mirrors the active selection shown in the UI and is distinct from the
    machine-readable `filters` field used for retrieval scoping.

    """

    attachments: Optional[List[ChatAttachmentRef]] = None
    r"""Uploaded chat attachments to associate with this conversation turn (see
    `POST /conversations/attachments/upload`).

    """

    model_key: Annotated[Optional[str], pydantic.Field(alias="modelKey")] = None
    r"""Identifier for the AI model configuration to use.
    Available models depend on organization settings.

    """

    model_name: Annotated[Optional[str], pydantic.Field(alias="modelName")] = None
    r"""Display name of the AI model"""

    model_friendly_name: Annotated[
        Optional[str], pydantic.Field(alias="modelFriendlyName")
    ] = None
    r"""Friendly display name of the selected model"""

    chat_mode: Annotated[
        Optional[CreateConversationRequestChatMode], pydantic.Field(alias="chatMode")
    ] = None
    r"""Chat mode affecting response behavior.

    """

    timezone: Optional[str] = None
    r"""IANA timezone identifier from the client (top-level field).
    Used to provide time-aware context to the AI.

    """

    current_time: Annotated[Optional[datetime], pydantic.Field(alias="currentTime")] = (
        None
    )
    r"""ISO 8601 / RFC 3339 datetime from the client (top-level field; UTC `Z` or numeric offset).

    """

    tools: Optional[List[str]] = None
    r"""Optional list of tool identifiers (fully-qualified action names such as
    \"jira.create_issue\") that the AI agent is permitted to invoke for this
    request. When omitted the agent may use any configured tool. Applicable
    only when chatMode is an agent mode (e.g. \"agent:auto\").

    """

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "recordIds",
                "filters",
                "appliedFilters",
                "attachments",
                "modelKey",
                "modelName",
                "modelFriendlyName",
                "chatMode",
                "timezone",
                "currentTime",
                "tools",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    CreateConversationRequest.model_rebuild()
except NameError:
    pass
