"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import datetime
from pipeshub_sdk.types import BaseModel, UNSET_SENTINEL
from pipeshub_sdk.utils import FieldMetadata, PathParamMetadata, QueryParamMetadata
import pydantic
from pydantic import model_serializer
from typing import Literal, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


DeleteSearchByIDShared = Literal[
    "true",
    "false",
]
r"""Additional `isShared` filter (`'true'` / `'false'`). The row is
only deleted if it also matches this value.

"""


class DeleteSearchByIDRequestTypedDict(TypedDict):
    search_id: str
    r"""ObjectId of the persisted search row to delete."""
    search: NotRequired[str]
    r"""Additional substring filter against `title` / `messages.content`.
    The row is only deleted if the `searchId` row also matches this
    filter; otherwise `404`. Special regex characters are escaped;
    values over 1000 chars or tripping the XSS guard yield `400`.

    """
    shared: NotRequired[DeleteSearchByIDShared]
    r"""Additional `isShared` filter (`'true'` / `'false'`). The row is
    only deleted if it also matches this value.

    """
    start_date: NotRequired[datetime]
    r"""ISO 8601 lower bound for `createdAt`. The row is only deleted
    if its `createdAt` is on or after this value.

    """
    end_date: NotRequired[datetime]
    r"""ISO 8601 upper bound for `createdAt`. The row is only deleted
    if its `createdAt` is on or before this value.

    """


class DeleteSearchByIDRequest(BaseModel):
    search_id: Annotated[
        str,
        pydantic.Field(alias="searchId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""ObjectId of the persisted search row to delete."""

    search: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Additional substring filter against `title` / `messages.content`.
    The row is only deleted if the `searchId` row also matches this
    filter; otherwise `404`. Special regex characters are escaped;
    values over 1000 chars or tripping the XSS guard yield `400`.

    """

    shared: Annotated[
        Optional[DeleteSearchByIDShared],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Additional `isShared` filter (`'true'` / `'false'`). The row is
    only deleted if it also matches this value.

    """

    start_date: Annotated[
        Optional[datetime],
        pydantic.Field(alias="startDate"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""ISO 8601 lower bound for `createdAt`. The row is only deleted
    if its `createdAt` is on or after this value.

    """

    end_date: Annotated[
        Optional[datetime],
        pydantic.Field(alias="endDate"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""ISO 8601 upper bound for `createdAt`. The row is only deleted
    if its `createdAt` is on or before this value.

    """

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["search", "shared", "startDate", "endDate"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class DeleteSearchByIDResponseTypedDict(TypedDict):
    r"""Search deleted successfully."""

    message: str


class DeleteSearchByIDResponse(BaseModel):
    r"""Search deleted successfully."""

    message: str
