"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: 1fd02f899cd3

from __future__ import annotations
from pipeshub_sdk.types import BaseModel
from pipeshub_sdk.utils import FieldMetadata, PathParamMetadata
import pydantic
from typing_extensions import Annotated, TypedDict


class DeleteAgentRequestTypedDict(TypedDict):
    agent_key: str


class DeleteAgentRequest(BaseModel):
    agent_key: Annotated[
        str,
        pydantic.Field(alias="agentKey"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
