"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pipeshub_sdk.types import BaseModel
from typing_extensions import TypedDict


class DeleteKnowledgeBaseByIDTypedDict(TypedDict):
    r"""Response returned by DELETE /knowledgeBase/{kbId} (deleteKnowledgeBase)."""

    success: bool
    message: str


class DeleteKnowledgeBaseByID(BaseModel):
    r"""Response returned by DELETE /knowledgeBase/{kbId} (deleteKnowledgeBase)."""

    success: bool

    message: str
