"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pipeshub_sdk.types import BaseModel
from pipeshub_sdk.utils import FieldMetadata, PathParamMetadata
import pydantic
from typing_extensions import Annotated, TypedDict


class EnsureProjectKnowledgeBaseRequestTypedDict(TypedDict):
    project_id: str


class EnsureProjectKnowledgeBaseRequest(BaseModel):
    project_id: Annotated[
        str,
        pydantic.Field(alias="projectId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]


class EnsureProjectKnowledgeBaseResponseTypedDict(TypedDict):
    r"""The project's linked Collection id (existing or newly created)"""

    kb_id: str


class EnsureProjectKnowledgeBaseResponse(BaseModel):
    r"""The project's linked Collection id (existing or newly created)"""

    kb_id: Annotated[str, pydantic.Field(alias="kbId")]


try:
    EnsureProjectKnowledgeBaseResponse.model_rebuild()
except NameError:
    pass
