"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pipeshub_sdk.types import BaseModel
from typing_extensions import TypedDict


class FolderDeleteResponseSchemaTypedDict(TypedDict):
    r"""Response returned by DELETE /knowledgeBase/{kbId}/folder/{folderId} (deleteFolder)."""

    success: bool
    message: str


class FolderDeleteResponseSchema(BaseModel):
    r"""Response returned by DELETE /knowledgeBase/{kbId}/folder/{folderId} (deleteFolder)."""

    success: bool

    message: str
