"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pipeshub_sdk.types import BaseModel
from typing_extensions import TypedDict


class FolderUpdateResponseSchemaTypedDict(TypedDict):
    r"""Response returned by PUT /knowledgeBase/{kbId}/folder/{folderId} (updateFolder)."""

    success: bool
    message: str


class FolderUpdateResponseSchema(BaseModel):
    r"""Response returned by PUT /knowledgeBase/{kbId}/folder/{folderId} (updateFolder)."""

    success: bool

    message: str
