"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: 94edfa6c223e

from __future__ import annotations
from pipeshub_sdk.types import BaseModel
from typing_extensions import TypedDict


class GetAIModelsProvidersResponseTypedDict(TypedDict):
    r"""AI model providers retrieved"""


class GetAIModelsProvidersResponse(BaseModel):
    r"""AI model providers retrieved"""
