"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: 081818273a44

from __future__ import annotations
from .agentconversation import AgentConversation, AgentConversationTypedDict
from .conversationfilters import ConversationFilters, ConversationFiltersTypedDict
from datetime import datetime
from pipeshub_sdk.types import BaseModel, UNSET_SENTINEL
from pipeshub_sdk.utils import FieldMetadata, PathParamMetadata
import pydantic
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class GetAgentConversationRequestTypedDict(TypedDict):
    agent_key: str
    conversation_id: str


class GetAgentConversationRequest(BaseModel):
    agent_key: Annotated[
        str,
        pydantic.Field(alias="agentKey"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]

    conversation_id: Annotated[
        str,
        pydantic.Field(alias="conversationId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]


class GetAgentConversationMetaTypedDict(TypedDict):
    request_id: NotRequired[str]
    timestamp: NotRequired[datetime]
    duration: NotRequired[int]
    conversation_id: NotRequired[str]
    message_count: NotRequired[int]


class GetAgentConversationMeta(BaseModel):
    request_id: Annotated[Optional[str], pydantic.Field(alias="requestId")] = None

    timestamp: Optional[datetime] = None

    duration: Optional[int] = None

    conversation_id: Annotated[
        Optional[str], pydantic.Field(alias="conversationId")
    ] = None

    message_count: Annotated[Optional[int], pydantic.Field(alias="messageCount")] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["requestId", "timestamp", "duration", "conversationId", "messageCount"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class GetAgentConversationResponseTypedDict(TypedDict):
    r"""Agent conversation details"""

    conversation: NotRequired[AgentConversationTypedDict]
    r"""A conversation with a specific AI agent (full detail with messages).

    """
    filters: NotRequired[ConversationFiltersTypedDict]
    r"""Applied and available filters for conversation endpoints"""
    meta: NotRequired[GetAgentConversationMetaTypedDict]


class GetAgentConversationResponse(BaseModel):
    r"""Agent conversation details"""

    conversation: Optional[AgentConversation] = None
    r"""A conversation with a specific AI agent (full detail with messages).

    """

    filters: Optional[ConversationFilters] = None
    r"""Applied and available filters for conversation endpoints"""

    meta: Optional[GetAgentConversationMeta] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["conversation", "filters", "meta"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    GetAgentConversationMeta.model_rebuild()
except NameError:
    pass
