"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .conversationlistitem import ConversationListItem, ConversationListItemTypedDict
from datetime import datetime
from pipeshub_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
    UnrecognizedStr,
)
from pipeshub_sdk.utils import FieldMetadata, QueryParamMetadata
import pydantic
from pydantic import model_serializer
from typing import List, Literal, Optional, Union
from typing_extensions import Annotated, NotRequired, TypedDict


QueryParamSource = Literal[
    "owned",
    "shared",
]
r"""`owned` — owner list (`userId` filter only).
`shared` — explicit share grant list (`isShared` + `sharedWith`).
Defaults to `owned` when omitted.

"""


GetAllConversationsSortByEnum = Literal[
    "createdAt",
    "lastActivityAt",
    "title",
]
r"""Sort field. Invalid values fall back to `lastActivityAt`."""


GetAllConversationsSortOrderEnum = Literal[
    "asc",
    "desc",
]
r"""Sort direction. Defaults to `desc` unless set to `asc`."""


class GetAllConversationsRequestTypedDict(TypedDict):
    source: NotRequired[QueryParamSource]
    r"""`owned` — owner list (`userId` filter only).
    `shared` — explicit share grant list (`isShared` + `sharedWith`).
    Defaults to `owned` when omitted.

    """
    page: NotRequired[int]
    r"""Page number (1-based). Defaults to 1."""
    limit: NotRequired[int]
    r"""Page size. Defaults to 20; capped by the server (max 100)."""
    sort_by: NotRequired[GetAllConversationsSortByEnum]
    r"""Sort field. Invalid values fall back to `lastActivityAt`."""
    sort_order: NotRequired[GetAllConversationsSortOrderEnum]
    r"""Sort direction. Defaults to `desc` unless set to `asc`."""
    conversation_id: NotRequired[str]
    r"""When set, restricts results to that conversation ID (if visible under the chosen `source`)."""
    search: NotRequired[str]
    r"""Case-insensitive match on title and message content (max 1000 characters)."""
    start_date: NotRequired[datetime]
    r"""Filter by `createdAt` ≥ this ISO date."""
    end_date: NotRequired[datetime]
    r"""Filter by `createdAt` ≤ this ISO date."""
    shared: NotRequired[str]
    r"""When set, filters by `isShared`. Accepts case-insensitive
    `true`/`false`, or `1`/`0`.

    """


class GetAllConversationsRequest(BaseModel):
    source: Annotated[
        Optional[QueryParamSource],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = "owned"
    r"""`owned` — owner list (`userId` filter only).
    `shared` — explicit share grant list (`isShared` + `sharedWith`).
    Defaults to `owned` when omitted.

    """

    page: Annotated[
        Optional[int],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Page number (1-based). Defaults to 1."""

    limit: Annotated[
        Optional[int],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Page size. Defaults to 20; capped by the server (max 100)."""

    sort_by: Annotated[
        Optional[GetAllConversationsSortByEnum],
        pydantic.Field(alias="sortBy"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Sort field. Invalid values fall back to `lastActivityAt`."""

    sort_order: Annotated[
        Optional[GetAllConversationsSortOrderEnum],
        pydantic.Field(alias="sortOrder"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Sort direction. Defaults to `desc` unless set to `asc`."""

    conversation_id: Annotated[
        Optional[str],
        pydantic.Field(alias="conversationId"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""When set, restricts results to that conversation ID (if visible under the chosen `source`)."""

    search: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Case-insensitive match on title and message content (max 1000 characters)."""

    start_date: Annotated[
        Optional[datetime],
        pydantic.Field(alias="startDate"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Filter by `createdAt` ≥ this ISO date."""

    end_date: Annotated[
        Optional[datetime],
        pydantic.Field(alias="endDate"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Filter by `createdAt` ≤ this ISO date."""

    shared: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""When set, filters by `isShared`. Accepts case-insensitive
    `true`/`false`, or `1`/`0`.

    """

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "source",
                "page",
                "limit",
                "sortBy",
                "sortOrder",
                "conversationId",
                "search",
                "startDate",
                "endDate",
                "shared",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


GetAllConversationsSourceResponse = Union[
    Literal[
        "owned",
        "shared",
    ],
    UnrecognizedStr,
]
r"""Echoes the requested `source` query value."""


class GetAllConversationsPaginationTypedDict(TypedDict):
    page: NotRequired[int]
    limit: NotRequired[int]
    total_count: NotRequired[int]
    total_pages: NotRequired[int]
    has_next_page: NotRequired[bool]
    has_prev_page: NotRequired[bool]


class GetAllConversationsPagination(BaseModel):
    page: Optional[int] = None

    limit: Optional[int] = None

    total_count: Annotated[Optional[int], pydantic.Field(alias="totalCount")] = None

    total_pages: Annotated[Optional[int], pydantic.Field(alias="totalPages")] = None

    has_next_page: Annotated[Optional[bool], pydantic.Field(alias="hasNextPage")] = None

    has_prev_page: Annotated[Optional[bool], pydantic.Field(alias="hasPrevPage")] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["page", "limit", "totalCount", "totalPages", "hasNextPage", "hasPrevPage"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class ValuesDateRangeTypedDict(TypedDict):
    start: NotRequired[Nullable[str]]
    end: NotRequired[Nullable[str]]


class ValuesDateRange(BaseModel):
    start: OptionalNullable[str] = UNSET

    end: OptionalNullable[str] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["start", "end"])
        nullable_fields = set(["start", "end"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


class GetAllConversationsValuesTypedDict(TypedDict):
    r"""Current value for each applied filter. Only keys
    present in `filters` are populated; others are
    omitted.

    """

    search: NotRequired[str]
    shared: NotRequired[str]
    tags: NotRequired[str]
    min_messages: NotRequired[str]
    sort_by: NotRequired[str]
    sort_order: NotRequired[str]
    start_date: NotRequired[str]
    end_date: NotRequired[str]
    message_type: NotRequired[str]
    page: NotRequired[int]
    limit: NotRequired[int]
    date_range: NotRequired[ValuesDateRangeTypedDict]


class GetAllConversationsValues(BaseModel):
    r"""Current value for each applied filter. Only keys
    present in `filters` are populated; others are
    omitted.

    """

    search: Optional[str] = None

    shared: Optional[str] = None

    tags: Optional[str] = None

    min_messages: Annotated[Optional[str], pydantic.Field(alias="minMessages")] = None

    sort_by: Annotated[Optional[str], pydantic.Field(alias="sortBy")] = None

    sort_order: Annotated[Optional[str], pydantic.Field(alias="sortOrder")] = None

    start_date: Annotated[Optional[str], pydantic.Field(alias="startDate")] = None

    end_date: Annotated[Optional[str], pydantic.Field(alias="endDate")] = None

    message_type: Annotated[Optional[str], pydantic.Field(alias="messageType")] = None

    page: Optional[int] = None

    limit: Optional[int] = None

    date_range: Annotated[
        Optional[ValuesDateRange], pydantic.Field(alias="dateRange")
    ] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "search",
                "shared",
                "tags",
                "minMessages",
                "sortBy",
                "sortOrder",
                "startDate",
                "endDate",
                "messageType",
                "page",
                "limit",
                "dateRange",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class GetAllConversationsAppliedTypedDict(TypedDict):
    filters: List[str]
    r"""Names of filters currently applied."""
    values: GetAllConversationsValuesTypedDict
    r"""Current value for each applied filter. Only keys
    present in `filters` are populated; others are
    omitted.

    """


class GetAllConversationsApplied(BaseModel):
    filters: List[str]
    r"""Names of filters currently applied."""

    values: GetAllConversationsValues
    r"""Current value for each applied filter. Only keys
    present in `filters` are populated; others are
    omitted.

    """


class GetAllConversationsSharedTypedDict(TypedDict):
    values: NotRequired[List[str]]
    r"""Accepted values for the `shared` query param."""
    description: NotRequired[str]
    current: NotRequired[Nullable[str]]
    applied: NotRequired[bool]


class GetAllConversationsShared(BaseModel):
    values: Optional[List[str]] = None
    r"""Accepted values for the `shared` query param."""

    description: Optional[str] = None

    current: OptionalNullable[str] = UNSET

    applied: Optional[bool] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["values", "description", "current", "applied"])
        nullable_fields = set(["current"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


class GetAllConversationsTagsTypedDict(TypedDict):
    type: NotRequired[str]
    description: NotRequired[str]
    current: NotRequired[Nullable[str]]
    applied: NotRequired[bool]


class GetAllConversationsTags(BaseModel):
    type: Optional[str] = None

    description: Optional[str] = None

    current: OptionalNullable[str] = UNSET

    applied: Optional[bool] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["type", "description", "current", "applied"])
        nullable_fields = set(["current"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


class GetAllConversationsMinMessagesTypedDict(TypedDict):
    type: NotRequired[str]
    description: NotRequired[str]
    current: NotRequired[Nullable[float]]
    applied: NotRequired[bool]


class GetAllConversationsMinMessages(BaseModel):
    type: Optional[str] = None

    description: Optional[str] = None

    current: OptionalNullable[float] = UNSET

    applied: Optional[bool] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["type", "description", "current", "applied"])
        nullable_fields = set(["current"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


class GetAllConversationsSearchTypedDict(TypedDict):
    type: NotRequired[str]
    description: NotRequired[str]
    current: NotRequired[Nullable[str]]
    applied: NotRequired[bool]


class GetAllConversationsSearch(BaseModel):
    type: Optional[str] = None

    description: Optional[str] = None

    current: OptionalNullable[str] = UNSET

    applied: Optional[bool] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["type", "description", "current", "applied"])
        nullable_fields = set(["current"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


class GetAllConversationsPageTypedDict(TypedDict):
    type: NotRequired[str]
    current: NotRequired[int]
    min: NotRequired[int]
    max: NotRequired[int]
    default: NotRequired[int]
    description: NotRequired[str]
    applied: NotRequired[bool]


class GetAllConversationsPage(BaseModel):
    type: Optional[str] = None

    current: Optional[int] = None

    min: Optional[int] = None

    max: Optional[int] = None

    default: Optional[int] = None

    description: Optional[str] = None

    applied: Optional[bool] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["type", "current", "min", "max", "default", "description", "applied"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class GetAllConversationsLimitTypedDict(TypedDict):
    type: NotRequired[str]
    current: NotRequired[int]
    min: NotRequired[int]
    max: NotRequired[int]
    default: NotRequired[int]
    description: NotRequired[str]
    applied: NotRequired[bool]


class GetAllConversationsLimit(BaseModel):
    type: Optional[str] = None

    current: Optional[int] = None

    min: Optional[int] = None

    max: Optional[int] = None

    default: Optional[int] = None

    description: Optional[str] = None

    applied: Optional[bool] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["type", "current", "min", "max", "default", "description", "applied"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class GetAllConversationsAvailablePaginationTypedDict(TypedDict):
    page: NotRequired[GetAllConversationsPageTypedDict]
    limit: NotRequired[GetAllConversationsLimitTypedDict]


class GetAllConversationsAvailablePagination(BaseModel):
    page: Optional[GetAllConversationsPage] = None

    limit: Optional[GetAllConversationsLimit] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["page", "limit"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class GetAllConversationsSortingSortByTypedDict(TypedDict):
    values: NotRequired[List[str]]
    default: NotRequired[str]
    description: NotRequired[str]
    current: NotRequired[str]
    applied: NotRequired[bool]


class GetAllConversationsSortingSortBy(BaseModel):
    values: Optional[List[str]] = None

    default: Optional[str] = None

    description: Optional[str] = None

    current: Optional[str] = None

    applied: Optional[bool] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["values", "default", "description", "current", "applied"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class GetAllConversationsSortingSortOrderTypedDict(TypedDict):
    values: NotRequired[List[str]]
    default: NotRequired[str]
    description: NotRequired[str]
    current: NotRequired[str]
    applied: NotRequired[bool]


class GetAllConversationsSortingSortOrder(BaseModel):
    values: Optional[List[str]] = None

    default: Optional[str] = None

    description: Optional[str] = None

    current: Optional[str] = None

    applied: Optional[bool] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["values", "default", "description", "current", "applied"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class GetAllConversationsSortingTypedDict(TypedDict):
    sort_by: NotRequired[GetAllConversationsSortingSortByTypedDict]
    sort_order: NotRequired[GetAllConversationsSortingSortOrderTypedDict]


class GetAllConversationsSorting(BaseModel):
    sort_by: Annotated[
        Optional[GetAllConversationsSortingSortBy], pydantic.Field(alias="sortBy")
    ] = None

    sort_order: Annotated[
        Optional[GetAllConversationsSortingSortOrder], pydantic.Field(alias="sortOrder")
    ] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["sortBy", "sortOrder"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class GetAllConversationsCurrentTypedDict(TypedDict):
    start: NotRequired[Nullable[str]]
    end: NotRequired[Nullable[str]]


class GetAllConversationsCurrent(BaseModel):
    start: OptionalNullable[str] = UNSET

    end: OptionalNullable[str] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["start", "end"])
        nullable_fields = set(["start", "end"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


class GetAllConversationsDateFiltersDateRangeTypedDict(TypedDict):
    type: NotRequired[str]
    description: NotRequired[str]
    format_: NotRequired[str]
    current: NotRequired[GetAllConversationsCurrentTypedDict]
    applied: NotRequired[bool]


class GetAllConversationsDateFiltersDateRange(BaseModel):
    type: Optional[str] = None

    description: Optional[str] = None

    format_: Annotated[Optional[str], pydantic.Field(alias="format")] = None

    current: Optional[GetAllConversationsCurrent] = None

    applied: Optional[bool] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["type", "description", "format", "current", "applied"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class GetAllConversationsDateFiltersTypedDict(TypedDict):
    date_range: NotRequired[GetAllConversationsDateFiltersDateRangeTypedDict]


class GetAllConversationsDateFilters(BaseModel):
    date_range: Annotated[
        Optional[GetAllConversationsDateFiltersDateRange],
        pydantic.Field(alias="dateRange"),
    ] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["dateRange"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class GetAllConversationsMessageTypeTypedDict(TypedDict):
    values: NotRequired[List[str]]
    description: NotRequired[str]
    current: NotRequired[Nullable[str]]
    applied: NotRequired[bool]


class GetAllConversationsMessageType(BaseModel):
    values: Optional[List[str]] = None

    description: Optional[str] = None

    current: OptionalNullable[str] = UNSET

    applied: Optional[bool] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["values", "description", "current", "applied"])
        nullable_fields = set(["current"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


class GetAllConversationsMessageFiltersTypedDict(TypedDict):
    message_type: NotRequired[GetAllConversationsMessageTypeTypedDict]


class GetAllConversationsMessageFilters(BaseModel):
    message_type: Annotated[
        Optional[GetAllConversationsMessageType], pydantic.Field(alias="messageType")
    ] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["messageType"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class GetAllConversationsSortingMessagesSortByTypedDict(TypedDict):
    values: NotRequired[List[str]]
    default: NotRequired[str]
    description: NotRequired[str]
    current: NotRequired[str]


class GetAllConversationsSortingMessagesSortBy(BaseModel):
    values: Optional[List[str]] = None

    default: Optional[str] = None

    description: Optional[str] = None

    current: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["values", "default", "description", "current"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class GetAllConversationsSortingMessagesSortOrderTypedDict(TypedDict):
    values: NotRequired[List[str]]
    default: NotRequired[str]
    description: NotRequired[str]
    current: NotRequired[str]


class GetAllConversationsSortingMessagesSortOrder(BaseModel):
    values: Optional[List[str]] = None

    default: Optional[str] = None

    description: Optional[str] = None

    current: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["values", "default", "description", "current"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class GetAllConversationsSortingMessagesTypedDict(TypedDict):
    sort_by: NotRequired[GetAllConversationsSortingMessagesSortByTypedDict]
    sort_order: NotRequired[GetAllConversationsSortingMessagesSortOrderTypedDict]


class GetAllConversationsSortingMessages(BaseModel):
    sort_by: Annotated[
        Optional[GetAllConversationsSortingMessagesSortBy],
        pydantic.Field(alias="sortBy"),
    ] = None

    sort_order: Annotated[
        Optional[GetAllConversationsSortingMessagesSortOrder],
        pydantic.Field(alias="sortOrder"),
    ] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["sortBy", "sortOrder"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class GetAllConversationsAvailableTypedDict(TypedDict):
    shared: GetAllConversationsSharedTypedDict
    tags: GetAllConversationsTagsTypedDict
    min_messages: GetAllConversationsMinMessagesTypedDict
    search: GetAllConversationsSearchTypedDict
    pagination: GetAllConversationsAvailablePaginationTypedDict
    sorting: GetAllConversationsSortingTypedDict
    date_filters: GetAllConversationsDateFiltersTypedDict
    message_filters: GetAllConversationsMessageFiltersTypedDict
    sorting_messages: GetAllConversationsSortingMessagesTypedDict


class GetAllConversationsAvailable(BaseModel):
    shared: GetAllConversationsShared

    tags: GetAllConversationsTags

    min_messages: Annotated[
        GetAllConversationsMinMessages, pydantic.Field(alias="minMessages")
    ]

    search: GetAllConversationsSearch

    pagination: GetAllConversationsAvailablePagination

    sorting: GetAllConversationsSorting

    date_filters: Annotated[
        GetAllConversationsDateFilters, pydantic.Field(alias="dateFilters")
    ]

    message_filters: Annotated[
        GetAllConversationsMessageFilters, pydantic.Field(alias="messageFilters")
    ]

    sorting_messages: Annotated[
        GetAllConversationsSortingMessages, pydantic.Field(alias="sortingMessages")
    ]


class GetAllConversationsFiltersTypedDict(TypedDict):
    r"""Filter introspection block. `applied` summarises the
    filters active on this request; `available` catalogues
    every supported filter with its current value and whether
    it is applied.

    """

    applied: GetAllConversationsAppliedTypedDict
    available: GetAllConversationsAvailableTypedDict


class GetAllConversationsFilters(BaseModel):
    r"""Filter introspection block. `applied` summarises the
    filters active on this request; `available` catalogues
    every supported filter with its current value and whether
    it is applied.

    """

    applied: GetAllConversationsApplied

    available: GetAllConversationsAvailable


class GetAllConversationsMetaTypedDict(TypedDict):
    request_id: NotRequired[str]
    timestamp: NotRequired[datetime]
    duration: NotRequired[int]


class GetAllConversationsMeta(BaseModel):
    request_id: Annotated[Optional[str], pydantic.Field(alias="requestId")] = None

    timestamp: Optional[datetime] = None

    duration: Optional[int] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["requestId", "timestamp", "duration"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class GetAllConversationsResponseTypedDict(TypedDict):
    r"""List of conversations for the requested source"""

    conversations: List[ConversationListItemTypedDict]
    source: GetAllConversationsSourceResponse
    r"""Echoes the requested `source` query value."""
    pagination: GetAllConversationsPaginationTypedDict
    filters: GetAllConversationsFiltersTypedDict
    r"""Filter introspection block. `applied` summarises the
    filters active on this request; `available` catalogues
    every supported filter with its current value and whether
    it is applied.

    """
    meta: GetAllConversationsMetaTypedDict


class GetAllConversationsResponse(BaseModel):
    r"""List of conversations for the requested source"""

    conversations: List[ConversationListItem]

    source: GetAllConversationsSourceResponse
    r"""Echoes the requested `source` query value."""

    pagination: GetAllConversationsPagination

    filters: GetAllConversationsFilters
    r"""Filter introspection block. `applied` summarises the
    filters active on this request; `available` catalogues
    every supported filter with its current value and whether
    it is applied.

    """

    meta: GetAllConversationsMeta


try:
    GetAllConversationsPagination.model_rebuild()
except NameError:
    pass
try:
    GetAllConversationsValues.model_rebuild()
except NameError:
    pass
try:
    GetAllConversationsSorting.model_rebuild()
except NameError:
    pass
try:
    GetAllConversationsDateFiltersDateRange.model_rebuild()
except NameError:
    pass
try:
    GetAllConversationsDateFilters.model_rebuild()
except NameError:
    pass
try:
    GetAllConversationsMessageFilters.model_rebuild()
except NameError:
    pass
try:
    GetAllConversationsSortingMessages.model_rebuild()
except NameError:
    pass
try:
    GetAllConversationsAvailable.model_rebuild()
except NameError:
    pass
try:
    GetAllConversationsMeta.model_rebuild()
except NameError:
    pass
