"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: 43c97645b0aa

from __future__ import annotations
from pipeshub_sdk.types import BaseModel
from typing_extensions import TypedDict


class GetAIModelsConfigResponseTypedDict(TypedDict):
    r"""AI models config retrieved"""


class GetAIModelsConfigResponse(BaseModel):
    r"""AI models config retrieved"""
