"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pipeshub_sdk.types import BaseModel, UNSET_SENTINEL
from pipeshub_sdk.utils import FieldMetadata, PathParamMetadata, QueryParamMetadata
import pydantic
from pydantic import model_serializer
from typing import Literal, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


ParentType = Literal[
    "app",
    "recordGroup",
    "folder",
    "record",
]
r"""Type of the parent node whose children to retrieve.

Must be one of: `app`, `recordGroup`, `folder`, `record`.
Any other value returns a 400 error.

"""


GetKnowledgeHubChildNodesSortBy = Literal[
    "name",
    "createdAt",
    "updatedAt",
    "size",
    "type",
]
r"""Field to sort results by. Omitted → default `updatedAt`.
Unknown value → silently falls back to `name`.

"""


GetKnowledgeHubChildNodesSortOrder = Literal[
    "asc",
    "desc",
]
r"""Sort direction. Omitted → default `desc`.
Unknown value → silently falls back to `asc`.

"""


class GetKnowledgeHubChildNodesRequestTypedDict(TypedDict):
    parent_type: ParentType
    r"""Type of the parent node whose children to retrieve.

    Must be one of: `app`, `recordGroup`, `folder`, `record`.
    Any other value returns a 400 error.

    """
    parent_id: str
    r"""Identifier of the parent node. Must be a valid UUID
    (e.g. `f3a4b5b6-5b6c-4e85-9097-3202cfe696fc`).

    Any value that does not match this format returns a 400 error.

    """
    only_containers: NotRequired[bool]
    r"""When `true`, only nodes that have children are returned (useful for
    building sidebar / tree navigation). Leaf nodes are excluded.

    """
    page: NotRequired[int]
    r"""Page number (1-indexed). Combined with `limit` to paginate results.

    """
    limit: NotRequired[int]
    r"""Maximum number of items to return per page.

    """
    sort_by: NotRequired[GetKnowledgeHubChildNodesSortBy]
    r"""Field to sort results by. Omitted → default `updatedAt`.
    Unknown value → silently falls back to `name`.

    """
    sort_order: NotRequired[GetKnowledgeHubChildNodesSortOrder]
    r"""Sort direction. Omitted → default `desc`.
    Unknown value → silently falls back to `asc`.

    """
    q: NotRequired[str]
    r"""Full-text search query. Must be between 2 and 500 characters
    (inclusive). When provided, the endpoint searches across all
    descendants of the parent node.

    """
    node_types: NotRequired[str]
    r"""Comma-separated list of node types to include. Invalid values are
    silently ignored. Maximum 100 items.

    Valid values: `folder`, `app`, `recordGroup`, `record`

    """
    record_types: NotRequired[str]
    r"""Comma-separated list of record types to include. Invalid values are
    silently ignored. Maximum 100 items.

    Valid values: `FILE`, `DRIVE`, `WEBPAGE`, `DATABASE`, `DATASOURCE`,
    `MESSAGE`, `MAIL`, `GROUP_MAIL`, `TICKET`, `COMMENT`,
    `INLINE_COMMENT`, `CONFLUENCE_PAGE`, `CONFLUENCE_BLOGPOST`,
    `SHAREPOINT_PAGE`, `SHAREPOINT_LIST`, `SHAREPOINT_LIST_ITEM`,
    `SHAREPOINT_DOCUMENT_LIBRARY`, `LINK`, `PROJECT`, `PULL_REQUEST`,
    `MEETING`, `PRODUCT`, `DEAL`, `CASE`, `TASK`, `ARTIFACT`,
    `CODE_FILE`, `SQL_TABLE`, `SQL_VIEW`, `OTHERS`

    """
    origins: NotRequired[str]
    r"""Comma-separated list of origin types to include. Invalid values are
    silently ignored. Maximum 100 items.

    Valid values: `COLLECTION`, `CONNECTOR`

    """
    connector_ids: NotRequired[str]
    r"""Comma-separated list of connector instance IDs (UUIDs) to filter by.
    Maximum 100 items. No enum validation — any string is accepted, but
    non-existent IDs simply yield zero results.

    """
    indexing_status: NotRequired[str]
    r"""Comma-separated list of indexing statuses to include. Invalid values
    are silently ignored. Maximum 100 items.

    Valid values: `NOT_STARTED`, `PAUSED`, `IN_PROGRESS`, `COMPLETED`,
    `FAILED`, `FILE_TYPE_NOT_SUPPORTED`, `AUTO_INDEX_OFF`, `EMPTY`,
    `ENABLE_MULTIMODAL_MODELS`, `QUEUED`

    """
    created_at: NotRequired[str]
    r"""Created-date range filter. Format: `gte:<epochMs>,lte:<epochMs>`.
    Both bounds are optional (you may send just `gte:...` or just
    `lte:...`). Timestamps must be in the range 0 to 9999999999999 and
    `gte` must be less than or equal to `lte` when both are present.

    """
    updated_at: NotRequired[str]
    r"""Updated-date range filter. Same format and constraints as `createdAt`.

    """
    size: NotRequired[str]
    r"""File-size range filter in bytes. Format: `gte:<bytes>,lte:<bytes>`.
    Both bounds are optional. Values must be non-negative and at most
    1099511627776 (1 TB). `gte` must be less than or equal to `lte`
    when both are present.

    """
    flattened: NotRequired[bool]
    r"""Force flattened/recursive search (`true`) or direct top-level
    listing (`false`). When omitted, it's computed from whether any
    of `q`, `nodeTypes`, `recordTypes`, `origins`, `connectorIds`,
    `indexingStatus`, `createdAt`, `updatedAt`, or `size` are present —
    if any are, results are flattened automatically; otherwise only
    top-level nodes are returned.

    """
    include: NotRequired[str]
    r"""Comma-separated list of additional response sections to include.
    Invalid values are silently ignored. Maximum 100 items.

    Valid values: `breadcrumbs`, `counts`, `availableFilters`, `permissions`

    """


class GetKnowledgeHubChildNodesRequest(BaseModel):
    parent_type: Annotated[
        ParentType,
        pydantic.Field(alias="parentType"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""Type of the parent node whose children to retrieve.

    Must be one of: `app`, `recordGroup`, `folder`, `record`.
    Any other value returns a 400 error.

    """

    parent_id: Annotated[
        str,
        pydantic.Field(alias="parentId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""Identifier of the parent node. Must be a valid UUID
    (e.g. `f3a4b5b6-5b6c-4e85-9097-3202cfe696fc`).

    Any value that does not match this format returns a 400 error.

    """

    only_containers: Annotated[
        Optional[bool],
        pydantic.Field(alias="onlyContainers"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = False
    r"""When `true`, only nodes that have children are returned (useful for
    building sidebar / tree navigation). Leaf nodes are excluded.

    """

    page: Annotated[
        Optional[int],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = 1
    r"""Page number (1-indexed). Combined with `limit` to paginate results.

    """

    limit: Annotated[
        Optional[int],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = 50
    r"""Maximum number of items to return per page.

    """

    sort_by: Annotated[
        Optional[GetKnowledgeHubChildNodesSortBy],
        pydantic.Field(alias="sortBy"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = "updatedAt"
    r"""Field to sort results by. Omitted → default `updatedAt`.
    Unknown value → silently falls back to `name`.

    """

    sort_order: Annotated[
        Optional[GetKnowledgeHubChildNodesSortOrder],
        pydantic.Field(alias="sortOrder"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = "desc"
    r"""Sort direction. Omitted → default `desc`.
    Unknown value → silently falls back to `asc`.

    """

    q: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Full-text search query. Must be between 2 and 500 characters
    (inclusive). When provided, the endpoint searches across all
    descendants of the parent node.

    """

    node_types: Annotated[
        Optional[str],
        pydantic.Field(alias="nodeTypes"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Comma-separated list of node types to include. Invalid values are
    silently ignored. Maximum 100 items.

    Valid values: `folder`, `app`, `recordGroup`, `record`

    """

    record_types: Annotated[
        Optional[str],
        pydantic.Field(alias="recordTypes"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Comma-separated list of record types to include. Invalid values are
    silently ignored. Maximum 100 items.

    Valid values: `FILE`, `DRIVE`, `WEBPAGE`, `DATABASE`, `DATASOURCE`,
    `MESSAGE`, `MAIL`, `GROUP_MAIL`, `TICKET`, `COMMENT`,
    `INLINE_COMMENT`, `CONFLUENCE_PAGE`, `CONFLUENCE_BLOGPOST`,
    `SHAREPOINT_PAGE`, `SHAREPOINT_LIST`, `SHAREPOINT_LIST_ITEM`,
    `SHAREPOINT_DOCUMENT_LIBRARY`, `LINK`, `PROJECT`, `PULL_REQUEST`,
    `MEETING`, `PRODUCT`, `DEAL`, `CASE`, `TASK`, `ARTIFACT`,
    `CODE_FILE`, `SQL_TABLE`, `SQL_VIEW`, `OTHERS`

    """

    origins: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Comma-separated list of origin types to include. Invalid values are
    silently ignored. Maximum 100 items.

    Valid values: `COLLECTION`, `CONNECTOR`

    """

    connector_ids: Annotated[
        Optional[str],
        pydantic.Field(alias="connectorIds"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Comma-separated list of connector instance IDs (UUIDs) to filter by.
    Maximum 100 items. No enum validation — any string is accepted, but
    non-existent IDs simply yield zero results.

    """

    indexing_status: Annotated[
        Optional[str],
        pydantic.Field(alias="indexingStatus"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Comma-separated list of indexing statuses to include. Invalid values
    are silently ignored. Maximum 100 items.

    Valid values: `NOT_STARTED`, `PAUSED`, `IN_PROGRESS`, `COMPLETED`,
    `FAILED`, `FILE_TYPE_NOT_SUPPORTED`, `AUTO_INDEX_OFF`, `EMPTY`,
    `ENABLE_MULTIMODAL_MODELS`, `QUEUED`

    """

    created_at: Annotated[
        Optional[str],
        pydantic.Field(alias="createdAt"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Created-date range filter. Format: `gte:<epochMs>,lte:<epochMs>`.
    Both bounds are optional (you may send just `gte:...` or just
    `lte:...`). Timestamps must be in the range 0 to 9999999999999 and
    `gte` must be less than or equal to `lte` when both are present.

    """

    updated_at: Annotated[
        Optional[str],
        pydantic.Field(alias="updatedAt"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Updated-date range filter. Same format and constraints as `createdAt`.

    """

    size: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""File-size range filter in bytes. Format: `gte:<bytes>,lte:<bytes>`.
    Both bounds are optional. Values must be non-negative and at most
    1099511627776 (1 TB). `gte` must be less than or equal to `lte`
    when both are present.

    """

    flattened: Annotated[
        Optional[bool],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Force flattened/recursive search (`true`) or direct top-level
    listing (`false`). When omitted, it's computed from whether any
    of `q`, `nodeTypes`, `recordTypes`, `origins`, `connectorIds`,
    `indexingStatus`, `createdAt`, `updatedAt`, or `size` are present —
    if any are, results are flattened automatically; otherwise only
    top-level nodes are returned.

    """

    include: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Comma-separated list of additional response sections to include.
    Invalid values are silently ignored. Maximum 100 items.

    Valid values: `breadcrumbs`, `counts`, `availableFilters`, `permissions`

    """

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "onlyContainers",
                "page",
                "limit",
                "sortBy",
                "sortOrder",
                "q",
                "nodeTypes",
                "recordTypes",
                "origins",
                "connectorIds",
                "indexingStatus",
                "createdAt",
                "updatedAt",
                "size",
                "flattened",
                "include",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


GetKnowledgeHubChildNodesCodeHTTPInternalServerError = Literal[
    "HTTP_INTERNAL_SERVER_ERROR",
]


class GetKnowledgeHubChildNodesErrorHTTPInternalServerErrorTypedDict(TypedDict):
    code: GetKnowledgeHubChildNodesCodeHTTPInternalServerError
    message: str


class GetKnowledgeHubChildNodesErrorHTTPInternalServerError(BaseModel):
    code: GetKnowledgeHubChildNodesCodeHTTPInternalServerError

    message: str


GetKnowledgeHubChildNodesNotFoundCode = Literal["HTTP_NOT_FOUND",]


class GetKnowledgeHubChildNodesNotFoundErrorTypedDict(TypedDict):
    code: GetKnowledgeHubChildNodesNotFoundCode
    message: str


class GetKnowledgeHubChildNodesNotFoundError(BaseModel):
    code: GetKnowledgeHubChildNodesNotFoundCode

    message: str


GetKnowledgeHubChildNodesForbiddenCode = Literal["HTTP_FORBIDDEN",]


class GetKnowledgeHubChildNodesErrorHTTPForbiddenTypedDict(TypedDict):
    code: GetKnowledgeHubChildNodesForbiddenCode
    message: str


class GetKnowledgeHubChildNodesErrorHTTPForbidden(BaseModel):
    code: GetKnowledgeHubChildNodesForbiddenCode

    message: str


GetKnowledgeHubChildNodesUnauthorizedCode = Literal["HTTP_UNAUTHORIZED",]


class GetKnowledgeHubChildNodesErrorHTTPUnauthorizedTypedDict(TypedDict):
    code: GetKnowledgeHubChildNodesUnauthorizedCode
    message: str


class GetKnowledgeHubChildNodesErrorHTTPUnauthorized(BaseModel):
    code: GetKnowledgeHubChildNodesUnauthorizedCode

    message: str


GetKnowledgeHubChildNodesCodeHTTPBadRequest = Literal["HTTP_BAD_REQUEST",]


class GetKnowledgeHubChildNodesErrorHTTPBadRequestTypedDict(TypedDict):
    code: GetKnowledgeHubChildNodesCodeHTTPBadRequest
    message: str


class GetKnowledgeHubChildNodesErrorHTTPBadRequest(BaseModel):
    code: GetKnowledgeHubChildNodesCodeHTTPBadRequest

    message: str
