"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .conversationlistitem import ConversationListItem, ConversationListItemTypedDict
from pipeshub_sdk.types import BaseModel, UNSET_SENTINEL
from pipeshub_sdk.utils import FieldMetadata, PathParamMetadata, QueryParamMetadata
import pydantic
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class GetProjectConversationsRequestTypedDict(TypedDict):
    project_id: str
    page: NotRequired[int]
    limit: NotRequired[int]


class GetProjectConversationsRequest(BaseModel):
    project_id: Annotated[
        str,
        pydantic.Field(alias="projectId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]

    page: Annotated[
        Optional[int],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = 1

    limit: Annotated[
        Optional[int],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = 20

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["page", "limit"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class GetProjectConversationsPaginationTypedDict(TypedDict):
    page: NotRequired[int]
    limit: NotRequired[int]
    total_count: NotRequired[int]
    total_pages: NotRequired[int]


class GetProjectConversationsPagination(BaseModel):
    page: Optional[int] = None

    limit: Optional[int] = None

    total_count: Annotated[Optional[int], pydantic.Field(alias="totalCount")] = None

    total_pages: Annotated[Optional[int], pydantic.Field(alias="totalPages")] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["page", "limit", "totalCount", "totalPages"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class GetProjectConversationsResponseTypedDict(TypedDict):
    r"""Paginated conversations linked to the project"""

    conversations: List[ConversationListItemTypedDict]
    pagination: GetProjectConversationsPaginationTypedDict


class GetProjectConversationsResponse(BaseModel):
    r"""Paginated conversations linked to the project"""

    conversations: List[ConversationListItem]

    pagination: GetProjectConversationsPagination


try:
    GetProjectConversationsPagination.model_rebuild()
except NameError:
    pass
