"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: 12b648bbbb2f

from __future__ import annotations
from pipeshub_sdk.types import BaseModel
from pipeshub_sdk.utils import FieldMetadata, PathParamMetadata
import pydantic
from typing_extensions import Annotated, TypedDict


class GetToolsetConfigRequestTypedDict(TypedDict):
    toolset_id: str


class GetToolsetConfigRequest(BaseModel):
    toolset_id: Annotated[
        str,
        pydantic.Field(alias="toolsetId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
