"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: 85e6000c1dad

from __future__ import annotations
from pipeshub_sdk.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Literal, Optional, Union
from typing_extensions import NotRequired, TypeAliasType, TypedDict


HANDLE_MCP_REQUEST_OP_SERVERS = [
    "https://{instance_url}",
]


JsonrpcRequest = Literal["2.0",]


IDRequestTypedDict = TypeAliasType("IDRequestTypedDict", Union[str, int])


IDRequest = TypeAliasType("IDRequest", Union[str, int])


class ParamsTypedDict(TypedDict):
    pass


class Params(BaseModel):
    pass


class HandleMCPRequestRequestTypedDict(TypedDict):
    r"""JSON-RPC 2.0 request object"""

    jsonrpc: JsonrpcRequest
    method: str
    r"""MCP method (e.g. initialize, tools/list, tools/call)"""
    id: NotRequired[IDRequestTypedDict]
    params: NotRequired[ParamsTypedDict]


class HandleMCPRequestRequest(BaseModel):
    r"""JSON-RPC 2.0 request object"""

    jsonrpc: JsonrpcRequest

    method: str
    r"""MCP method (e.g. initialize, tools/list, tools/call)"""

    id: Optional[IDRequest] = None

    params: Optional[Params] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["id", "params"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


JsonrpcResponse = Literal["2.0",]


IDResponseTypedDict = TypeAliasType("IDResponseTypedDict", Union[str, int])


IDResponse = TypeAliasType("IDResponse", Union[str, int])


class ResultTypedDict(TypedDict):
    pass


class Result(BaseModel):
    pass


class HandleMCPRequestErrorTypedDict(TypedDict):
    code: NotRequired[int]
    message: NotRequired[str]


class HandleMCPRequestError(BaseModel):
    code: Optional[int] = None

    message: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["code", "message"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class HandleMCPRequestResponseTypedDict(TypedDict):
    r"""JSON-RPC 2.0 response"""

    jsonrpc: NotRequired[JsonrpcResponse]
    id: NotRequired[IDResponseTypedDict]
    result: NotRequired[ResultTypedDict]
    error: NotRequired[HandleMCPRequestErrorTypedDict]


class HandleMCPRequestResponse(BaseModel):
    r"""JSON-RPC 2.0 response"""

    jsonrpc: Optional[JsonrpcResponse] = None

    id: Optional[IDResponse] = None

    result: Optional[Result] = None

    error: Optional[HandleMCPRequestError] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["jsonrpc", "id", "result", "error"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
