"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pipeshub_sdk.types import BaseModel, Nullable, UNSET_SENTINEL
from pydantic import model_serializer
from typing_extensions import TypedDict


class KnowledgeGraphNodeRefSchemaTypedDict(TypedDict):
    r"""Minimal identity reference for a node in the knowledge graph."""

    id: str
    r"""Node identifier. Pass it back as `nodeId` to open this node. When `is_record` is true it is also the Record ID accepted by GET /connectors/record/{recordId}/content."""
    name: str
    node_type: str
    r"""One of `app`, `recordGroup`, `folder`, `record`."""
    sub_type: Nullable[str]
    r"""e.g. `TICKET`, `CONFLUENCE_PAGE`, `PROJECT`, `COLLECTION`."""
    is_record: bool
    r"""True for record and folder nodes — the nodes whose content can be read via GET /connectors/record/{recordId}/content."""


class KnowledgeGraphNodeRefSchema(BaseModel):
    r"""Minimal identity reference for a node in the knowledge graph."""

    id: str
    r"""Node identifier. Pass it back as `nodeId` to open this node. When `is_record` is true it is also the Record ID accepted by GET /connectors/record/{recordId}/content."""

    name: str

    node_type: str
    r"""One of `app`, `recordGroup`, `folder`, `record`."""

    sub_type: Nullable[str]
    r"""e.g. `TICKET`, `CONFLUENCE_PAGE`, `PROJECT`, `COLLECTION`."""

    is_record: bool
    r"""True for record and folder nodes — the nodes whose content can be read via GET /connectors/record/{recordId}/content."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                m[k] = val

        return m
