"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pipeshub_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from pydantic import model_serializer
from typing_extensions import NotRequired, TypedDict


class KnowledgeGraphLookupMatchSchemaTypedDict(TypedDict):
    r"""A single record resolved from an identifier."""

    id: str
    r"""The Record ID. Pass it to GET /connectors/record/{recordId}/content to read the record, or as `nodeId` to GET /connectors/navigate to list what is under it."""
    name: str
    record_type: Nullable[str]
    connector_name: Nullable[str]
    web_url: Nullable[str]
    indexing_status: Nullable[str]
    identifier_used: str
    r"""Which of the supplied identifiers produced this match."""
    external_id: NotRequired[Nullable[str]]
    r"""e.g. `PA-1787`, a Confluence page id, a Drive file id."""
    context_block: NotRequired[Nullable[str]]
    r"""Type-specific metadata for the record — for a ticket, status, assignee, priority and dates."""


class KnowledgeGraphLookupMatchSchema(BaseModel):
    r"""A single record resolved from an identifier."""

    id: str
    r"""The Record ID. Pass it to GET /connectors/record/{recordId}/content to read the record, or as `nodeId` to GET /connectors/navigate to list what is under it."""

    name: str

    record_type: Nullable[str]

    connector_name: Nullable[str]

    web_url: Nullable[str]

    indexing_status: Nullable[str]

    identifier_used: str
    r"""Which of the supplied identifiers produced this match."""

    external_id: OptionalNullable[str] = UNSET
    r"""e.g. `PA-1787`, a Confluence page id, a Drive file id."""

    context_block: OptionalNullable[str] = UNSET
    r"""Type-specific metadata for the record — for a ticket, status, assignee, priority and dates."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["external_id", "context_block"])
        nullable_fields = set(
            [
                "record_type",
                "connector_name",
                "web_url",
                "indexing_status",
                "external_id",
                "context_block",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
