"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pipeshub_sdk.types import BaseModel, Nullable, UNSET_SENTINEL, UnrecognizedStr
import pydantic
from pydantic import model_serializer
from typing import Literal, Union
from typing_extensions import Annotated, TypedDict


NodeType = Union[
    Literal[
        "app",
        "recordGroup",
        "folder",
        "record",
    ],
    UnrecognizedStr,
]
r"""Type of the node (app, recordGroup, folder, or record)."""


KnowledgeHubNodeOrigin = Union[
    Literal[
        "COLLECTION",
        "CONNECTOR",
    ],
    UnrecognizedStr,
]
r"""Origin type."""


class KnowledgeHubNodePermissionTypedDict(TypedDict):
    r"""Per-item permission when `include=permissions` is requested; otherwise `null`."""

    role: str
    can_edit: bool
    can_delete: bool


class KnowledgeHubNodePermission(BaseModel):
    r"""Per-item permission when `include=permissions` is requested; otherwise `null`."""

    role: str

    can_edit: Annotated[bool, pydantic.Field(alias="canEdit")]

    can_delete: Annotated[bool, pydantic.Field(alias="canDelete")]


class KnowledgeHubNodeTypedDict(TypedDict):
    r"""One element of `items`. The live API keeps keys stable and sets
    inapplicable values to JSON `null` (not omitted).

    """

    id: str
    r"""Unique identifier for the node."""
    name: str
    r"""Display name of the node."""
    node_type: NodeType
    r"""Type of the node (app, recordGroup, folder, or record)."""
    parent_id: Nullable[str]
    r"""Parent node ID, or `null` at the root browse level."""
    origin: KnowledgeHubNodeOrigin
    r"""Origin type."""
    connector: Nullable[str]
    r"""Connector display name / key when applicable; otherwise `null`."""
    record_type: Nullable[str]
    r"""Record type when `nodeType` is `record`; otherwise `null`."""
    record_group_type: Nullable[str]
    r"""Record group type when `nodeType` is `recordGroup`; otherwise `null`."""
    indexing_status: Nullable[str]
    r"""Indexing status when `nodeType` is `record`; otherwise `null`."""
    reason: Nullable[str]
    r"""Failure or status reason when set; otherwise `null`."""
    is_internal: bool
    r"""True for internal/system nodes that do not originate from a source."""
    is_placeholder: bool
    r"""True for placeholder/stub nodes standing in for an out-of-scope ancestor (rendered read-only, no content actions; excluded from search and indexing)."""
    created_at: int
    r"""Creation timestamp (epoch ms)."""
    updated_at: int
    r"""Update timestamp (epoch ms)."""
    size_in_bytes: Nullable[int]
    r"""File size in bytes for file records; otherwise `null`."""
    mime_type: Nullable[str]
    extension: Nullable[str]
    web_url: Nullable[str]
    has_children: bool
    r"""Whether the node has children (sidebar / tree)."""
    preview_renderable: Nullable[bool]
    permission: Nullable[KnowledgeHubNodePermissionTypedDict]
    r"""Per-item permission when `include=permissions` is requested; otherwise `null`."""
    sharing_status: Nullable[str]
    r"""Sharing status (e.g. `private`, `shared`, `team`, `workspace`) when
    applicable; otherwise `null`.

    """


class KnowledgeHubNode(BaseModel):
    r"""One element of `items`. The live API keeps keys stable and sets
    inapplicable values to JSON `null` (not omitted).

    """

    id: str
    r"""Unique identifier for the node."""

    name: str
    r"""Display name of the node."""

    node_type: Annotated[NodeType, pydantic.Field(alias="nodeType")]
    r"""Type of the node (app, recordGroup, folder, or record)."""

    parent_id: Annotated[Nullable[str], pydantic.Field(alias="parentId")]
    r"""Parent node ID, or `null` at the root browse level."""

    origin: KnowledgeHubNodeOrigin
    r"""Origin type."""

    connector: Nullable[str]
    r"""Connector display name / key when applicable; otherwise `null`."""

    record_type: Annotated[Nullable[str], pydantic.Field(alias="recordType")]
    r"""Record type when `nodeType` is `record`; otherwise `null`."""

    record_group_type: Annotated[Nullable[str], pydantic.Field(alias="recordGroupType")]
    r"""Record group type when `nodeType` is `recordGroup`; otherwise `null`."""

    indexing_status: Annotated[Nullable[str], pydantic.Field(alias="indexingStatus")]
    r"""Indexing status when `nodeType` is `record`; otherwise `null`."""

    reason: Nullable[str]
    r"""Failure or status reason when set; otherwise `null`."""

    is_internal: Annotated[bool, pydantic.Field(alias="isInternal")]
    r"""True for internal/system nodes that do not originate from a source."""

    is_placeholder: Annotated[bool, pydantic.Field(alias="isPlaceholder")]
    r"""True for placeholder/stub nodes standing in for an out-of-scope ancestor (rendered read-only, no content actions; excluded from search and indexing)."""

    created_at: Annotated[int, pydantic.Field(alias="createdAt")]
    r"""Creation timestamp (epoch ms)."""

    updated_at: Annotated[int, pydantic.Field(alias="updatedAt")]
    r"""Update timestamp (epoch ms)."""

    size_in_bytes: Annotated[Nullable[int], pydantic.Field(alias="sizeInBytes")]
    r"""File size in bytes for file records; otherwise `null`."""

    mime_type: Annotated[Nullable[str], pydantic.Field(alias="mimeType")]

    extension: Nullable[str]

    web_url: Annotated[Nullable[str], pydantic.Field(alias="webUrl")]

    has_children: Annotated[bool, pydantic.Field(alias="hasChildren")]
    r"""Whether the node has children (sidebar / tree)."""

    preview_renderable: Annotated[
        Nullable[bool], pydantic.Field(alias="previewRenderable")
    ]

    permission: Nullable[KnowledgeHubNodePermission]
    r"""Per-item permission when `include=permissions` is requested; otherwise `null`."""

    sharing_status: Annotated[Nullable[str], pydantic.Field(alias="sharingStatus")]
    r"""Sharing status (e.g. `private`, `shared`, `team`, `workspace`) when
    applicable; otherwise `null`.

    """

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                m[k] = val

        return m


try:
    KnowledgeHubNodePermission.model_rebuild()
except NameError:
    pass
try:
    KnowledgeHubNode.model_rebuild()
except NameError:
    pass
