"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .knowledgegraphlookupmatchschema import (
    KnowledgeGraphLookupMatchSchema,
    KnowledgeGraphLookupMatchSchemaTypedDict,
)
from pipeshub_sdk.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Dict, List, Optional
from typing_extensions import NotRequired, TypedDict


class LookupRecordResponseSchemaTypedDict(TypedDict):
    r"""Response returned by GET /connectors/record/lookup.

    Field names are snake_case, matching the knowledge graph's internal
    view models. A miss is a 200 with an empty `matches` and the input
    echoed in `not_found_identifiers` — see the endpoint description.

    """

    matches: List[KnowledgeGraphLookupMatchSchemaTypedDict]
    ambiguous: bool
    r"""True when one identifier resolved to more than one accessible record. Present the choice rather than taking the first, or retry with `connectorName`."""
    not_found_identifiers: List[str]
    r"""Identifiers that resolved to nothing the caller can access."""
    text: str
    r"""Flat-text rendering of the matches — each match's metadata block followed by a `Next:` line naming a follow-up call — and a line per miss naming the connectors that were searched. Capped at 25,000 bytes."""
    searched_connectors: NotRequired[Dict[str, List[str]]]
    r"""Per-identifier list of the connector types that were searched, so a miss can be retried against a different `connectorName`. Keys are the identifiers exactly as supplied."""


class LookupRecordResponseSchema(BaseModel):
    r"""Response returned by GET /connectors/record/lookup.

    Field names are snake_case, matching the knowledge graph's internal
    view models. A miss is a 200 with an empty `matches` and the input
    echoed in `not_found_identifiers` — see the endpoint description.

    """

    matches: List[KnowledgeGraphLookupMatchSchema]

    ambiguous: bool
    r"""True when one identifier resolved to more than one accessible record. Present the choice rather than taking the first, or retry with `connectorName`."""

    not_found_identifiers: List[str]
    r"""Identifiers that resolved to nothing the caller can access."""

    text: str
    r"""Flat-text rendering of the matches — each match's metadata block followed by a `Next:` line naming a follow-up call — and a line per miss naming the connectors that were searched. Capped at 25,000 bytes."""

    searched_connectors: Optional[Dict[str, List[str]]] = None
    r"""Per-identifier list of the connector types that were searched, so a miss can be retried against a different `connectorName`. Keys are the identifiers exactly as supplied."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["searched_connectors"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
