"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pipeshub_sdk.types import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class McpServerToolTypedDict(TypedDict):
    key: NotRequired[str]
    r"""Tool node key in the backing graph store."""
    name: NotRequired[str]
    full_name: NotRequired[str]
    description: NotRequired[str]


class McpServerTool(BaseModel):
    key: Annotated[Optional[str], pydantic.Field(alias="_key")] = None
    r"""Tool node key in the backing graph store."""

    name: Optional[str] = None

    full_name: Annotated[Optional[str], pydantic.Field(alias="fullName")] = None

    description: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["_key", "name", "fullName", "description"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class McpServerTypedDict(TypedDict):
    r"""MCP server instance linked to an agent, as projected by the graph
    store on `GET /agents/{agentKey}` and `GET /agents` — same shape as
    `Toolset`. MCP server nodes carry no secrets, only the attach-time
    snapshot of `instanceId`/`typeId`/`name`.

    """

    key: NotRequired[str]
    r"""MCP server instance node key in the backing graph store."""
    name: NotRequired[str]
    r"""MCP server attachment name (attach-time snapshot)."""
    display_name: NotRequired[str]
    r"""Human-readable MCP server product label (for example `Jira MCP`)."""
    type_id: NotRequired[str]
    r"""Catalog server type id, when this instance came from a registered template."""
    instance_id: NotRequired[str]
    r"""Admin-created MCP server instance id."""
    tools: NotRequired[List[McpServerToolTypedDict]]


class McpServer(BaseModel):
    r"""MCP server instance linked to an agent, as projected by the graph
    store on `GET /agents/{agentKey}` and `GET /agents` — same shape as
    `Toolset`. MCP server nodes carry no secrets, only the attach-time
    snapshot of `instanceId`/`typeId`/`name`.

    """

    key: Annotated[Optional[str], pydantic.Field(alias="_key")] = None
    r"""MCP server instance node key in the backing graph store."""

    name: Optional[str] = None
    r"""MCP server attachment name (attach-time snapshot)."""

    display_name: Annotated[Optional[str], pydantic.Field(alias="displayName")] = None
    r"""Human-readable MCP server product label (for example `Jira MCP`)."""

    type_id: Annotated[Optional[str], pydantic.Field(alias="typeId")] = None
    r"""Catalog server type id, when this instance came from a registered template."""

    instance_id: Annotated[Optional[str], pydantic.Field(alias="instanceId")] = None
    r"""Admin-created MCP server instance id."""

    tools: Optional[List[McpServerTool]] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["_key", "name", "displayName", "typeId", "instanceId", "tools"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    McpServerTool.model_rebuild()
except NameError:
    pass
try:
    McpServer.model_rebuild()
except NameError:
    pass
