"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pipeshub_sdk.types import BaseModel, UNSET_SENTINEL
import pydantic
from pydantic import model_serializer
from typing import List, Literal, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


MessageFeedbackSubmitRequestCategory = Literal[
    "incorrect_information",
    "missing_information",
    "irrelevant_information",
    "unclear_explanation",
    "poor_citations",
    "excellent_answer",
    "helpful_citations",
    "well_explained",
    "other",
]


class MessageFeedbackSubmitRequestCommentsTypedDict(TypedDict):
    r"""Free-text comments grouped by sentiment."""

    positive: NotRequired[str]
    r"""What was good about the response."""
    negative: NotRequired[str]
    r"""What could be improved."""


class MessageFeedbackSubmitRequestComments(BaseModel):
    r"""Free-text comments grouped by sentiment."""

    positive: Optional[str] = None
    r"""What was good about the response."""

    negative: Optional[str] = None
    r"""What could be improved."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["positive", "negative"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class MessageFeedbackSubmitRequestTypedDict(TypedDict):
    r"""Gateway request body for submitting message feedback (Zod
    `feedbackBodySchema`). All fields are optional; an empty object is
    accepted. Matches the first-party chat UI payload shape.

    """

    is_helpful: NotRequired[bool]
    r"""Overall helpfulness signal (thumbs up/down)."""
    categories: NotRequired[List[MessageFeedbackSubmitRequestCategory]]
    r"""Issue or positive categories that apply to the response."""
    comments: NotRequired[MessageFeedbackSubmitRequestCommentsTypedDict]
    r"""Free-text comments grouped by sentiment."""


class MessageFeedbackSubmitRequest(BaseModel):
    r"""Gateway request body for submitting message feedback (Zod
    `feedbackBodySchema`). All fields are optional; an empty object is
    accepted. Matches the first-party chat UI payload shape.

    """

    is_helpful: Annotated[Optional[bool], pydantic.Field(alias="isHelpful")] = None
    r"""Overall helpfulness signal (thumbs up/down)."""

    categories: Optional[List[MessageFeedbackSubmitRequestCategory]] = None
    r"""Issue or positive categories that apply to the response."""

    comments: Optional[MessageFeedbackSubmitRequestComments] = None
    r"""Free-text comments grouped by sentiment."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["isHelpful", "categories", "comments"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    MessageFeedbackSubmitRequest.model_rebuild()
except NameError:
    pass
