"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: 4986d2badd98

from __future__ import annotations
from typing import Literal


ModelType = Literal[
    "llm",
    "embedding",
    "ocr",
    "slm",
    "reasoning",
    "multiModal",
]
r"""Type of AI model"""
