"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pipeshub_sdk.types import UnrecognizedStr
from typing import Literal, Union


ModelType = Union[
    Literal[
        "llm",
        "embedding",
        "ocr",
        "slm",
        "reasoning",
        "multiModal",
        "imageGeneration",
        "tts",
        "stt",
    ],
    UnrecognizedStr,
]
r"""Type of AI model"""
