"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: d8a020f63434

from __future__ import annotations


OAUTH_AUTHORIZATION_SERVER_METADATA_OP_SERVERS = [
    # Root URL (not /api/v1)
    "https://{instance_url}",
]
