"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .address import Address, AddressTypedDict
from pipeshub_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
    UnrecognizedStr,
)
import pydantic
from pydantic import model_serializer
from typing import Literal, Optional, Union
from typing_extensions import Annotated, NotRequired, TypedDict


Kind = Union[
    Literal[
        "human",
        "service",
    ],
    UnrecognizedStr,
]
r"""Whether this account is a person who signs in (`human`) or a
machine identity that automation authenticates as (`service`).
Absent on records written before service accounts existed, which
are all human.

"""


RefreshTokenUserRole = Union[
    Literal[
        "admin",
        "member",
    ],
    UnrecognizedStr,
]
r"""Organization role stored on the user document (`admin` or `member`)"""


class RefreshTokenUserTypedDict(TypedDict):
    r"""User record returned with a refreshed access token"""

    id: str
    r"""User ID"""
    org_id: str
    r"""Organization ID"""
    email: str
    full_name: str
    has_logged_in: bool
    is_deleted: bool
    slug: str
    created_at: str
    updated_at: str
    v: int
    first_name: NotRequired[str]
    last_name: NotRequired[str]
    middle_name: NotRequired[str]
    mobile: NotRequired[str]
    r"""Mobile number (10-15 digits with optional +)"""
    designation: NotRequired[str]
    kind: NotRequired[Kind]
    r"""Whether this account is a person who signs in (`human`) or a
    machine identity that automation authenticates as (`service`).
    Absent on records written before service accounts existed, which
    are all human.

    """
    description: NotRequired[str]
    r"""Free text explaining what a service account is for. Unused for people."""
    is_disabled: NotRequired[bool]
    r"""The account is suspended: its tokens stop working and no session
    can be issued, but the record, its group memberships and its
    permission-graph node survive so it can be switched back on.

    """
    restore_op_id: NotRequired[str]
    r"""Internal and transient. Present only while a deleted service
    account is being brought back, and cleared when that finishes
    either way. It lets the steps that complete or undo a restore tell
    their own attempt from a later one. Not something to depend on.

    """
    role: NotRequired[RefreshTokenUserRole]
    r"""Organization role stored on the user document (`admin` or `member`)"""
    address: NotRequired[AddressTypedDict]
    data_collection_consent: NotRequired[bool]
    r"""Whether user has consented to data collection"""
    deleted_by: NotRequired[str]
    r"""ID of user who deleted this user"""
    profile_picture: NotRequired[Nullable[str]]
    r"""Base64-encoded data URI of the user's display picture"""


class RefreshTokenUser(BaseModel):
    r"""User record returned with a refreshed access token"""

    id: Annotated[str, pydantic.Field(alias="_id")]
    r"""User ID"""

    org_id: Annotated[str, pydantic.Field(alias="orgId")]
    r"""Organization ID"""

    email: str

    full_name: Annotated[str, pydantic.Field(alias="fullName")]

    has_logged_in: Annotated[bool, pydantic.Field(alias="hasLoggedIn")]

    is_deleted: Annotated[bool, pydantic.Field(alias="isDeleted")]

    slug: str

    created_at: Annotated[str, pydantic.Field(alias="createdAt")]

    updated_at: Annotated[str, pydantic.Field(alias="updatedAt")]

    v: Annotated[int, pydantic.Field(alias="__v")]

    first_name: Annotated[Optional[str], pydantic.Field(alias="firstName")] = None

    last_name: Annotated[Optional[str], pydantic.Field(alias="lastName")] = None

    middle_name: Annotated[Optional[str], pydantic.Field(alias="middleName")] = None

    mobile: Optional[str] = None
    r"""Mobile number (10-15 digits with optional +)"""

    designation: Optional[str] = None

    kind: Optional[Kind] = None
    r"""Whether this account is a person who signs in (`human`) or a
    machine identity that automation authenticates as (`service`).
    Absent on records written before service accounts existed, which
    are all human.

    """

    description: Optional[str] = None
    r"""Free text explaining what a service account is for. Unused for people."""

    is_disabled: Annotated[Optional[bool], pydantic.Field(alias="isDisabled")] = False
    r"""The account is suspended: its tokens stop working and no session
    can be issued, but the record, its group memberships and its
    permission-graph node survive so it can be switched back on.

    """

    restore_op_id: Annotated[Optional[str], pydantic.Field(alias="restoreOpId")] = None
    r"""Internal and transient. Present only while a deleted service
    account is being brought back, and cleared when that finishes
    either way. It lets the steps that complete or undo a restore tell
    their own attempt from a later one. Not something to depend on.

    """

    role: Optional[RefreshTokenUserRole] = None
    r"""Organization role stored on the user document (`admin` or `member`)"""

    address: Optional[Address] = None

    data_collection_consent: Annotated[
        Optional[bool], pydantic.Field(alias="dataCollectionConsent")
    ] = None
    r"""Whether user has consented to data collection"""

    deleted_by: Annotated[Optional[str], pydantic.Field(alias="deletedBy")] = None
    r"""ID of user who deleted this user"""

    profile_picture: Annotated[
        OptionalNullable[str], pydantic.Field(alias="profilePicture")
    ] = UNSET
    r"""Base64-encoded data URI of the user's display picture"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "firstName",
                "lastName",
                "middleName",
                "mobile",
                "designation",
                "kind",
                "description",
                "isDisabled",
                "restoreOpId",
                "role",
                "address",
                "dataCollectionConsent",
                "deletedBy",
                "profilePicture",
            ]
        )
        nullable_fields = set(["profilePicture"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


try:
    RefreshTokenUser.model_rebuild()
except NameError:
    pass
