"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .regeneraterequest import RegenerateRequest, RegenerateRequestTypedDict
from pipeshub_sdk.types import BaseModel, UNSET_SENTINEL
from pipeshub_sdk.utils import FieldMetadata, PathParamMetadata, RequestMetadata
import pydantic
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class RegenerateAgentConversationMessageRequestTypedDict(TypedDict):
    agent_key: str
    r"""Stable key identifying the agent that owns this conversation."""
    conversation_id: str
    r"""ID of the agent conversation containing the target message."""
    message_id: str
    r"""ID of the bot-response message to regenerate."""
    body: NotRequired[RegenerateRequestTypedDict]
    r"""Optional regeneration payload. All fields are optional and are
    validated against `RegenerateRequest`.

    """


class RegenerateAgentConversationMessageRequest(BaseModel):
    agent_key: Annotated[
        str,
        pydantic.Field(alias="agentKey"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""Stable key identifying the agent that owns this conversation."""

    conversation_id: Annotated[
        str,
        pydantic.Field(alias="conversationId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""ID of the agent conversation containing the target message."""

    message_id: Annotated[
        str,
        pydantic.Field(alias="messageId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""ID of the bot-response message to regenerate."""

    body: Annotated[
        Optional[RegenerateRequest],
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ] = None
    r"""Optional regeneration payload. All fields are optional and are
    validated against `RegenerateRequest`.

    """

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["body"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
