"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .semanticsearchboundingbox import (
    SemanticSearchBoundingBox,
    SemanticSearchBoundingBoxTypedDict,
)
from pipeshub_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
import pydantic
from pydantic import model_serializer
from typing import List, Union
from typing_extensions import Annotated, NotRequired, TypeAliasType, TypedDict


RecordVersionTypedDict = TypeAliasType("RecordVersionTypedDict", Union[str, float])


RecordVersion = TypeAliasType("RecordVersion", Union[str, float])


PointIDTypedDict = TypeAliasType("PointIDTypedDict", Union[str, int, float])
r"""Qdrant point identifier attached during vector lookup (shape varies by deployment)."""


PointID = TypeAliasType("PointID", Union[str, int, float])
r"""Qdrant point identifier attached during vector lookup (shape varies by deployment)."""


class SemanticSearchHitMetadataTypedDict(TypedDict):
    r"""Per-hit metadata after retrieval enrichment (record + vector context).
    Listed fields are the documented contract; Qdrant or pipeline updates may add more keys over time—extend this schema when new stable fields appear.

    """

    org_id: NotRequired[Nullable[str]]
    record_id: NotRequired[Nullable[str]]
    virtual_record_id: NotRequired[Nullable[str]]
    record_name: NotRequired[Nullable[str]]
    record_type: NotRequired[Nullable[str]]
    record_version: NotRequired[Nullable[RecordVersionTypedDict]]
    origin: NotRequired[Nullable[str]]
    connector: NotRequired[Nullable[str]]
    connector_id: NotRequired[Nullable[str]]
    connector_name: NotRequired[Nullable[str]]
    block_text: NotRequired[Nullable[str]]
    block_type: NotRequired[Nullable[str]]
    r"""Block type for this hit. Common values: `text`, `image`, `table_row`, `table`,
    `record_summary` (whole-record semantic summary chunk — no block index).

    """
    bounding_box: NotRequired[Nullable[List[SemanticSearchBoundingBoxTypedDict]]]
    page_num: NotRequired[Nullable[List[Nullable[int]]]]
    extension: NotRequired[Nullable[str]]
    mime_type: NotRequired[Nullable[str]]
    block_num: NotRequired[Nullable[List[float]]]
    chunk_index: NotRequired[Nullable[int]]
    sheet_name: NotRequired[Nullable[str]]
    sheet_num: NotRequired[Nullable[int]]
    web_url: NotRequired[Nullable[str]]
    preview_renderable: NotRequired[Nullable[bool]]
    hide_weburl: NotRequired[Nullable[bool]]
    categories: NotRequired[Nullable[List[str]]]
    departments: NotRequired[Nullable[List[str]]]
    topics: NotRequired[Nullable[List[str]]]
    languages: NotRequired[Nullable[List[str]]]
    subcategory_level1: NotRequired[Nullable[str]]
    subcategory_level2: NotRequired[Nullable[str]]
    subcategory_level3: NotRequired[Nullable[str]]
    score: NotRequired[Nullable[float]]
    id: NotRequired[Nullable[str]]
    collection_name: NotRequired[Nullable[str]]
    block_index: NotRequired[Nullable[int]]
    block_id: NotRequired[Nullable[str]]
    is_block: NotRequired[Nullable[bool]]
    is_block_group: NotRequired[Nullable[bool]]
    is_record_summary: NotRequired[Nullable[bool]]
    r"""Set to `true` by the indexing pipeline when this vector chunk represents a
    whole-record semantic summary rather than an individual block. When true,
    `blockIndex` is absent and `block_type` on the parent hit is `record_summary`.

    """
    kb_id: NotRequired[Nullable[str]]
    r"""Knowledge base id merged from graph record during retrieval (when present)."""
    point_id: NotRequired[Nullable[PointIDTypedDict]]
    r"""Qdrant point identifier attached during vector lookup (shape varies by deployment)."""


class SemanticSearchHitMetadata(BaseModel):
    r"""Per-hit metadata after retrieval enrichment (record + vector context).
    Listed fields are the documented contract; Qdrant or pipeline updates may add more keys over time—extend this schema when new stable fields appear.

    """

    org_id: Annotated[OptionalNullable[str], pydantic.Field(alias="orgId")] = UNSET

    record_id: Annotated[OptionalNullable[str], pydantic.Field(alias="recordId")] = (
        UNSET
    )

    virtual_record_id: Annotated[
        OptionalNullable[str], pydantic.Field(alias="virtualRecordId")
    ] = UNSET

    record_name: Annotated[
        OptionalNullable[str], pydantic.Field(alias="recordName")
    ] = UNSET

    record_type: Annotated[
        OptionalNullable[str], pydantic.Field(alias="recordType")
    ] = UNSET

    record_version: Annotated[
        OptionalNullable[RecordVersion], pydantic.Field(alias="recordVersion")
    ] = UNSET

    origin: OptionalNullable[str] = UNSET

    connector: OptionalNullable[str] = UNSET

    connector_id: Annotated[
        OptionalNullable[str], pydantic.Field(alias="connectorId")
    ] = UNSET

    connector_name: Annotated[
        OptionalNullable[str], pydantic.Field(alias="connectorName")
    ] = UNSET

    block_text: Annotated[OptionalNullable[str], pydantic.Field(alias="blockText")] = (
        UNSET
    )

    block_type: Annotated[OptionalNullable[str], pydantic.Field(alias="blockType")] = (
        UNSET
    )
    r"""Block type for this hit. Common values: `text`, `image`, `table_row`, `table`,
    `record_summary` (whole-record semantic summary chunk — no block index).

    """

    bounding_box: OptionalNullable[List[SemanticSearchBoundingBox]] = UNSET

    page_num: Annotated[
        OptionalNullable[List[Nullable[int]]], pydantic.Field(alias="pageNum")
    ] = UNSET

    extension: OptionalNullable[str] = UNSET

    mime_type: Annotated[OptionalNullable[str], pydantic.Field(alias="mimeType")] = (
        UNSET
    )

    block_num: Annotated[
        OptionalNullable[List[float]], pydantic.Field(alias="blockNum")
    ] = UNSET

    chunk_index: Annotated[
        OptionalNullable[int], pydantic.Field(alias="chunkIndex")
    ] = UNSET

    sheet_name: Annotated[OptionalNullable[str], pydantic.Field(alias="sheetName")] = (
        UNSET
    )

    sheet_num: Annotated[OptionalNullable[int], pydantic.Field(alias="sheetNum")] = (
        UNSET
    )

    web_url: Annotated[OptionalNullable[str], pydantic.Field(alias="webUrl")] = UNSET

    preview_renderable: Annotated[
        OptionalNullable[bool], pydantic.Field(alias="previewRenderable")
    ] = UNSET

    hide_weburl: Annotated[
        OptionalNullable[bool], pydantic.Field(alias="hideWeburl")
    ] = UNSET

    categories: OptionalNullable[List[str]] = UNSET

    departments: OptionalNullable[List[str]] = UNSET

    topics: OptionalNullable[List[str]] = UNSET

    languages: OptionalNullable[List[str]] = UNSET

    subcategory_level1: Annotated[
        OptionalNullable[str], pydantic.Field(alias="subcategoryLevel1")
    ] = UNSET

    subcategory_level2: Annotated[
        OptionalNullable[str], pydantic.Field(alias="subcategoryLevel2")
    ] = UNSET

    subcategory_level3: Annotated[
        OptionalNullable[str], pydantic.Field(alias="subcategoryLevel3")
    ] = UNSET

    score: OptionalNullable[float] = UNSET

    id: Annotated[OptionalNullable[str], pydantic.Field(alias="_id")] = UNSET

    collection_name: Annotated[
        OptionalNullable[str], pydantic.Field(alias="_collection_name")
    ] = UNSET

    block_index: Annotated[
        OptionalNullable[int], pydantic.Field(alias="blockIndex")
    ] = UNSET

    block_id: Annotated[OptionalNullable[str], pydantic.Field(alias="blockId")] = UNSET

    is_block: Annotated[OptionalNullable[bool], pydantic.Field(alias="isBlock")] = UNSET

    is_block_group: Annotated[
        OptionalNullable[bool], pydantic.Field(alias="isBlockGroup")
    ] = UNSET

    is_record_summary: Annotated[
        OptionalNullable[bool], pydantic.Field(alias="isRecordSummary")
    ] = UNSET
    r"""Set to `true` by the indexing pipeline when this vector chunk represents a
    whole-record semantic summary rather than an individual block. When true,
    `blockIndex` is absent and `block_type` on the parent hit is `record_summary`.

    """

    kb_id: Annotated[OptionalNullable[str], pydantic.Field(alias="kbId")] = UNSET
    r"""Knowledge base id merged from graph record during retrieval (when present)."""

    point_id: OptionalNullable[PointID] = UNSET
    r"""Qdrant point identifier attached during vector lookup (shape varies by deployment)."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "orgId",
                "recordId",
                "virtualRecordId",
                "recordName",
                "recordType",
                "recordVersion",
                "origin",
                "connector",
                "connectorId",
                "connectorName",
                "blockText",
                "blockType",
                "bounding_box",
                "pageNum",
                "extension",
                "mimeType",
                "blockNum",
                "chunkIndex",
                "sheetName",
                "sheetNum",
                "webUrl",
                "previewRenderable",
                "hideWeburl",
                "categories",
                "departments",
                "topics",
                "languages",
                "subcategoryLevel1",
                "subcategoryLevel2",
                "subcategoryLevel3",
                "score",
                "_id",
                "_collection_name",
                "blockIndex",
                "blockId",
                "isBlock",
                "isBlockGroup",
                "isRecordSummary",
                "kbId",
                "point_id",
            ]
        )
        nullable_fields = set(
            [
                "orgId",
                "recordId",
                "virtualRecordId",
                "recordName",
                "recordType",
                "recordVersion",
                "origin",
                "connector",
                "connectorId",
                "connectorName",
                "blockText",
                "blockType",
                "bounding_box",
                "pageNum",
                "extension",
                "mimeType",
                "blockNum",
                "chunkIndex",
                "sheetName",
                "sheetNum",
                "webUrl",
                "previewRenderable",
                "hideWeburl",
                "categories",
                "departments",
                "topics",
                "languages",
                "subcategoryLevel1",
                "subcategoryLevel2",
                "subcategoryLevel3",
                "score",
                "_id",
                "_collection_name",
                "blockIndex",
                "blockId",
                "isBlock",
                "isBlockGroup",
                "isRecordSummary",
                "kbId",
                "point_id",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


try:
    SemanticSearchHitMetadata.model_rebuild()
except NameError:
    pass
