"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .agentaddmessagestreamrequest import (
    AgentAddMessageStreamRequest,
    AgentAddMessageStreamRequestTypedDict,
)
from pipeshub_sdk.types import BaseModel
from pipeshub_sdk.utils import FieldMetadata, PathParamMetadata, RequestMetadata
import pydantic
from typing_extensions import Annotated, TypedDict


class StreamAgentConversationMessageRequestTypedDict(TypedDict):
    agent_key: str
    conversation_id: str
    body: AgentAddMessageStreamRequestTypedDict
    r"""Follow-up message payload for the agent conversation stream."""


class StreamAgentConversationMessageRequest(BaseModel):
    agent_key: Annotated[
        str,
        pydantic.Field(alias="agentKey"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]

    conversation_id: Annotated[
        str,
        pydantic.Field(alias="conversationId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]

    body: Annotated[
        AgentAddMessageStreamRequest,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
    r"""Follow-up message payload for the agent conversation stream."""
