"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: a01e43c89901

from __future__ import annotations
from pipeshub_sdk.types import BaseModel, UNSET_SENTINEL
from pipeshub_sdk.utils import FieldMetadata, PathParamMetadata, RequestMetadata
import pydantic
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class UpdateToolsetCredentialsAuthTypedDict(TypedDict):
    email: NotRequired[str]
    api_token: NotRequired[str]
    username: NotRequired[str]
    password: NotRequired[str]


class UpdateToolsetCredentialsAuth(BaseModel):
    email: Optional[str] = None

    api_token: Annotated[Optional[str], pydantic.Field(alias="apiToken")] = None

    username: Optional[str] = None

    password: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["email", "apiToken", "username", "password"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class UpdateToolsetCredentialsRequestBodyTypedDict(TypedDict):
    auth: NotRequired[UpdateToolsetCredentialsAuthTypedDict]


class UpdateToolsetCredentialsRequestBody(BaseModel):
    auth: Optional[UpdateToolsetCredentialsAuth] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["auth"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class UpdateToolsetCredentialsRequestTypedDict(TypedDict):
    instance_id: str
    body: UpdateToolsetCredentialsRequestBodyTypedDict


class UpdateToolsetCredentialsRequest(BaseModel):
    instance_id: Annotated[
        str,
        pydantic.Field(alias="instanceId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]

    body: Annotated[
        UpdateToolsetCredentialsRequestBody,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]


try:
    UpdateToolsetCredentialsAuth.model_rebuild()
except NameError:
    pass
