"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .appliedfilternode import AppliedFilterNode, AppliedFilterNodeTypedDict
from .citationreference import CitationReference, CitationReferenceTypedDict
from .conversationmodelinfo import ConversationModelInfo, ConversationModelInfoTypedDict
from .followupquestion import FollowUpQuestion, FollowUpQuestionTypedDict
from .messagefeedback import MessageFeedback, MessageFeedbackTypedDict
from datetime import datetime
from pipeshub_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
    UnrecognizedStr,
)
from pipeshub_sdk.utils import FieldMetadata, PathParamMetadata, RequestMetadata
import pydantic
from pydantic import model_serializer
from typing import Any, Dict, List, Literal, Optional, Union
from typing_extensions import Annotated, NotRequired, TypedDict


class UpdateConversationTitleRequestBodyTypedDict(TypedDict):
    r"""Request payload"""

    title: str
    r"""New conversation title"""


class UpdateConversationTitleRequestBody(BaseModel):
    r"""Request payload"""

    title: str
    r"""New conversation title"""


class UpdateConversationTitleRequestTypedDict(TypedDict):
    conversation_id: str
    r"""Unique conversation identifier"""
    body: UpdateConversationTitleRequestBodyTypedDict
    r"""Request payload"""


class UpdateConversationTitleRequest(BaseModel):
    conversation_id: Annotated[
        str,
        pydantic.Field(alias="conversationId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""Unique conversation identifier"""

    body: Annotated[
        UpdateConversationTitleRequestBody,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
    r"""Request payload"""


UpdateConversationTitleMessageType = Union[
    Literal[
        "user_query",
        "bot_response",
        "error",
        "feedback",
        "system",
    ],
    UnrecognizedStr,
]


UpdateConversationTitleContentFormat = Union[
    Literal[
        "MARKDOWN",
        "JSON",
        "HTML",
    ],
    UnrecognizedStr,
]


class UpdateConversationTitleReferenceDatumTypedDict(TypedDict):
    name: NotRequired[str]
    r"""Display name shown to the user."""
    id: NotRequired[str]
    r"""Technical identifier (numeric ID, UUID, etc.)."""
    type: NotRequired[str]
    r"""Item type (e.g. `project`, `issue`, `file`, `notebook`, `page`)."""
    app: NotRequired[str]
    r"""Source application (e.g. `jira`, `confluence`,
    `sharepoint`, `slack`, `drive`, `gmail`).

    """
    web_url: NotRequired[str]
    r"""URL to open the item in a browser."""
    metadata: NotRequired[Dict[str, str]]
    r"""App-specific fields keyed by name (e.g. `key` for a Jira
    project, `siteId` for a SharePoint document).

    """


class UpdateConversationTitleReferenceDatum(BaseModel):
    name: Optional[str] = None
    r"""Display name shown to the user."""

    id: Optional[str] = None
    r"""Technical identifier (numeric ID, UUID, etc.)."""

    type: Optional[str] = None
    r"""Item type (e.g. `project`, `issue`, `file`, `notebook`, `page`)."""

    app: Optional[str] = None
    r"""Source application (e.g. `jira`, `confluence`,
    `sharepoint`, `slack`, `drive`, `gmail`).

    """

    web_url: Annotated[Optional[str], pydantic.Field(alias="webUrl")] = None
    r"""URL to open the item in a browser."""

    metadata: Optional[Dict[str, str]] = None
    r"""App-specific fields keyed by name (e.g. `key` for a Jira
    project, `siteId` for a SharePoint document).

    """

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["name", "id", "type", "app", "webUrl", "metadata"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class UpdateConversationTitleAppliedFiltersTypedDict(TypedDict):
    apps: NotRequired[List[AppliedFilterNodeTypedDict]]
    kb: NotRequired[List[AppliedFilterNodeTypedDict]]


class UpdateConversationTitleAppliedFilters(BaseModel):
    apps: Optional[List[AppliedFilterNode]] = None

    kb: Optional[List[AppliedFilterNode]] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["apps", "kb"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class UpdateConversationTitleMetadataTypedDict(TypedDict):
    processing_time_ms: NotRequired[float]
    model_version: NotRequired[str]
    ai_transaction_id: NotRequired[str]
    reason: NotRequired[str]


class UpdateConversationTitleMetadata(BaseModel):
    processing_time_ms: Annotated[
        Optional[float], pydantic.Field(alias="processingTimeMs")
    ] = None

    model_version: Annotated[Optional[str], pydantic.Field(alias="modelVersion")] = None

    ai_transaction_id: Annotated[
        Optional[str], pydantic.Field(alias="aiTransactionId")
    ] = None

    reason: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["processingTimeMs", "modelVersion", "aiTransactionId", "reason"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class UpdateConversationTitleMessageTypedDict(TypedDict):
    id: str
    message_type: UpdateConversationTitleMessageType
    content: str
    citations: List[CitationReferenceTypedDict]
    r"""References to source documents used in the
    response, stored as raw citation pointers
    (not populated on this endpoint).

    """
    follow_up_questions: List[FollowUpQuestionTypedDict]
    feedback: List[MessageFeedbackTypedDict]
    reference_data: List[UpdateConversationTitleReferenceDatumTypedDict]
    r"""Reference IDs surfaced from tool responses,
    used for follow-up queries.

    """
    created_at: datetime
    updated_at: datetime
    content_format: NotRequired[UpdateConversationTitleContentFormat]
    confidence: NotRequired[str]
    r"""AI confidence in the answer. Present only on
    `bot_response` messages, and only when the
    model emitted a trailing confidence block.

    """
    model_info: NotRequired[ConversationModelInfoTypedDict]
    r"""AI model configuration recorded against a conversation or message."""
    applied_filters: NotRequired[UpdateConversationTitleAppliedFiltersTypedDict]
    metadata: NotRequired[UpdateConversationTitleMetadataTypedDict]


class UpdateConversationTitleMessage(BaseModel):
    id: Annotated[str, pydantic.Field(alias="_id")]

    message_type: Annotated[
        UpdateConversationTitleMessageType, pydantic.Field(alias="messageType")
    ]

    content: str

    citations: List[CitationReference]
    r"""References to source documents used in the
    response, stored as raw citation pointers
    (not populated on this endpoint).

    """

    follow_up_questions: Annotated[
        List[FollowUpQuestion], pydantic.Field(alias="followUpQuestions")
    ]

    feedback: List[MessageFeedback]

    reference_data: Annotated[
        List[UpdateConversationTitleReferenceDatum],
        pydantic.Field(alias="referenceData"),
    ]
    r"""Reference IDs surfaced from tool responses,
    used for follow-up queries.

    """

    created_at: Annotated[datetime, pydantic.Field(alias="createdAt")]

    updated_at: Annotated[datetime, pydantic.Field(alias="updatedAt")]

    content_format: Annotated[
        Optional[UpdateConversationTitleContentFormat],
        pydantic.Field(alias="contentFormat"),
    ] = "MARKDOWN"

    confidence: Optional[str] = None
    r"""AI confidence in the answer. Present only on
    `bot_response` messages, and only when the
    model emitted a trailing confidence block.

    """

    model_info: Annotated[
        Optional[ConversationModelInfo], pydantic.Field(alias="modelInfo")
    ] = None
    r"""AI model configuration recorded against a conversation or message."""

    applied_filters: Annotated[
        Optional[UpdateConversationTitleAppliedFilters],
        pydantic.Field(alias="appliedFilters"),
    ] = None

    metadata: Optional[UpdateConversationTitleMetadata] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["contentFormat", "confidence", "modelInfo", "appliedFilters", "metadata"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


UpdateConversationTitleStatus = Union[
    Literal[
        "None",
        "Inprogress",
        "Complete",
        "Failed",
    ],
    UnrecognizedStr,
]
r"""Current status of the conversation:
- `None` — no activity yet
- `Inprogress` — AI is processing
- `Complete` — response ready
- `Failed` — error occurred

"""


UpdateConversationTitleAccessLevel = Union[
    Literal[
        "read",
        "write",
    ],
    UnrecognizedStr,
]


class UpdateConversationTitleSharedWithTypedDict(TypedDict):
    user_id: str
    access_level: NotRequired[UpdateConversationTitleAccessLevel]


class UpdateConversationTitleSharedWith(BaseModel):
    user_id: Annotated[str, pydantic.Field(alias="userId")]

    access_level: Annotated[
        Optional[UpdateConversationTitleAccessLevel],
        pydantic.Field(alias="accessLevel"),
    ] = "read"

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["accessLevel"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class UpdateConversationTitleConversationErrorTypedDict(TypedDict):
    id: str
    r"""Sub-document identifier auto-assigned by MongoDB."""
    message: str
    timestamp: datetime
    r"""Time the error was recorded. Server-defaulted
    to `Date.now` when the entry is pushed, so
    always present.

    """
    error_type: NotRequired[str]
    message_id: NotRequired[str]
    stack: NotRequired[str]
    metadata: NotRequired[Dict[str, Any]]
    r"""Free-form metadata attached to this error
    entry (Map of Mixed in the schema).

    """


class UpdateConversationTitleConversationError(BaseModel):
    id: Annotated[str, pydantic.Field(alias="_id")]
    r"""Sub-document identifier auto-assigned by MongoDB."""

    message: str

    timestamp: datetime
    r"""Time the error was recorded. Server-defaulted
    to `Date.now` when the entry is pushed, so
    always present.

    """

    error_type: Annotated[Optional[str], pydantic.Field(alias="errorType")] = None

    message_id: Annotated[Optional[str], pydantic.Field(alias="messageId")] = None

    stack: Optional[str] = None

    metadata: Optional[Dict[str, Any]] = None
    r"""Free-form metadata attached to this error
    entry (Map of Mixed in the schema).

    """

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["errorType", "messageId", "stack", "metadata"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class UpdateConversationTitleConversationTypedDict(TypedDict):
    r"""The full conversation document after the title update,
    returned as stored in MongoDB.

    """

    id: str
    r"""Unique conversation identifier"""
    user_id: str
    r"""ID of the user who owns this conversation"""
    org_id: str
    r"""Organization this conversation belongs to"""
    initiator: str
    r"""User who started the conversation"""
    messages: List[UpdateConversationTitleMessageTypedDict]
    r"""All messages stored on this conversation."""
    shared_with: List[UpdateConversationTitleSharedWithTypedDict]
    r"""Users this conversation is shared with"""
    conversation_errors: List[UpdateConversationTitleConversationErrorTypedDict]
    r"""Errors recorded against this conversation
    (e.g. failed message generations).

    """
    last_activity_at: int
    r"""Unix timestamp of the last activity, stored as
    epoch milliseconds (server-side default `Date.now`).

    """
    created_at: datetime
    updated_at: datetime
    v: int
    r"""Mongoose document version key."""
    title: NotRequired[str]
    r"""Conversation title. Present and equal to the value
    submitted in the request body after a successful
    update.

    """
    status: NotRequired[UpdateConversationTitleStatus]
    r"""Current status of the conversation:
    - `None` — no activity yet
    - `Inprogress` — AI is processing
    - `Complete` — response ready
    - `Failed` — error occurred

    """
    fail_reason: NotRequired[str]
    r"""Error description, populated only when `status`
    is `Failed`.

    """
    model_info: NotRequired[ConversationModelInfoTypedDict]
    r"""AI model configuration recorded against a conversation or message."""
    is_shared: NotRequired[bool]
    r"""Whether this conversation is shared with others"""
    share_link: NotRequired[str]
    r"""Shareable link if the conversation is shared"""
    is_archived: NotRequired[bool]
    r"""Whether this conversation is archived"""
    archived_by: NotRequired[Nullable[str]]
    r"""User ID of the last user who archived this row, or `null` after
    unarchive cleared the archive state. Absent on rows that have
    never been archived.

    """
    is_deleted: NotRequired[bool]
    r"""Whether this conversation has been soft-deleted."""
    deleted_by: NotRequired[str]
    r"""User who soft-deleted this conversation."""
    metadata: NotRequired[Dict[str, Any]]
    r"""Free-form metadata attached to the conversation."""


class UpdateConversationTitleConversation(BaseModel):
    r"""The full conversation document after the title update,
    returned as stored in MongoDB.

    """

    id: Annotated[str, pydantic.Field(alias="_id")]
    r"""Unique conversation identifier"""

    user_id: Annotated[str, pydantic.Field(alias="userId")]
    r"""ID of the user who owns this conversation"""

    org_id: Annotated[str, pydantic.Field(alias="orgId")]
    r"""Organization this conversation belongs to"""

    initiator: str
    r"""User who started the conversation"""

    messages: List[UpdateConversationTitleMessage]
    r"""All messages stored on this conversation."""

    shared_with: Annotated[
        List[UpdateConversationTitleSharedWith], pydantic.Field(alias="sharedWith")
    ]
    r"""Users this conversation is shared with"""

    conversation_errors: Annotated[
        List[UpdateConversationTitleConversationError],
        pydantic.Field(alias="conversationErrors"),
    ]
    r"""Errors recorded against this conversation
    (e.g. failed message generations).

    """

    last_activity_at: Annotated[int, pydantic.Field(alias="lastActivityAt")]
    r"""Unix timestamp of the last activity, stored as
    epoch milliseconds (server-side default `Date.now`).

    """

    created_at: Annotated[datetime, pydantic.Field(alias="createdAt")]

    updated_at: Annotated[datetime, pydantic.Field(alias="updatedAt")]

    v: Annotated[int, pydantic.Field(alias="__v")]
    r"""Mongoose document version key."""

    title: Optional[str] = None
    r"""Conversation title. Present and equal to the value
    submitted in the request body after a successful
    update.

    """

    status: Optional[UpdateConversationTitleStatus] = None
    r"""Current status of the conversation:
    - `None` — no activity yet
    - `Inprogress` — AI is processing
    - `Complete` — response ready
    - `Failed` — error occurred

    """

    fail_reason: Annotated[Optional[str], pydantic.Field(alias="failReason")] = None
    r"""Error description, populated only when `status`
    is `Failed`.

    """

    model_info: Annotated[
        Optional[ConversationModelInfo], pydantic.Field(alias="modelInfo")
    ] = None
    r"""AI model configuration recorded against a conversation or message."""

    is_shared: Annotated[Optional[bool], pydantic.Field(alias="isShared")] = False
    r"""Whether this conversation is shared with others"""

    share_link: Annotated[Optional[str], pydantic.Field(alias="shareLink")] = None
    r"""Shareable link if the conversation is shared"""

    is_archived: Annotated[Optional[bool], pydantic.Field(alias="isArchived")] = False
    r"""Whether this conversation is archived"""

    archived_by: Annotated[
        OptionalNullable[str], pydantic.Field(alias="archivedBy")
    ] = UNSET
    r"""User ID of the last user who archived this row, or `null` after
    unarchive cleared the archive state. Absent on rows that have
    never been archived.

    """

    is_deleted: Annotated[Optional[bool], pydantic.Field(alias="isDeleted")] = False
    r"""Whether this conversation has been soft-deleted."""

    deleted_by: Annotated[Optional[str], pydantic.Field(alias="deletedBy")] = None
    r"""User who soft-deleted this conversation."""

    metadata: Optional[Dict[str, Any]] = None
    r"""Free-form metadata attached to the conversation."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "title",
                "status",
                "failReason",
                "modelInfo",
                "isShared",
                "shareLink",
                "isArchived",
                "archivedBy",
                "isDeleted",
                "deletedBy",
                "metadata",
            ]
        )
        nullable_fields = set(["archivedBy"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


class UpdateConversationTitleMetaTypedDict(TypedDict):
    request_id: str
    r"""Server-side request identifier. Read from the
    `X-Request-ID` header when supplied, otherwise
    auto-generated, so this field is always present.

    """
    timestamp: datetime
    duration: int
    r"""Server-side processing time in milliseconds."""


class UpdateConversationTitleMeta(BaseModel):
    request_id: Annotated[str, pydantic.Field(alias="requestId")]
    r"""Server-side request identifier. Read from the
    `X-Request-ID` header when supplied, otherwise
    auto-generated, so this field is always present.

    """

    timestamp: datetime

    duration: int
    r"""Server-side processing time in milliseconds."""


class UpdateConversationTitleResponseTypedDict(TypedDict):
    r"""Title updated successfully"""

    conversation: UpdateConversationTitleConversationTypedDict
    r"""The full conversation document after the title update,
    returned as stored in MongoDB.

    """
    meta: UpdateConversationTitleMetaTypedDict


class UpdateConversationTitleResponse(BaseModel):
    r"""Title updated successfully"""

    conversation: UpdateConversationTitleConversation
    r"""The full conversation document after the title update,
    returned as stored in MongoDB.

    """

    meta: UpdateConversationTitleMeta


try:
    UpdateConversationTitleReferenceDatum.model_rebuild()
except NameError:
    pass
try:
    UpdateConversationTitleMetadata.model_rebuild()
except NameError:
    pass
try:
    UpdateConversationTitleMessage.model_rebuild()
except NameError:
    pass
try:
    UpdateConversationTitleSharedWith.model_rebuild()
except NameError:
    pass
try:
    UpdateConversationTitleConversationError.model_rebuild()
except NameError:
    pass
try:
    UpdateConversationTitleConversation.model_rebuild()
except NameError:
    pass
try:
    UpdateConversationTitleMeta.model_rebuild()
except NameError:
    pass
