"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: 065f4c031af3

from __future__ import annotations
from .conversation import Conversation, ConversationTypedDict
from datetime import datetime
from pipeshub_sdk.types import BaseModel, UNSET_SENTINEL
from pipeshub_sdk.utils import FieldMetadata, PathParamMetadata, RequestMetadata
import pydantic
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class UpdateConversationTitleRequestBodyTypedDict(TypedDict):
    r"""Request payload"""

    title: str
    r"""New conversation title"""


class UpdateConversationTitleRequestBody(BaseModel):
    r"""Request payload"""

    title: str
    r"""New conversation title"""


class UpdateConversationTitleRequestTypedDict(TypedDict):
    conversation_id: str
    body: UpdateConversationTitleRequestBodyTypedDict
    r"""Request payload"""


class UpdateConversationTitleRequest(BaseModel):
    conversation_id: Annotated[
        str,
        pydantic.Field(alias="conversationId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]

    body: Annotated[
        UpdateConversationTitleRequestBody,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
    r"""Request payload"""


class UpdateConversationTitleMetaTypedDict(TypedDict):
    request_id: NotRequired[str]
    timestamp: NotRequired[datetime]
    duration: NotRequired[int]


class UpdateConversationTitleMeta(BaseModel):
    request_id: Annotated[Optional[str], pydantic.Field(alias="requestId")] = None

    timestamp: Optional[datetime] = None

    duration: Optional[int] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["requestId", "timestamp", "duration"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class UpdateConversationTitleResponseTypedDict(TypedDict):
    r"""Title updated successfully"""

    conversation: NotRequired[ConversationTypedDict]
    r"""A conversation represents a chat session between a user and the AI.
    Conversations maintain context across multiple messages and can be
    shared, archived, and organized.

    """
    meta: NotRequired[UpdateConversationTitleMetaTypedDict]


class UpdateConversationTitleResponse(BaseModel):
    r"""Title updated successfully"""

    conversation: Optional[Conversation] = None
    r"""A conversation represents a chat session between a user and the AI.
    Conversations maintain context across multiple messages and can be
    shared, archived, and organized.

    """

    meta: Optional[UpdateConversationTitleMeta] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["conversation", "meta"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    UpdateConversationTitleMeta.model_rebuild()
except NameError:
    pass
