"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .oauthappresponse import OAuthAppResponse, OAuthAppResponseTypedDict
from pipeshub_sdk.types import BaseModel
from typing_extensions import TypedDict


class UpdateOAuthAppResponseTypedDict(TypedDict):
    r"""Response body for `PUT /oauth-clients/{appId}` (`oauth.app.controller.ts` `updateApp`).
    Updated app (never includes `clientSecret`) is nested under `app`.

    """

    message: str
    app: OAuthAppResponseTypedDict
    r"""OAuth app details (without secret). Fields under `required:` always appear
    in `toAppResponse` (`oauth.app.service.ts`); optional URL/description fields
    are only present when set by the caller.

    """


class UpdateOAuthAppResponse(BaseModel):
    r"""Response body for `PUT /oauth-clients/{appId}` (`oauth.app.controller.ts` `updateApp`).
    Updated app (never includes `clientSecret`) is nested under `app`.

    """

    message: str

    app: OAuthAppResponse
    r"""OAuth app details (without secret). Fields under `required:` always appear
    in `toAppResponse` (`oauth.app.service.ts`); optional URL/description fields
    are only present when set by the caller.

    """
