"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .messagefeedbacksubmitrequest import (
    MessageFeedbackSubmitRequest,
    MessageFeedbackSubmitRequestTypedDict,
)
from pipeshub_sdk.types import BaseModel
from pipeshub_sdk.utils import FieldMetadata, PathParamMetadata, RequestMetadata
import pydantic
from typing_extensions import Annotated, TypedDict


class UpdateMessageFeedbackRequestTypedDict(TypedDict):
    conversation_id: str
    r"""Unique conversation identifier."""
    message_id: str
    r"""Identifier of the bot-response message being rated."""
    body: MessageFeedbackSubmitRequestTypedDict
    r"""Request payload"""


class UpdateMessageFeedbackRequest(BaseModel):
    conversation_id: Annotated[
        str,
        pydantic.Field(alias="conversationId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""Unique conversation identifier."""

    message_id: Annotated[
        str,
        pydantic.Field(alias="messageId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""Identifier of the bot-response message being rated."""

    body: Annotated[
        MessageFeedbackSubmitRequest,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
    r"""Request payload"""
