"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .authstep import AuthStep, AuthStepTypedDict
from pipeshub_sdk.types import BaseModel
import pydantic
from typing import List
from typing_extensions import Annotated, TypedDict


class UpdateAuthMethodResponseTypedDict(TypedDict):
    r"""Response after updating organization authentication methods"""

    message: str
    auth_method: List[AuthStepTypedDict]
    r"""Updated authentication steps (same shape as request body)"""


class UpdateAuthMethodResponse(BaseModel):
    r"""Response after updating organization authentication methods"""

    message: str

    auth_method: Annotated[List[AuthStep], pydantic.Field(alias="authMethod")]
    r"""Updated authentication steps (same shape as request body)"""


try:
    UpdateAuthMethodResponse.model_rebuild()
except NameError:
    pass
