"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .conversationmodelinfo import ConversationModelInfo, ConversationModelInfoTypedDict
from datetime import datetime
from pipeshub_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
    UnrecognizedStr,
)
from pipeshub_sdk.utils import FieldMetadata, PathParamMetadata, RequestMetadata
import pydantic
from pydantic import model_serializer
from typing import Any, Dict, List, Literal, Optional, Union
from typing_extensions import Annotated, NotRequired, TypedDict


class UpdateConversationTitleRequestBodyTypedDict(TypedDict):
    r"""Request payload"""

    title: str
    r"""New conversation title"""


class UpdateConversationTitleRequestBody(BaseModel):
    r"""Request payload"""

    title: str
    r"""New conversation title"""


class UpdateConversationTitleRequestTypedDict(TypedDict):
    conversation_id: str
    r"""Unique conversation identifier"""
    body: UpdateConversationTitleRequestBodyTypedDict
    r"""Request payload"""


class UpdateConversationTitleRequest(BaseModel):
    conversation_id: Annotated[
        str,
        pydantic.Field(alias="conversationId"),
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""Unique conversation identifier"""

    body: Annotated[
        UpdateConversationTitleRequestBody,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
    r"""Request payload"""


UpdateConversationTitleStatus = Union[
    Literal[
        "None",
        "Inprogress",
        "Complete",
        "Failed",
        "Stopped",
    ],
    UnrecognizedStr,
]
r"""Current status of the conversation:
- `None` — no activity yet
- `Inprogress` — AI is processing
- `Complete` — response ready
- `Failed` — error occurred
- `Stopped` — cancelled, or the client disconnected mid-answer

"""


UpdateConversationTitleAccessLevel = Union[
    Literal[
        "read",
        "write",
    ],
    UnrecognizedStr,
]


class UpdateConversationTitleSharedWithTypedDict(TypedDict):
    user_id: str
    access_level: NotRequired[UpdateConversationTitleAccessLevel]


class UpdateConversationTitleSharedWith(BaseModel):
    user_id: Annotated[str, pydantic.Field(alias="userId")]

    access_level: Annotated[
        Optional[UpdateConversationTitleAccessLevel],
        pydantic.Field(alias="accessLevel"),
    ] = "read"

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["accessLevel"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class UpdateConversationTitleConversationErrorTypedDict(TypedDict):
    id: str
    r"""Sub-document identifier auto-assigned by MongoDB."""
    message: str
    timestamp: datetime
    r"""Time the error was recorded. Server-defaulted
    to `Date.now` when the entry is pushed, so
    always present.

    """
    error_type: NotRequired[str]
    message_id: NotRequired[str]
    stack: NotRequired[str]
    metadata: NotRequired[Dict[str, Any]]
    r"""Free-form metadata attached to this error
    entry (Map of Mixed in the schema).

    """


class UpdateConversationTitleConversationError(BaseModel):
    id: Annotated[str, pydantic.Field(alias="_id")]
    r"""Sub-document identifier auto-assigned by MongoDB."""

    message: str

    timestamp: datetime
    r"""Time the error was recorded. Server-defaulted
    to `Date.now` when the entry is pushed, so
    always present.

    """

    error_type: Annotated[Optional[str], pydantic.Field(alias="errorType")] = None

    message_id: Annotated[Optional[str], pydantic.Field(alias="messageId")] = None

    stack: Optional[str] = None

    metadata: Optional[Dict[str, Any]] = None
    r"""Free-form metadata attached to this error
    entry (Map of Mixed in the schema).

    """

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["errorType", "messageId", "stack", "metadata"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class UpdateConversationTitleConversationTypedDict(TypedDict):
    r"""The conversation document after the title update, as
    stored in the `chatSessions` collection.

    Carries no `messages`: they live in `chatSessionMessages`
    (see `chat.session.schema.ts`) and this route neither
    reads nor joins them. Fetch the conversation by id to
    get its messages.

    """

    id: str
    r"""Unique conversation identifier"""
    user_id: str
    r"""ID of the user who owns this conversation"""
    org_id: str
    r"""Organization this conversation belongs to"""
    initiator: str
    r"""User who started the conversation"""
    shared_with: List[UpdateConversationTitleSharedWithTypedDict]
    r"""Users this conversation is shared with"""
    conversation_errors: List[UpdateConversationTitleConversationErrorTypedDict]
    r"""Errors recorded against this conversation
    (e.g. failed message generations).

    """
    last_activity_at: int
    r"""Unix timestamp of the last activity, stored as
    epoch milliseconds (server-side default `Date.now`).

    """
    created_at: datetime
    updated_at: datetime
    v: int
    r"""Mongoose document version key."""
    title: NotRequired[str]
    r"""Conversation title. Present and equal to the value
    submitted in the request body after a successful
    update.

    """
    status: NotRequired[UpdateConversationTitleStatus]
    r"""Current status of the conversation:
    - `None` — no activity yet
    - `Inprogress` — AI is processing
    - `Complete` — response ready
    - `Failed` — error occurred
    - `Stopped` — cancelled, or the client disconnected mid-answer

    """
    fail_reason: NotRequired[str]
    r"""Error description, populated only when `status`
    is `Failed`.

    """
    model_info: NotRequired[ConversationModelInfoTypedDict]
    r"""AI model configuration recorded against a conversation or message."""
    is_shared: NotRequired[bool]
    r"""Whether this conversation is shared with others"""
    share_link: NotRequired[str]
    r"""Shareable link if the conversation is shared"""
    is_archived: NotRequired[bool]
    r"""Whether this conversation is archived"""
    archived_by: NotRequired[Nullable[str]]
    r"""User ID of the last user who archived this row, or `null` after
    unarchive cleared the archive state. Absent on rows that have
    never been archived.

    """
    is_deleted: NotRequired[bool]
    r"""Whether this conversation has been soft-deleted."""
    deleted_by: NotRequired[str]
    r"""User who soft-deleted this conversation."""
    metadata: NotRequired[Dict[str, Any]]
    r"""Free-form metadata attached to the conversation."""


class UpdateConversationTitleConversation(BaseModel):
    r"""The conversation document after the title update, as
    stored in the `chatSessions` collection.

    Carries no `messages`: they live in `chatSessionMessages`
    (see `chat.session.schema.ts`) and this route neither
    reads nor joins them. Fetch the conversation by id to
    get its messages.

    """

    id: Annotated[str, pydantic.Field(alias="_id")]
    r"""Unique conversation identifier"""

    user_id: Annotated[str, pydantic.Field(alias="userId")]
    r"""ID of the user who owns this conversation"""

    org_id: Annotated[str, pydantic.Field(alias="orgId")]
    r"""Organization this conversation belongs to"""

    initiator: str
    r"""User who started the conversation"""

    shared_with: Annotated[
        List[UpdateConversationTitleSharedWith], pydantic.Field(alias="sharedWith")
    ]
    r"""Users this conversation is shared with"""

    conversation_errors: Annotated[
        List[UpdateConversationTitleConversationError],
        pydantic.Field(alias="conversationErrors"),
    ]
    r"""Errors recorded against this conversation
    (e.g. failed message generations).

    """

    last_activity_at: Annotated[int, pydantic.Field(alias="lastActivityAt")]
    r"""Unix timestamp of the last activity, stored as
    epoch milliseconds (server-side default `Date.now`).

    """

    created_at: Annotated[datetime, pydantic.Field(alias="createdAt")]

    updated_at: Annotated[datetime, pydantic.Field(alias="updatedAt")]

    v: Annotated[int, pydantic.Field(alias="__v")]
    r"""Mongoose document version key."""

    title: Optional[str] = None
    r"""Conversation title. Present and equal to the value
    submitted in the request body after a successful
    update.

    """

    status: Optional[UpdateConversationTitleStatus] = None
    r"""Current status of the conversation:
    - `None` — no activity yet
    - `Inprogress` — AI is processing
    - `Complete` — response ready
    - `Failed` — error occurred
    - `Stopped` — cancelled, or the client disconnected mid-answer

    """

    fail_reason: Annotated[Optional[str], pydantic.Field(alias="failReason")] = None
    r"""Error description, populated only when `status`
    is `Failed`.

    """

    model_info: Annotated[
        Optional[ConversationModelInfo], pydantic.Field(alias="modelInfo")
    ] = None
    r"""AI model configuration recorded against a conversation or message."""

    is_shared: Annotated[Optional[bool], pydantic.Field(alias="isShared")] = False
    r"""Whether this conversation is shared with others"""

    share_link: Annotated[Optional[str], pydantic.Field(alias="shareLink")] = None
    r"""Shareable link if the conversation is shared"""

    is_archived: Annotated[Optional[bool], pydantic.Field(alias="isArchived")] = False
    r"""Whether this conversation is archived"""

    archived_by: Annotated[
        OptionalNullable[str], pydantic.Field(alias="archivedBy")
    ] = UNSET
    r"""User ID of the last user who archived this row, or `null` after
    unarchive cleared the archive state. Absent on rows that have
    never been archived.

    """

    is_deleted: Annotated[Optional[bool], pydantic.Field(alias="isDeleted")] = False
    r"""Whether this conversation has been soft-deleted."""

    deleted_by: Annotated[Optional[str], pydantic.Field(alias="deletedBy")] = None
    r"""User who soft-deleted this conversation."""

    metadata: Optional[Dict[str, Any]] = None
    r"""Free-form metadata attached to the conversation."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "title",
                "status",
                "failReason",
                "modelInfo",
                "isShared",
                "shareLink",
                "isArchived",
                "archivedBy",
                "isDeleted",
                "deletedBy",
                "metadata",
            ]
        )
        nullable_fields = set(["archivedBy"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


class UpdateConversationTitleMetaTypedDict(TypedDict):
    request_id: str
    r"""Server-side request identifier. Read from the
    `X-Request-ID` header when supplied, otherwise
    auto-generated, so this field is always present.

    """
    timestamp: datetime
    duration: int
    r"""Server-side processing time in milliseconds."""


class UpdateConversationTitleMeta(BaseModel):
    request_id: Annotated[str, pydantic.Field(alias="requestId")]
    r"""Server-side request identifier. Read from the
    `X-Request-ID` header when supplied, otherwise
    auto-generated, so this field is always present.

    """

    timestamp: datetime

    duration: int
    r"""Server-side processing time in milliseconds."""


class UpdateConversationTitleResponseTypedDict(TypedDict):
    r"""Title updated successfully"""

    conversation: UpdateConversationTitleConversationTypedDict
    r"""The conversation document after the title update, as
    stored in the `chatSessions` collection.

    Carries no `messages`: they live in `chatSessionMessages`
    (see `chat.session.schema.ts`) and this route neither
    reads nor joins them. Fetch the conversation by id to
    get its messages.

    """
    meta: UpdateConversationTitleMetaTypedDict


class UpdateConversationTitleResponse(BaseModel):
    r"""Title updated successfully"""

    conversation: UpdateConversationTitleConversation
    r"""The conversation document after the title update, as
    stored in the `chatSessions` collection.

    Carries no `messages`: they live in `chatSessionMessages`
    (see `chat.session.schema.ts`) and this route neither
    reads nor joins them. Fetch the conversation by id to
    get its messages.

    """

    meta: UpdateConversationTitleMeta


try:
    UpdateConversationTitleSharedWith.model_rebuild()
except NameError:
    pass
try:
    UpdateConversationTitleConversationError.model_rebuild()
except NameError:
    pass
try:
    UpdateConversationTitleConversation.model_rebuild()
except NameError:
    pass
try:
    UpdateConversationTitleMeta.model_rebuild()
except NameError:
    pass
