"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .authstep import AuthStep, AuthStepTypedDict
from pipeshub_sdk.types import BaseModel
import pydantic
from typing import List
from typing_extensions import Annotated, TypedDict


class UpdateAuthMethodRequestTypedDict(TypedDict):
    r"""Request payload"""

    auth_method: List[AuthStepTypedDict]
    r"""Authentication steps to set for the organization (1-3 steps)"""


class UpdateAuthMethodRequest(BaseModel):
    r"""Request payload"""

    auth_method: Annotated[List[AuthStep], pydantic.Field(alias="authMethod")]
    r"""Authentication steps to set for the organization (1-3 steps)"""


try:
    UpdateAuthMethodRequest.model_rebuild()
except NameError:
    pass
